#Configuration tested on YAMCS 5.4.0
services:
  - class: org.yamcs.archive.XtceTmRecorder
  - class: org.yamcs.archive.ParameterRecorder
  - class: org.yamcs.archive.AlarmRecorder
  - class: org.yamcs.archive.EventRecorder
  - class: org.yamcs.archive.ReplayServer
  - class: org.yamcs.parameter.SystemParametersCollector
    args:
      provideJvmVariables: true
      provideFsVariables: true
  - class: org.yamcs.ProcessorCreatorService
    args:
      name: realtime
      type: realtime
  - class: org.yamcs.archive.CommandHistoryRecorder
  - class: org.yamcs.parameterarchive.ParameterArchive
    args:
      realtimeFiller:
        enabled: false
      backFiller:
        enabled: true
        warmupTime: 60
  - class: org.yamcs.tctm.cfs.CfsEventDecoder
    args:
      msgIds: [0x0815, 0x0a15] #Always confirm this ID with CFE_EVS configuration
      byteOrder: LITTLE_ENDIAN
      appNameMax: 40
      eventMsgMax: 122
  - class: org.yamcs.cfdp.CfdpService
    name: cfdp0
    args:
      inStream: cfdp_in
      outStream: cfdp_out
      localEntities:
        - name: "0.23"
          id: 23
          bucket: cfdpUp
      remoteEntities:
        - name: "0.24"
          id: 24
          bucket: cfdpDown
      receiverFaultHandlers:
        AckLimitReached: suspend

dataLinks:
  - name: tm_cpd
    class: org.yamcs.tctm.UdpTmDataLink
    stream: "tm_realtime"
    port: 5011
    maxLength: 32768
    packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
    packetPreprocessorArgs:
      byteOrder: LITTLE_ENDIAN
      timestampFormat: CFE_SB_TIME_32_16_SUBS
      timeEncoding:
        epoch: CUSTOM
        epochUTC: "1970-01-01T00:00:00Z"
        timeIncludesLeapSeconds: false

  - name: tc_ppd
    class: org.yamcs.tctm.UdpTcDataLink
    stream: tc_realtime
    host: 192.168.2.155
    tcMaxRate: 10
    stream: tc_realtime
    commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
    commandPreprocessorArgs:
      swapChecksumFc: true


      
  - name: tmtc_cpd
    class: com.windhoverlabs.yamcs.tctm.ccsds.SerialTmTcFrameLink
    device: /dev/radio0
    tm_config:
      stream: tm_realtime
      frameType: TM
      maxFrameLength: 1024
      packetInputStreamClassName: com.windhoverlabs.yamcs.tctm.ccsds.SdlpPacketInputStream
      packetInputStreamArgs:
        asm: "1ACFFC1D"
        minLength: 1024
        maxLength: 1024
        dropMalformed: false
      frameHeaderErrorControlPresent: false
      insertZoneLen.gth: 0
      spacecraftId: 66
      errorDetection: NONE
      frameLength: 1024
      virtualChannels:
        - vcId: 0
          service: PACKET
          ocfPresent: false
          maxPacketLength: 32768 #32KB is the default for CCSDS
          stream: tm_realtime
          #stripEncapsulationHeader: false
          #packetPreprocessorClassName: com.windhoverlabs.yamcs.tctm.PacketPreprocessor
          packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
          packetPreprocessorArgs:
            byteOrder: LITTLE_ENDIAN
            #errorDetection:
            #tcoService:
            timestampFormat: CFE_SB_TIME_32_16_SUBS
            timeEncoding:
              epoch: CUSTOM
              # Normally, the epochUTC value belue should be 1970-01-01T00:00:00Z.
              # However, until we add the capability of synchronizing and saving
              # time, set this to current wall time for convenience.
              epochUTC: "1970-01-01T00:00:00Z"
              timeIncludesLeapSeconds: false
    tc_config:
      spacecraftId: 66
      maxFrameLength: 1024
      cltuEncoding: "BCH"
      priorityScheme: FIFO
      randomizeCltu: false
      cltuStartSequence: "EB90"
      cltuTailSequence: "C5C5C5C5C5C5C579"
      errorDetection: NONE
      virtualChannels:
        - vcId: 1
          service: PACKET
          priority: 1
          commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
          commandPostprocessorArgs:
            swapChecksumFc: true
          stream: tc_realtime
          useCop1: false
          bdAbsolutePriority: false

#    One Serial port for downlink
#  - name: tm_cpd
#    class: org.yamcs.tctm.ccsds.SerialTmFrameLink
#    stream: tm_realtime
#    device: /dev/ttyUSB0
#    frameType: TM
#    #clcwStream:
#    #goodFrameStream:
#    #badFrameStream: 
#    packetInputStreamClassName: org.yamcs.tctm.ccsds.SdlpPacketInputStream
#    packetInputStreamArgs:
#      asm: "1ACFFC1D"
#      minLength: 1024
#      maxLength: 1024
#      dropMalformed: false
#    frameHeaderErrorControlPresent: false
#    insertZoneLength: 0
#    spacecraftId: 66
#    errorDetection: NONE
#    frameLength: 1024
#    virtualChannels:
#      - vcId: 0
#        service: PACKET
#        ocfPresent: false
#        maxPacketLength: 32768 #32KB is the default for CCSDS
#        stream: tm_realtime
#        #stripEncapsulationHeader: false
#        #packetPreprocessorClassName: com.windhoverlabs.yamcs.tctm.PacketPreprocessor
#        packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
#        packetPreprocessorArgs:
#          byteOrder: LITTLE_ENDIAN
#          #errorDetection:
#          #tcoService:
#          timestampFormat: CFE_SB_TIME_32_16_SUBS
#          timeEncoding:
#            epoch: CUSTOM
#            epochUTC: "1970-01-01T00:00:00Z"
#            timeIncludesLeapSeconds: false


# One serial port for downlink and uplink
#  - name: tmtc_cpd
#    class: com.windhoverlabs.yamcs.tctm.ccsds.SerialTmTcFrameLink
#    device: /dev/ttyUSB0
#    tm_config:
#      stream: tm_realtime
#      frameType: TM
#      maxFrameLength: 1024
#      packetInputStreamClassName: com.windhoverlabs.yamcs.tctm.ccsds.SdlpPacketInputStream
#      packetInputStreamArgs:
#        asm: "1ACFFC1D"
#        minLength: 1024
#        maxLength: 1024
#        dropMalformed: false
#      frameHeaderErrorControlPresent: false
#      insertZoneLen.gth: 0
#      spacecraftId: 66
#      errorDetection: NONE
#      frameLength: 1024
#      virtualChannels:
#        - vcId: 0
#          service: PACKET
#          ocfPresent: false
#          maxPacketLength: 32768 #32KB is the default for CCSDS
#          stream: tm_realtime
#          #stripEncapsulationHeader: false
#          #packetPreprocessorClassName: com.windhoverlabs.yamcs.tctm.PacketPreprocessor
#          packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
#          packetPreprocessorArgs:
#            byteOrder: LITTLE_ENDIAN
#            #errorDetection:
#            #tcoService:
#            timestampFormat: CFE_SB_TIME_32_16_SUBS
#            timeEncoding:
#              epoch: CUSTOM
#              epochUTC: "1970-01-01T00:00:00Z"
#              timeIncludesLeapSeconds: false
#    tc_config:
#        spacecraftId: 66
#        maxFrameLength: 1024
#        cltuEncoding: "BCH"
#        priorityScheme: FIFO
#        randomizeCltu: false
#        cltuStartSequence: "EB90"
#        cltuTailSequence: "C5C5C5C5C5C5C579"
#        errorDetection: NONE
#        virtualChannels:
#          - vcId: 1
#            service: PACKET
#            priority: 1
#            commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
#            commandPostprocessorArgs:
#              swapChecksumFc: true
#            stream: tc_realtime
#            useCop1: false
#            bdAbsolutePriority: false

mdb:
    # Configuration of the active loaders
    # Valid loaders are: sheet, xtce or fully qualified name of the class
    - type: "xtce"
      spec: "mdb/cfs-ccsds.xml"
      subLoaders:
      - type: "xtce"
        spec: "mdb/PPD.xml"
      - type: "xtce"
        spec: "mdb/CPD.xml"

# Configuration for streams created at server startup
streamConfig:
  tm:
    - name: "tm_realtime"
    - name: "tm_dump"
  cmdHist: ["cmdhist_realtime", "cmdhist_dump"]
  event: ["events_realtime", "events_dump"]
  param: ["pp_realtime", "sys_param", "proc_param"]
  parameterAlarm: ["alarms_realtime"]
  tc: ["tc_realtime"]
  sqlFile: "etc/extra_streams.sql"
