#Configuration tested on YAMCS 5.4.0
services:
  - class: org.yamcs.archive.XtceTmRecorder
  - class: org.yamcs.archive.ParameterRecorder
  - class: org.yamcs.archive.AlarmRecorder
  - class: org.yamcs.archive.EventRecorder
  - class: org.yamcs.archive.ReplayServer
  - class: org.yamcs.parameter.SystemParametersCollector
    args:
      provideJvmVariables: true
      provideFsVariables: true
  - class: org.yamcs.ProcessorCreatorService
    args:
      name: realtime
      type: realtime
  - class: org.yamcs.archive.CommandHistoryRecorder
  - class: org.yamcs.parameterarchive.ParameterArchive
    args:
      realtimeFiller:
        enabled: false
      backFiller:
        enabled: true
        warmupTime: 60
  - class: org.yamcs.tctm.cfs.CfsEventDecoder
    args:
      msgIds: [0x0815, 0x0a15] #Always confirm this ID with CFE_EVS configuration
      byteOrder: LITTLE_ENDIAN
      appNameMax: 40
      eventMsgMax: 122
  - class: org.yamcs.cfdp.CfdpService
    name: cfdp0
    args:
      inStream: cfdp_in
      outStream: cfdp_out
      localEntities:
        - name: "0.23"
          id: 23
          bucket: cfdpUp
      remoteEntities:
        - name: "0.24"
          id: 24
          bucket: cfdpDown
      receiverFaultHandlers:
        AckLimitReached: suspend

dataLinks:
  - name: tc_ppd
    class: org.yamcs.tctm.UdpTcDataLink
    stream: tc_realtime
    host: 192.168.2.153
    port: 5010
    commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
    commandPostprocessorArgs:
      swapChecksumFc: true

  - name: tm_ppd
    class: org.yamcs.tctm.ccsds.UdpTmFrameLink
    stream: "tm_realtime"
    port: 5011
    stream: tm_realtime
    frameType: TM
    maxFrameLength: 1024
    #packetInputStreamClassName: com.windhoverlabs.yamcs.tctm.ccsds.SdlpPacketInputStream
    packetInputStreamClassName: org.yamcs.tctm.ccsds.SdlpPacketInputStreamasdf
    packetPreprocessorArgs:
      asm: "1ACFFC1D"
      minLength: 1024
      maxLength: 1024
      dropMalformed: false
    frameHeaderErrorControlPresent: false
    insertZoneLength: 0
    spacecraftId: 1
    errorDetection: NONE
    frameLength: 1024
    virtualChannels:
      - vcId: 0
        service: PACKET
        ocfPresent: false
        maxPacketLength: 32768 #32KB is the default for CCSDS
        stream: tm_realtime
        #stripEncapsulationHeader: false
        #packetPreprocessorClassName: com.windhoverlabs.yamcs.tctm.PacketPreprocessor
        packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
        packetPreprocessorArgs:
          byteOrder: LITTLE_ENDIAN
          #errorDetection:
          #tcoService:
          timestampFormat: CFE_SB_TIME_32_16_SUBS
          timeEncoding:
            epoch: CUSTOM
            epochUTC: "1970-01-01T00:00:00Z"
            timeIncludesLeapSeconds: false

  - name: tmtc_cpd
    class: com.windhoverlabs.yamcs.tctm.ccsds.SerialTmTcFrameLink
    device: /dev/ttyUSB0
    tm_config:
      stream: tm_realtime
      frameType: TM
      maxFrameLength: 1024
      packetInputStreamClassName: com.windhoverlabs.yamcs.tctm.ccsds.SdlpPacketInputStream
      packetInputStreamArgs:
        asm: "1ACFFC1D"
        minLength: 1024
        maxLength: 1024
        dropMalformed: false
      frameHeaderErrorControlPresent: false
      insertZoneLength: 0
      spacecraftId: 1
      errorDetection: NONE
      frameLength: 1024
      virtualChannels:
        - vcId: 0
          service: PACKET
          ocfPresent: false
          maxPacketLength: 32768 #32KB is the default for CCSDS
          stream: tm_realtime
          #stripEncapsulationHeader: false
          #packetPreprocessorClassName: com.windhoverlabs.yamcs.tctm.PacketPreprocessor
          packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
          packetPreprocessorArgs:
            byteOrder: LITTLE_ENDIAN
            useLocalGenerationTime: true
            #errorDetection:
            #tcoService:
            timestampFormat: CFE_SB_TIME_32_16_SUBS
            timeEncoding:
              epoch: CUSTOM
              epochUTC: "1970-01-01T00:00:00Z"
              timeIncludesLeapSeconds: false
    tc_config:
      spacecraftId: 1
      maxFrameLength: 1024
      cltuEncoding: "BCH"
      priorityScheme: FIFO
      randomizeCltu: false
      cltuStartSequence: "EB90"
      cltuTailSequence: "C5C5C5C5C5C5C579"
      errorDetection: NONE
      virtualChannels:
        - vcId: 1
          service: PACKET
          priority: 1
          commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
          commandPostprocessorArgs:
            swapChecksumFc: true
          stream: tc_realtime
          useCop1: false
          bdAbsolutePriority: false

mdb:
    # Configuration of the active loaders
    # Valid loaders are: sheet, xtce or fully qualified name of the class
    - type: "xtce"
      spec: "mdb/cfs-ccsds.xml"
      subLoaders:
      - type: "xtce"
        spec: "mdb/PPD.xml"
      - type: "xtce"
        spec: "mdb/CPD.xml"

# Configuration for streams created at server startup
streamConfig:
  tm:
    - name: "tm_realtime"
    - name: "tm_dump"
  cmdHist: ["cmdhist_realtime", "cmdhist_dump"]
  event: ["events_realtime", "events_dump"]
  param: ["pp_realtime", "sys_param", "proc_param"]
  parameterAlarm: ["alarms_realtime"]
  tc: ["tc_realtime"]
  sqlFile: "etc/extra_streams.sql"
