---

config_base: ${PROJECT_SOURCE_DIR}

core:
  osal:
    definition: ${PROJECT_SOURCE_DIR}/core/osal/src/os/posix-nasa/wh_design.yaml
  psp:
    definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/pc-linux-nasa/wh_design.yaml
    
modules:
  sch:
