#Configuration tested on YAMCS 5.4.0
services:
  - class: org.yamcs.http.HttpServer
    args:
      port: 8090
      webSocket:
        maxFrameLength: 262144 # We need this much for rendering SCH tables in Studio.

# This is where Yamcs will persist its data. Paths are resolved relative to where Yamcs is running
# from (by default: target/yamcs). This means that `mvn clean` will remove also persisted data.
# Change this property to an absolute path in case you want to persist your data.
dataDir: yamcs-data

instances:
  - fsw
  - simlink

# Secret key unique to a particular Yamcs installation.
# This is used to provide cryptographic signing.
secretKey: changeme


#The bucket with name of "displays" must ALWAYS be called "displays". The YAMCS Webapp looks for a bucket with ths exact name when loading displays from the filesystem. 
#See yamcs/yamcs-web/src/main/java/org/yamcs/web/WebPlugin.java for details.
buckets:
  - name: cfdpDownCH1
    path: cfdp_downlink_ch1
  - name: cfdpDownCH2
    path: cfdp_downlink_ch2
  - name: cfdpUpCH1
    path: cfdp_uplink_ch1
  - name: cfdpUpCH2
    path: cfdp_uplink_ch2
  - name: displays
    path: Displays
