---

config_base: ${PROJECT_SOURCE_DIR}

core:
  osal:
    definition: ${PROJECT_SOURCE_DIR}/core/osal/src/os/posix-fast/wh_design.yaml
  psp:
    definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/pc-linux-wh/wh_design.yaml
    
modules:
  sch:
    definition: ${PROJECT_SOURCE_DIR}/apps/sch/wh_design.yaml