---
config_base: ${PROJECT_SOURCE_DIR}

core:
  osal:
    definition: ${PROJECT_SOURCE_DIR}/core/osal/src/os/posix-fast/wh_design.yaml
  psp:
    definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/pc-linux-wh/wh_design.yaml
  
modules:
  cf:
    definition: ${PROJECT_SOURCE_DIR}/apps/cf/wh_design.yaml
    
  cs:
    definition: ${PROJECT_SOURCE_DIR}/apps/cs/wh_design.yaml
    
  ds:
    definition: ${PROJECT_SOURCE_DIR}/apps/ds/wh_design.yaml
    
  fm:
    definition: ${PROJECT_SOURCE_DIR}/apps/fm/wh_design.yaml
    
  hk:
    definition: ${PROJECT_SOURCE_DIR}/apps/hk/wh_design.yaml
    
  hs:
    definition: ${PROJECT_SOURCE_DIR}/apps/hs/wh_design.yaml
    
  lc:
    definition: ${PROJECT_SOURCE_DIR}/apps/lc/wh_design.yaml
    
  md:
    definition: ${PROJECT_SOURCE_DIR}/apps/md/wh_design.yaml
    
  mm:
    definition: ${PROJECT_SOURCE_DIR}/apps/mm/wh_design.yaml
    
  sc:
    definition: ${PROJECT_SOURCE_DIR}/apps/sc/wh_design.yaml
    
  ak8963:
    definition: ${PROJECT_SOURCE_DIR}/apps/ak8963/wh_design.yaml
    
  amc:
    definition: ${PROJECT_SOURCE_DIR}/apps/amc/wh_design.yaml
    
  bat:
    definition: ${PROJECT_SOURCE_DIR}/apps/bat/wh_design.yaml
    
  ea:
    definition: ${PROJECT_SOURCE_DIR}/apps/ea/wh_design.yaml
    
  flow:
    definition: ${PROJECT_SOURCE_DIR}/apps/flow/wh_design.yaml
    
  gps:
    definition: ${PROJECT_SOURCE_DIR}/apps/gps/wh_design.yaml
    
  hmc5883:
    definition: ${PROJECT_SOURCE_DIR}/apps/hmc5883/wh_design.yaml
    
  ld:
    definition: ${PROJECT_SOURCE_DIR}/apps/ld/wh_design.yaml
    
  lgc:
    definition: ${PROJECT_SOURCE_DIR}/apps/lgc/wh_design.yaml
    
  mac:
    definition: ${PROJECT_SOURCE_DIR}/apps/mac/wh_design.yaml
    
  mavlink:
    definition: ${PROJECT_SOURCE_DIR}/apps/mavlink/wh_design.yaml
    
  mpc:
    definition: ${PROJECT_SOURCE_DIR}/apps/mpc/wh_design.yaml
    
  mpu6050:
    definition: ${PROJECT_SOURCE_DIR}/apps/mpu6050/wh_design.yaml
    
  mpu9250:
    telemetry:
      MPU9250_HK_TLM_MID:
        msgID: 0x0b51
      MPU9250_DIAG_TLM_MID:
        msgID: 0x0b52
    commands:
      MPU9250_CMD_MID:
        msgID: 0x1b53
      MPU9250_SEND_HK_MID:
        msgID: 0x1b50
      MPU9250_MEASURE_MID:
        msgID: 0x1b54
    perfids:
      MPU9250_MAIN_TASK_PERF_ID:
        id: 83
    definition: ${PROJECT_SOURCE_DIR}/apps/mpu9250/wh_design.yaml
    
  ms5607:
    definition: ${PROJECT_SOURCE_DIR}/apps/ms5607/wh_design.yaml
    
  ms5611:
    definition: ${PROJECT_SOURCE_DIR}/apps/ms5611/wh_design.yaml
    
  nav:
    definition: ${PROJECT_SOURCE_DIR}/apps/nav/wh_design.yaml
    
  prmlib:
    definition: ${PROJECT_SOURCE_DIR}/apps/prmlib/wh_design.yaml
    
  pe:
    definition: ${PROJECT_SOURCE_DIR}/apps/pe/wh_design.yaml
    
  qae:
    definition: ${PROJECT_SOURCE_DIR}/apps/qae/wh_design.yaml
    
  rcin:
    definition: ${PROJECT_SOURCE_DIR}/apps/rcin/wh_design.yaml
    
  rgbled:
    definition: ${PROJECT_SOURCE_DIR}/apps/rgbled/wh_design.yaml
    
  sbn:
    definition: ${PROJECT_SOURCE_DIR}/apps/sbn/wh_design.yaml
    
  sc:
    definition: ${PROJECT_SOURCE_DIR}/apps/sc/wh_design.yaml
    
  sens:
    definition: ${PROJECT_SOURCE_DIR}/apps/sens/wh_design.yaml
    
  sim:
    definition: ${PROJECT_SOURCE_DIR}/apps/sim/wh_design.yaml
    
  sonar:
    definition: ${PROJECT_SOURCE_DIR}/apps/sonar/wh_design.yaml
    
  ulr:
    definition: ${PROJECT_SOURCE_DIR}/apps/ulr/wh_design.yaml
    
  vc:
    definition: ${PROJECT_SOURCE_DIR}/apps/vc/wh_design.yaml
    
  vm:
    definition: ${PROJECT_SOURCE_DIR}/apps/vm/wh_design.yaml
    
  px4lib:
    definition: ${PROJECT_SOURCE_DIR}/apps/px4lib/wh_design.yaml
