#include "ds_msg.h"

DS_NoopCmd_t        DS_NoopCmd;
DS_ResetCmd_t       DS_ResetCmd;
DS_AppStateCmd_t    DS_AppStateCmd;
DS_FilterFileCmd_t  DS_FilterFileCmd;
DS_FilterTypeCmd_t  DS_FilterTypeCmd;
DS_FilterParmsCmd_t DS_FilterParmsCmd;
DS_DestTypeCmd_t    DS_DestTypeCmd;
DS_DestStateCmd_t   DS_DestStateCmd;
DS_DestPathCmd_t    DS_DestPathCmd;
DS_DestBaseCmd_t    DS_DestBaseCmd;
DS_DestExtCmd_t     DS_DestExtCmd;
DS_DestSizeCmd_t    DS_DestSizeCmd;
DS_DestAgeCmd_t     DS_DestAgeCmd;
DS_DestCountCmd_t   DS_DestCountCmd;
DS_CloseFileCmd_t   DS_CloseFileCmd;
DS_CloseAllCmd_t    DS_CloseAllCmd;
DS_GetFileInfoCmd_t DS_GetFileInfoCmd;
DS_AddMidCmd_t      DS_AddMidCmd;
