---
config_base: ${PROJECT_SOURCE_DIR}

core:
  osal:
    definition: ${PROJECT_SOURCE_DIR}/core/osal/src/os/posix-fast/wh_design.yaml
  psp:
    definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/ocpoc-linux/wh_design.yaml
  
modules:    
  amc:
    telemetry:
      AMC_HK_TLM_MID:
        msgID: 0x0c41
    commands:
      AMC_CMD_MID:
        msgID: 0x1c3d
      AMC_SEND_HK_MID:
        msgID: 0x1c3e
      AMC_UPDATE_MOTORS_MID:
        msgID: 0x1c3f
    perfids:
      AMC_MAIN_TASK_PERF_ID:
        id: 67
      AMC_SEND_PERF_ID:
        id: 108
      AMC_RECEIVE_PERF_ID:
        id: 109
    definition: ${PROJECT_SOURCE_DIR}/apps/amc/wh_design.yaml
    
  bat:
    telemetry:
      BAT_HK_TLM_MID:
        msgID: 0x0c71
    commands:
      BAT_CMD_MID:
        msgID: 0x1c74
      BAT_SEND_HK_MID:
        msgID: 0x1c72
      BAT_WAKEUP_MID:
        msgID: 0x1c73
    perfids:
      BAT_MAIN_TASK_PERF_ID:
        id: 82
    definition: ${PROJECT_SOURCE_DIR}/apps/bat/wh_design.yaml
    
  ea:
    telemetry:
      EA_HK_TLM_MID:
        msgID: 0x0c2b
    commands:
      EA_CMD_MID:
        msgID: 0x1c29
      EA_WAKEUP_MID:
        msgID: 0x1c2c
    perfids:
      EA_MAIN_TASK_PERF_ID:
        id: 69
    definition: ${PROJECT_SOURCE_DIR}/apps/ea/wh_design.yaml
    
  flow:
    short_name: flow
    long_name: Optical Flow
    telemetry:
      FLOW_HK_TLM_MID:
        msgID: 0x0ce1
      FLOW_DIAG_TLM_MID:
        msgID: 0x0ce6
    commands:
      FLOW_CMD_MID:
        msgID: 0x1ce4
      FLOW_SEND_HK_MID:
        msgID: 0x1ce2
      FLOW_WAKEUP_MID:
        msgID: 0x1ce3
    perfids:
      FLOW_MAIN_TASK_PERF_ID:
        id: 113
      FLOW_COMPUTE_PERF_ID:
        id: 114
    definition: ${PROJECT_SOURCE_DIR}/apps/flow/wh_design.yaml
    
  gps:
    telemetry:
      GPS_HK_TLM_MID:
        msgID: 0x0c54
    commands:
      GPS_CMD_MID:
        msgID: 0x1c51
      GPS_SEND_HK_MID:
        msgID: 0x1c52
      GPS_READ_SENSOR_MID:
        msgID: 0x1c53
    perfids: 
      GPS_MAIN_TASK_PERF_ID:
        id: 116
    definition: ${PROJECT_SOURCE_DIR}/apps/gps/wh_design.yaml
    
  hmc5883:
    telemetry:
      HMC5883_HK_TLM_MID:
        msgID: 0x0ca1
      HMC5883_DIAG_TLM_MID:
        msgID: 0x0ca5
    commands:
      HMC5883_CMD_MID:
        msgID: 0x1ca4
      HMC5883_WAKEUP_MID:
        msgID: 0x1ca3
      HMC5883_SEND_HK_MID:
        msgID: 0x1ca2
    perfids:
      HMC5883_MAIN_TASK_PERF_ID:
        id: 87
      HMC5883_RECEIVE_PERF_ID:
        id: 88
      HMC5883_SEND_PERF_ID:
        id: 89
    definition: ${PROJECT_SOURCE_DIR}/apps/hmc5883/wh_design.yaml
    
  ld:
    telemetry:
      LD_HK_TLM_MID:
        msgID: 0x0c5d
      LD_DIAG_TLM_MID:
        msgID: 0x0ceb
    commands:
      LD_CMD_MID:
        msgID: 0x1c60
      LD_SEND_HK_MID:
        msgID: 0x1c5e
      LD_WAKEUP_MID:
        msgID: 0x1c5f
    perfids:
      LD_MAIN_TASK_PERF_ID:
        id: 77
    definition: ${PROJECT_SOURCE_DIR}/apps/ld/wh_design.yaml
    
  lgc:
    telemetry:
      LGC_HK_TLM_MID:
        msgID: 0x0cb0
    commands:
      LGC_CMD_MID:
        msgID: 0x1cb3
      LGC_SEND_HK_MID:
        msgID: 0x1cb1
      LGC_WAKEUP_MID:
        msgID: 0x1cb2
    perfids:
      LGC_MAIN_TASK_PERF_ID:
        id: 112
    definition: ${PROJECT_SOURCE_DIR}/apps/lgc/wh_design.yaml
    
  mac:
    telemetry:
      MAC_HK_TLM_MID:
        msgID: 0x0c46
    commands:
      MAC_CMD_MID:
        msgID: 0x1c42
      MAC_SEND_HK_MID:
        msgID: 0x1c43
      MAC_RUN_CONTROLLER_MID:
        msgID: 0x1c44
    perfids:
      MAC_MAIN_TASK_PERF_ID:
        id: 68
    definition: ${PROJECT_SOURCE_DIR}/apps/mac/wh_design.yaml
    
  mpc:
    telemetry:
      MPC_HK_TLM_MID:
        msgID: 0x0c61
      MPC_DIAG_TLM_MID:
        msgID: 0x0cea
    commands:
      MPC_CMD_MID:
        msgID: 0x1c64
      MPC_WAKEUP_MID:
        msgID: 0x1c63
      MPC_SEND_HK_MID:
        msgID: 0x1c62
    perfids:
      MPC_MAIN_TASK_PERF_ID:
        id: 78
    definition: ${PROJECT_SOURCE_DIR}/apps/mpc/wh_design.yaml
    
  mpu9250:
    telemetry:
      MPU9250_HK_TLM_MID:
        msgID: 0x0b51
      MPU9250_DIAG_TLM_MID:
        msgID: 0x0b52
    commands:
      MPU9250_CMD_MID:
        msgID: 0x1b53
      MPU9250_SEND_HK_MID:
        msgID: 0x1b50
      MPU9250_MEASURE_MID:
        msgID: 0x1b54
    perfids:
      MPU9250_MAIN_TASK_PERF_ID:
        id: 83
    definition: ${PROJECT_SOURCE_DIR}/apps/mpu9250/wh_design.yaml
    
  ms5611:
    telemetry:
      MS5611_HK_TLM_MID:
        msgID: 0x0b61
      MS5611_DIAG_TLM_MID:
        msgID: 0x0b62
    commands:
      MS5611_CMD_MID:
        msgID: 0x1b63
      MS5611_SEND_HK_MID:
        msgID: 0x1b60
      MS5611_MEASURE_MID:
        msgID: 0x1b64
    perfids:
      MS5611_MAIN_TASK_PERF_ID:
        id: 74
    definition: ${PROJECT_SOURCE_DIR}/apps/ms5611/wh_design.yaml
    
  nav:
    telemetry:
      NAV_HK_TLM_MID:
        msgID: 0x0c65
    commands:
      NAV_CMD_MID:
        msgID: 0x1c68
      NAV_SEND_HK_MID:
        msgID: 0x1c66
      NAV_WAKEUP_MID:
        msgID: 0x1c67
    perfids:
      NAV_MAIN_TASK_PERF_ID:
        id: 79
    definition: ${PROJECT_SOURCE_DIR}/apps/nav/wh_design.yaml
    
  prmlib:
    telemetry:
      PRMLIB_PARAM_UPDATED_MID:
        msgID: 0x0ca6
    commands:
      PRM_CMD_MID:
        msgID: 0x1ced
      PRM_SEND_HK_MID:
        msgID: 0x1cee
      PRM_WAKEUP_MID:
        msgID: 0x1cef
    perfids:
      PARAMS_MAIN_TASK_PERF_ID:
        id: 90
    definition: ${PROJECT_SOURCE_DIR}/apps/prmlib/wh_design.yaml
    
  pe:
    telemetry:
      PE_HK_TLM_MID:
        msgID: 0x0c79
    commands:
      PE_CMD_MID:
        msgID: 0x1c7c
      PE_SEND_HK_MID:
        msgID: 0x1c7a
      PE_WAKEUP_MID:
        msgID: 0x1c7b
    perfids:
      PE_MAIN_TASK_PERF_ID:
        id: 92
      PE_UPDATE_TASK_PERF_ID:
        id: 93
      PE_SENSOR_GPS_PERF_ID:
        id: 94
      PE_SENSOR_BARO_PERF_ID:
        id: 95
      PE_SENSOR_LAND_PERF_ID:
        id: 96
      PE_INVERSE_MAT_PERF_ID:
        id: 97
      PE_SENSOR_FLOW_PERF_ID:
        id: 98
      PE_SENSOR_DIST_PERF_ID:
        id: 110
    definition: ${PROJECT_SOURCE_DIR}/apps/pe/wh_design.yaml
    
  qae:
    telemetry:
      QAE_HK_TLM_MID:
        msgID: 0x0c59
    commands:
      QAE_CMD_MID:
        msgID: 0x1c5c
      QAE_SEND_HK_MID:
        msgID: 0x1c5a
      QAE_WAKEUP_MID:
        msgID: 0x1c5b
    perfids:
      QAE_MAIN_TASK_PERF_ID:
        id: 76
      AE_MAIN_TASK_PERF_ID:
        id: 91
    definition: ${PROJECT_SOURCE_DIR}/apps/qae/wh_design.yaml
    
  rcin:
    telemetry:
      RCIN_HK_TLM_MID:
        msgID: 0x0c69
    commands:
      RCIN_CMD_MID:
        msgID: 0x1c6c
      RCIN_SEND_HK_MID:
        msgID: 0x1c6a
      RCIN_WAKEUP_MID:
        msgID: 0x1c6b
    perfids:
      RCIN_MAIN_TASK_PERF_ID:
        id: 80
      RCIN_DEVICE_GET_PERF_ID:
        id: 84
    definition: ${PROJECT_SOURCE_DIR}/apps/rcin/wh_design.yaml
    
  rgbled:
    telemetry:
      RGBLED_HK_TLM_MID:
        msgID: 0x0c4f
    commands:
      RGBLED_CMD_MID:
        msgID: 0x1c4c
      RGBLED_SEND_HK_MID:
        msgID: 0x1c4d
      RGBLED_WAKEUP_MID:
        msgID: 0x1c4e
    perfids:
      RGBLED_MAIN_TASK_PERF_ID:
        id: 71
      RGBLED_SEND_PERF_ID:
        id: 72
      RGBLED_RECEIVE_PERF_ID:
        id: 73
    definition: ${PROJECT_SOURCE_DIR}/apps/rgbled/wh_design.yaml
    
  sens:
    telemetry:
      SENS_HK_TLM_MID:
        msgID: 0x0c55
    commands:
      SENS_CMD_MID:
        msgID: 0x1c58
      SENS_WAKEUP_MID:
        msgID: 0x1c57
      SENS_SEND_HK_MID:
        msgID: 0x1c56
    perfids:
      SENS_MAIN_TASK_PERF_ID:
        id: 75
    definition: ${PROJECT_SOURCE_DIR}/apps/sens/wh_design.yaml
    
  ulr:
    telemetry:
      ULR_HK_TLM_MID:
        msgID: 0x0c4b
    commands:
      ULR_CMD_MID:
        msgID: 0x1c47
      ULR_SEND_HK_MID:
        msgID: 0x1c48
      ULR_MEASURE_MID:
        msgID: 0x1c49
    perfids:
      ULR_MAIN_TASK_PERF_ID:
        id: 70
    definition: ${PROJECT_SOURCE_DIR}/apps/ulr/wh_design.yaml
    
  vc:
    telemetry:
      VC_HK_TLM_MID:
        msgID: 0x0c39
    commands:
      VC_CMD_MID:
        msgID: 0x1c3b
      VC_SEND_HK_MID:
        msgID: 0x1c3a
      VC_PROCESS_CMDS_MID:
        msgID: 0x1c3c
    perfids:
      VC_MAIN_TASK_PERF_ID:
        id: 63
      VC_SOCKET_SEND_PERF_ID:
        id: 64
      VC_DEVICE_GET_PERF_ID:
        id: 65
    definition: ${PROJECT_SOURCE_DIR}/apps/vc/wh_design.yaml
    
  vm:
    telemetry:
      VM_HK_TLM_MID:
        msgID: 0x0c6d
      VM_CONFIG_TLM_MID:
        msgID: 0x0cec
    commands:
      VM_CMD_MID:
        msgID: 0x1c70
      VM_SEND_HK_MID:
        msgID: 0x1c6e
      VM_WAKEUP_MID:
        msgID: 0x1c6f
    perfids:
      VM_MAIN_TASK_PERF_ID:
        id: 81
    definition: ${PROJECT_SOURCE_DIR}/apps/vm/wh_design.yaml
    
  px4lib:
    telemetry:
      PX4_ACTUATOR_ARMED_MID:
        msgID: 0x0a05
      PX4_ACTUATOR_CONTROLS_0_MID:
        msgID: 0x0a06
      PX4_ACTUATOR_CONTROLS_1_MID:
        msgID: 0x0a5f
      PX4_ACTUATOR_CONTROLS_2_MID:
        msgID: 0x0a5d
      PX4_ACTUATOR_CONTROLS_3_MID:
        msgID: 0x0a5e
      PX4_ACTUATOR_DIRECT_MID:
        msgID: 0x0a07
      PX4_ACTUATOR_OUTPUTS_MID:
        msgID: 0x0a08
      PX4_ADC_REPORT_MID:
        msgID: 0x0a09
      PX4_AIRSPEED_MID:
        msgID: 0x0a0a
      PX4_ATT_POS_MOCAP_MID:
        msgID: 0x0a0b
      PX4_BATTERY_STATUS_MID:
        msgID: 0x0a0c
      PX4_CAMERA_TRIGGER_MID:
        msgID: 0x0a0d
      PX4_COMMANDER_STATE_MID:
        msgID: 0x0a0e
      PX4_CONTROL_STATE_MID:
        msgID: 0x0a0f
      PX4_CPULOAD_MID:
        msgID: 0x0a10
      PX4_DEBUG_KEY_VALUE_MID:
        msgID: 0x0a11
      PX4_DIFFERENTIAL_PRESSURE_MID:
        msgID: 0x0a12
      PX4_DISTANCE_SENSOR_MID:
        msgID: 0x0a13
      PX4_FW_POS_CTRL_STATUS_MID:
        msgID: 0x0a14
      PX4_FW_VIRTUAL_ATTITUDE_SETPOINT_MID:
        msgID: 0x0a15
      PX4_FW_VIRTUAL_RATES_SETPOINT_MID:
        msgID: 0x0a16
      PX4_EKF2_INNOVATIONS_MID:
        msgID: 0x0a17
      PX4_EKF2_REPLAY_MID:
        msgID: 0x0a18
      PX4_ESC_REPORT_MID:
        msgID: 0x0a19
      PX4_ESC_STATUS_MID:
        msgID: 0x0a1a
      PX4_ESTIMATOR_STATUS_MID:
        msgID: 0x0a1b
      PX4_FENCE_MID:
        msgID: 0x0a1c
      PX4_FENCE_VERTEX_MID:
        msgID: 0x0a1d
      PX4_FILTERED_BOTTOM_FLOW_MID:
        msgID: 0x0a1e
      PX4_FOLLOW_TARGET_MID:
        msgID: 0x0a1f
      PX4_GEOFENCE_RESULT_MID:
        msgID: 0x0a20
      PX4_GPS_DUMP_MID:
        msgID: 0x0a21
      PX4_GPS_INJECT_DATA_MID:
        msgID: 0x0a22
      PX4_HIL_SENSOR_MID:
        msgID: 0x0a23
      PX4_HOME_POSITION_MID:
        msgID: 0x0a24
      PX4_INPUT_RC_MID:
        msgID: 0x0a25
      PX4_LED_CONTROL_MID:
        msgID: 0x0a5c
      PX4_LOG_MESSAGE_MID:
        msgID: 0x0a26
      PX4_MANUAL_CONTROL_SETPOINT_MID:
        msgID: 0x0a27
      PX4_MAVLINK_LOG_MID:
        msgID: 0x0a28
      PX4_MC_ATT_CTRL_STATUS_MID:
        msgID: 0x0a29
      PX4_MC_VIRTUAL_ATTITUDE_SETPOINT_MID:
        msgID: 0x0a2a
      PX4_MC_VIRTUAL_RATES_SETPOINT_MID:
        msgID: 0x0a2b
      PX4_MISSION_MID:
        msgID: 0x0a2c
      PX4_MISSION_RESULT_MID:
        msgID: 0x0a2d
      PX4_MULTIROTOR_MOTOR_LIMITS_MID:
        msgID: 0x0a2e
      PX4_OFFBOARD_CONTROL_MODE_MID:
        msgID: 0x0a2f
      PX4_OPTICAL_FLOW_MID:
        msgID: 0x0a30
      PX4_OUTPUT_PWM_MID:
        msgID: 0x0a31
      PX4_PARAMETER_UPDATE_MID:
        msgID: 0x0a32
      PX4_POSITION_SETPOINT_MID:
        msgID: 0x0a33
      PX4_POSITION_SETPOINT_TRIPLET_MID:
        msgID: 0x0a34
      PX4_PWM_INPUT_MID:
        msgID: 0x0a35
      PX4_QSHELL_REQ_MID:
        msgID: 0x0a36
      PX4_RC_CHANNELS_MID:
        msgID: 0x0a37
      PX4_RC_PARAMETER_MAP_MID:
        msgID: 0x0a38
      PX4_SAFETY_MID:
        msgID: 0x0a39
      PX4_SATELLITE_INFO_MID:
        msgID: 0x0a3a
      PX4_SENSOR_ACCEL_MID:
        msgID: 0x0a3b
      PX4_SENSOR_BARO_MID:
        msgID: 0x0a3c
      PX4_SENSOR_COMBINED_MID:
        msgID: 0x0a3d
      PX4_SENSOR_GYRO_MID:
        msgID: 0x0a3e
      PX4_SENSOR_MAG_MID:
        msgID: 0x0a3f
      PX4_SERVORAIL_STATUS_MID:
        msgID: 0x0a40
      PX4_SUBSYSTEM_INFO_MID:
        msgID: 0x0a41
      PX4_SYSTEM_POWER_MID:
        msgID: 0x0a42
      PX4_TECS_STATUS_MID:
        msgID: 0x0a43
      PX4_TELEMETRY_STATUS_MID:
        msgID: 0x0a44
      PX4_TEST_MOTOR_MID:
        msgID: 0x0a45
      PX4_TIME_OFFSET_MID:
        msgID: 0x0a46
      PX4_TRANSPONDER_REPORT_MID:
        msgID: 0x0a47
      PX4_UAVCAN_PARAMETER_REQUEST_MID:
        msgID: 0x0a48
      PX4_UAVCAN_PARAMETER_VALUE_MID:
        msgID: 0x0a49
      PX4_VEHICLE_ATTITUDE_MID:
        msgID: 0x0a4a
      PX4_VEHICLE_ATTITUDE_SETPOINT_MID:
        msgID: 0x0a4b
      PX4_VEHICLE_COMMAND_ACK_MID:
        msgID: 0x0a4c
      PX4_VEHICLE_COMMAND_MID:
        msgID: 0x0a4d
      PX4_VEHICLE_CONTROL_MODE_MID:
        msgID: 0x0a4e
      PX4_VEHICLE_FORCE_SETPOINT_MID:
        msgID: 0x0a4f
      PX4_VEHICLE_GLOBAL_POSITION_MID:
        msgID: 0x0a50
      PX4_VEHICLE_GLOBAL_VELOCITY_SETPOINT_MID:
        msgID: 0x0a51
      PX4_VEHICLE_GPS_POSITION_MID:
        msgID: 0x0a52
      PX4_VEHICLE_LAND_DETECTED_MID:
        msgID: 0x0a53
      PX4_VEHICLE_LOCAL_POSITION_MID:
        msgID: 0x0a54
      PX4_VEHICLE_LOCAL_POSITION_SETPOINT_MID:
        msgID: 0x0a55
      PX4_VEHICLE_RATES_SETPOINT_MID:
        msgID: 0x0a56
      PX4_VEHICLE_STATUS_MID:
        msgID: 0x0a57
      PX4_VISION_POSITION_ESTIMATE_MID:
        msgID: 0x0a58
      PX4_VTOL_VEHICLE_STATUS_MID:
        msgID: 0x0a59
      PX4_WIND_ESTIMATE_MID:
        msgID: 0x0a5a
      PX4_SENSOR_CORRECTION_MID:
        msgID: 0x0a5b
      FLOW_FRAME_MID:
        msgID: 0x0ce5
    definition: ${PROJECT_SOURCE_DIR}/apps/px4lib/wh_design.yaml
