#include "cf_msg.h"

CF_NoArgsCmd_t            CF_NoArgsCmd_s;
CF_ResetCtrsCmd_t         CF_ResetCtrsCmd_s;
CF_PlaybackFileCmd_t      CF_PlaybackFileCmd_s;
CF_PlaybackDirCmd_t       CF_PlaybackDirCmd_s;
CF_CARSCmd_t              CF_CARSCmd_s;
CF_SetMibParam_t          CF_SetMibParam_s;
CF_GetMibParam_t          CF_GetMibParam_s;
CF_SendTransCmd_t         CF_SendTransCmd_s;
CF_SetPollParamCmd_t      CF_SetPollParamCmd_s;
CF_WriteQueueCmd_t        CF_WriteQueueCmd_s;
CF_EnDisDequeueCmd_t      CF_EnDisDequeueCmd_s;
CF_EnDisPollCmd_t         CF_EnDisPollCmd_s;
CF_DequeueNodeCmd_t       CF_DequeueNodeCmd_s;
CF_PurgeQueueCmd_t        CF_PurgeQueueCmd_s;
CF_WriteActiveTransCmd_t  CF_WriteActiveTransCmd_s;
CF_KickstartCmd_t         CF_KickstartCmd_s;
CF_QuickStatCmd_t         CF_QuickStatCmd_s;
CF_GiveTakeCmd_t          CF_GiveTakeCmd_s;
CF_AutoSuspendEnCmd_t     CF_AutoSuspendEnCmd_s;
CF_CyclesPerWakeupCmd_t   CF_CyclesPerWakeupCmd_s;
