uri:
  http://localhost:8090/api/archive/
instance:
  yamcs-cfs
method:
  exportParameterValues
param_array:
  - /cfs/cpd/apps/aspd4525/ASPD4525_HK_TLM_MID.uPressureCount
  - /cfs/cpd/apps/aspd4525/ASPD4525_HK_TLM_MID.fTrueAirSpeed
  - /cfs/cpd/apps/px4lib/PX4_VEHICLE_GLOBAL_POSITION_MID.Lat
  - /cfs/cpd/apps/px4lib/PX4_VEHICLE_GLOBAL_POSITION_MID.Lon
  - /cfs/cpd/apps/px4lib/PX4_VEHICLE_GLOBAL_POSITION_MID.Alt
  - /cfs/cpd/apps/px4lib/PX4_MANUAL_CONTROL_SETPOINT_MID.X
  - /cfs/cpd/apps/px4lib/PX4_MANUAL_CONTROL_SETPOINT_MID.Y
  - /cfs/cpd/apps/px4lib/PX4_MANUAL_CONTROL_SETPOINT_MID.Z
  - /cfs/cpd/apps/px4lib/PX4_MANUAL_CONTROL_SETPOINT_MID.R
  - /cfs/cpd/apps/px4lib/PX4_VEHICLE_GLOBAL_POSITION_MID.VelN
  - /cfs/cpd/apps/px4lib/PX4_VEHICLE_GLOBAL_POSITION_MID.VelE
  - /cfs/cpd/apps/px4lib/PX4_VEHICLE_GLOBAL_POSITION_MID.VelD
start:
  #'1970-01-12T14:12:11.25Z'
  '1970-01-12T14:04:11.25Z' #Date Format needs to be in RFC 3339 format of Packet time in yamcs
stop:
  #'1970-01-12T14:13:11.25Z'
  '1970-01-12T14:40:00.000Z' #Date Format needs to be in RFC 3339 format of Packet time in yamcs
output_csv_file:
  param_log.csv
yamcs_csv_file:
  yamcs_param_log.csv