/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:06 2016. */

#ifndef PB_ACTUATOR_DIRECT_PB_H_INCLUDED
#define PB_ACTUATOR_DIRECT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_actuator_direct_pb_ACTUATOR_DIRECT {
    px4_actuator_direct_pb_ACTUATOR_DIRECT_ACTUATOR_DIRECT_NUM_ACTUATORS_DIRECT = 16
} px4_actuator_direct_pb_ACTUATOR_DIRECT;
#define _px4_actuator_direct_pb_ACTUATOR_DIRECT_MIN px4_actuator_direct_pb_ACTUATOR_DIRECT_ACTUATOR_DIRECT_NUM_ACTUATORS_DIRECT
#define _px4_actuator_direct_pb_ACTUATOR_DIRECT_MAX px4_actuator_direct_pb_ACTUATOR_DIRECT_ACTUATOR_DIRECT_NUM_ACTUATORS_DIRECT
#define _px4_actuator_direct_pb_ACTUATOR_DIRECT_ARRAYSIZE ((px4_actuator_direct_pb_ACTUATOR_DIRECT)(px4_actuator_direct_pb_ACTUATOR_DIRECT_ACTUATOR_DIRECT_NUM_ACTUATORS_DIRECT+1))

/* Struct definitions */
typedef struct _px4_actuator_direct_pb {
    uint64_t timestamp;
    uint32_t nvalues;
    pb_size_t values_count;
    float values[16];
/* @@protoc_insertion_point(struct:px4_actuator_direct_pb) */
} px4_actuator_direct_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_actuator_direct_pb_init_default      {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define px4_actuator_direct_pb_init_zero         {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define px4_actuator_direct_pb_timestamp_tag     1
#define px4_actuator_direct_pb_nvalues_tag       2
#define px4_actuator_direct_pb_values_tag        3

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_actuator_direct_pb_fields[4];

/* Maximum encoded size of messages (where known) */
#define px4_actuator_direct_pb_size              97

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ACTUATOR_DIRECT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
