/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:07 2016. */

#include "att_pos_mocap.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_att_pos_mocap_pb_fields[8] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_att_pos_mocap_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_att_pos_mocap_pb, timestamp_received, timestamp, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, px4_att_pos_mocap_pb, id, timestamp_received, 0),
    PB_FIELD(  4, FLOAT   , REPEATED, STATIC  , OTHER, px4_att_pos_mocap_pb, q, id, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_att_pos_mocap_pb, x, q, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_att_pos_mocap_pb, y, x, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_att_pos_mocap_pb, z, y, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
