/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:07 2016. */

#ifndef PB_ATT_POS_MOCAP_PB_H_INCLUDED
#define PB_ATT_POS_MOCAP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_att_pos_mocap_pb {
    uint64_t timestamp;
    uint64_t timestamp_received;
    uint32_t id;
    pb_size_t q_count;
    float q[4];
    float x;
    float y;
    float z;
/* @@protoc_insertion_point(struct:px4_att_pos_mocap_pb) */
} px4_att_pos_mocap_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_att_pos_mocap_pb_init_default        {0, 0, 0, 0, {0, 0, 0, 0}, 0, 0, 0}
#define px4_att_pos_mocap_pb_init_zero           {0, 0, 0, 0, {0, 0, 0, 0}, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_att_pos_mocap_pb_timestamp_tag       1
#define px4_att_pos_mocap_pb_timestamp_received_tag 2
#define px4_att_pos_mocap_pb_id_tag              3
#define px4_att_pos_mocap_pb_q_tag               4
#define px4_att_pos_mocap_pb_x_tag               5
#define px4_att_pos_mocap_pb_y_tag               6
#define px4_att_pos_mocap_pb_z_tag               7

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_att_pos_mocap_pb_fields[8];

/* Maximum encoded size of messages (where known) */
#define px4_att_pos_mocap_pb_size                63

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ATT_POS_MOCAP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
