/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:07 2016. */

#include "battery_status.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_battery_status_pb_fields[11] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_battery_status_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, voltage_v, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, voltage_filtered_v, voltage_v, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, current_a, voltage_filtered_v, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, current_filtered_a, current_a, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, discharged_mah, current_filtered_a, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, remaining, discharged_mah, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, cell_count, remaining, 0),
    PB_FIELD(  9, BOOL    , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, connected, cell_count, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, px4_battery_status_pb, warning, connected, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
