/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:07 2016. */

#ifndef PB_BATTERY_STATUS_PB_H_INCLUDED
#define PB_BATTERY_STATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_battery_status_pb_BATTERY_WARNING {
    px4_battery_status_pb_BATTERY_WARNING_BATTERY_WARNING_NONE = 0,
    px4_battery_status_pb_BATTERY_WARNING_BATTERY_WARNING_LOW = 1,
    px4_battery_status_pb_BATTERY_WARNING_BATTERY_WARNING_CRITICAL = 2
} px4_battery_status_pb_BATTERY_WARNING;
#define _px4_battery_status_pb_BATTERY_WARNING_MIN px4_battery_status_pb_BATTERY_WARNING_BATTERY_WARNING_NONE
#define _px4_battery_status_pb_BATTERY_WARNING_MAX px4_battery_status_pb_BATTERY_WARNING_BATTERY_WARNING_CRITICAL
#define _px4_battery_status_pb_BATTERY_WARNING_ARRAYSIZE ((px4_battery_status_pb_BATTERY_WARNING)(px4_battery_status_pb_BATTERY_WARNING_BATTERY_WARNING_CRITICAL+1))

/* Struct definitions */
typedef struct _px4_battery_status_pb {
    uint64_t timestamp;
    float voltage_v;
    float voltage_filtered_v;
    float current_a;
    float current_filtered_a;
    float discharged_mah;
    float remaining;
    int32_t cell_count;
    bool connected;
    uint32_t warning;
/* @@protoc_insertion_point(struct:px4_battery_status_pb) */
} px4_battery_status_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_battery_status_pb_init_default       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define px4_battery_status_pb_init_zero          {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_battery_status_pb_timestamp_tag      1
#define px4_battery_status_pb_voltage_v_tag      2
#define px4_battery_status_pb_voltage_filtered_v_tag 3
#define px4_battery_status_pb_current_a_tag      4
#define px4_battery_status_pb_current_filtered_a_tag 5
#define px4_battery_status_pb_discharged_mah_tag 6
#define px4_battery_status_pb_remaining_tag      7
#define px4_battery_status_pb_cell_count_tag     8
#define px4_battery_status_pb_connected_tag      9
#define px4_battery_status_pb_warning_tag        10

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_battery_status_pb_fields[11];

/* Maximum encoded size of messages (where known) */
#define px4_battery_status_pb_size               60

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BATTERY_STATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
