/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:10 2016. */

#include "ekf2_replay.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_ekf2_replay_pb_fields[41] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_ekf2_replay_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, time_ref, timestamp, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, magnetometer_timestamp, time_ref, 0),
    PB_FIELD(  4, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, baro_timestamp, magnetometer_timestamp, 0),
    PB_FIELD(  5, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, rng_timestamp, baro_timestamp, 0),
    PB_FIELD(  6, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, flow_timestamp, rng_timestamp, 0),
    PB_FIELD(  7, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, asp_timestamp, flow_timestamp, 0),
    PB_FIELD(  8, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, ev_timestamp, asp_timestamp, 0),
    PB_FIELD(  9, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, time_usec, ev_timestamp, 0),
    PB_FIELD( 10, UINT64  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, time_usec_vel, time_usec, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, gyro_integral_dt, time_usec_vel, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, accelerometer_integral_dt, gyro_integral_dt, 0),
    PB_FIELD( 13, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, gyro_rad, accelerometer_integral_dt, 0),
    PB_FIELD( 14, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, accelerometer_m_s2, gyro_rad, 0),
    PB_FIELD( 15, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, magnetometer_ga, accelerometer_m_s2, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, baro_alt_meter, magnetometer_ga, 0),
    PB_FIELD( 17, INT32   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, lat, baro_alt_meter, 0),
    PB_FIELD( 18, INT32   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, lon, lat, 0),
    PB_FIELD( 19, INT32   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, alt, lon, 0),
    PB_FIELD( 20, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, eph, alt, 0),
    PB_FIELD( 21, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, epv, eph, 0),
    PB_FIELD( 22, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, sacc, epv, 0),
    PB_FIELD( 23, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, vel_m_s, sacc, 0),
    PB_FIELD( 24, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, vel_n_m_s, vel_m_s, 0),
    PB_FIELD( 25, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, vel_e_m_s, vel_n_m_s, 0),
    PB_FIELD( 26, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, vel_d_m_s, vel_e_m_s, 0),
    PB_FIELD( 27, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, range_to_ground, vel_d_m_s, 0),
    PB_FIELD( 28, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, flow_pixel_integral, range_to_ground, 0),
    PB_FIELD( 29, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, flow_gyro_integral, flow_pixel_integral, 0),
    PB_FIELD( 30, UINT32  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, flow_time_integral, flow_gyro_integral, 0),
    PB_FIELD( 31, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, indicated_airspeed_m_s, flow_time_integral, 0),
    PB_FIELD( 32, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, true_airspeed_m_s, indicated_airspeed_m_s, 0),
    PB_FIELD( 33, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, pos_ev, true_airspeed_m_s, 0),
    PB_FIELD( 34, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_replay_pb, quat_ev, pos_ev, 0),
    PB_FIELD( 35, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, pos_err, quat_ev, 0),
    PB_FIELD( 36, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, ang_err, pos_err, 0),
    PB_FIELD( 37, UINT32  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, fix_type, ang_err, 0),
    PB_FIELD( 38, UINT32  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, nsats, fix_type, 0),
    PB_FIELD( 39, BOOL    , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, vel_ned_valid, nsats, 0),
    PB_FIELD( 40, UINT32  , REQUIRED, STATIC  , OTHER, px4_ekf2_replay_pb, flow_quality, vel_ned_valid, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
