/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:10 2016. */

#ifndef PB_ESTIMATOR_STATUS_PB_H_INCLUDED
#define PB_ESTIMATOR_STATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_estimator_status_pb {
    uint64_t timestamp;
    pb_size_t states_count;
    float states[32];
    float n_states;
    pb_size_t vibe_count;
    float vibe[3];
    pb_size_t covariances_count;
    float covariances[28];
    uint32_t gps_check_fail_flags;
    uint32_t control_mode_flags;
    uint32_t filter_fault_flags;
    uint32_t nan_flags;
    uint32_t health_flags;
    uint32_t timeout_flags;
/* @@protoc_insertion_point(struct:px4_estimator_status_pb) */
} px4_estimator_status_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_estimator_status_pb_init_default     {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, {0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0}
#define px4_estimator_status_pb_init_zero        {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, {0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_estimator_status_pb_timestamp_tag    1
#define px4_estimator_status_pb_states_tag       2
#define px4_estimator_status_pb_n_states_tag     3
#define px4_estimator_status_pb_vibe_tag         4
#define px4_estimator_status_pb_covariances_tag  5
#define px4_estimator_status_pb_gps_check_fail_flags_tag 6
#define px4_estimator_status_pb_control_mode_flags_tag 7
#define px4_estimator_status_pb_filter_fault_flags_tag 8
#define px4_estimator_status_pb_nan_flags_tag    9
#define px4_estimator_status_pb_health_flags_tag 10
#define px4_estimator_status_pb_timeout_flags_tag 11

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_estimator_status_pb_fields[12];

/* Maximum encoded size of messages (where known) */
#define px4_estimator_status_pb_size             367

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ESTIMATOR_STATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
