/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:11 2016. */

#include "fw_pos_ctrl_status.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_fw_pos_ctrl_status_pb_fields[13] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_fw_pos_ctrl_status_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, nav_roll, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, nav_pitch, nav_roll, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, nav_bearing, nav_pitch, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, target_bearing, nav_bearing, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, wp_dist, target_bearing, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, xtrack_error, wp_dist, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, turn_distance, xtrack_error, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, landing_horizontal_slope_displacement, turn_distance, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, landing_slope_angle_rad, landing_horizontal_slope_displacement, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, landing_flare_length, landing_slope_angle_rad, 0),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, px4_fw_pos_ctrl_status_pb, abort_landing, landing_flare_length, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
