/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:11 2016. */

#ifndef PB_FW_POS_CTRL_STATUS_PB_H_INCLUDED
#define PB_FW_POS_CTRL_STATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_fw_pos_ctrl_status_pb {
    uint64_t timestamp;
    float nav_roll;
    float nav_pitch;
    float nav_bearing;
    float target_bearing;
    float wp_dist;
    float xtrack_error;
    float turn_distance;
    float landing_horizontal_slope_displacement;
    float landing_slope_angle_rad;
    float landing_flare_length;
    bool abort_landing;
/* @@protoc_insertion_point(struct:px4_fw_pos_ctrl_status_pb) */
} px4_fw_pos_ctrl_status_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_fw_pos_ctrl_status_pb_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define px4_fw_pos_ctrl_status_pb_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_fw_pos_ctrl_status_pb_timestamp_tag  1
#define px4_fw_pos_ctrl_status_pb_nav_roll_tag   2
#define px4_fw_pos_ctrl_status_pb_nav_pitch_tag  3
#define px4_fw_pos_ctrl_status_pb_nav_bearing_tag 4
#define px4_fw_pos_ctrl_status_pb_target_bearing_tag 5
#define px4_fw_pos_ctrl_status_pb_wp_dist_tag    6
#define px4_fw_pos_ctrl_status_pb_xtrack_error_tag 7
#define px4_fw_pos_ctrl_status_pb_turn_distance_tag 8
#define px4_fw_pos_ctrl_status_pb_landing_horizontal_slope_displacement_tag 9
#define px4_fw_pos_ctrl_status_pb_landing_slope_angle_rad_tag 10
#define px4_fw_pos_ctrl_status_pb_landing_flare_length_tag 11
#define px4_fw_pos_ctrl_status_pb_abort_landing_tag 12

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_fw_pos_ctrl_status_pb_fields[13];

/* Maximum encoded size of messages (where known) */
#define px4_fw_pos_ctrl_status_pb_size           63

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FW_POS_CTRL_STATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
