/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:12 2016. */

#include "fw_virtual_rates_setpoint.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_fw_virtual_rates_setpoint_pb_fields[6] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_fw_virtual_rates_setpoint_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_virtual_rates_setpoint_pb, roll, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_virtual_rates_setpoint_pb, pitch, roll, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_virtual_rates_setpoint_pb, yaw, pitch, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_fw_virtual_rates_setpoint_pb, thrust, yaw, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
