/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:12 2016. */

#ifndef PB_GPS_INJECT_DATA_PB_H_INCLUDED
#define PB_GPS_INJECT_DATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_gps_inject_data_pb {
    uint64_t timestamp;
    uint32_t len;
    uint32_t flags;
    char data[182];
/* @@protoc_insertion_point(struct:px4_gps_inject_data_pb) */
} px4_gps_inject_data_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_gps_inject_data_pb_init_default      {0, 0, 0, ""}
#define px4_gps_inject_data_pb_init_zero         {0, 0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define px4_gps_inject_data_pb_timestamp_tag     1
#define px4_gps_inject_data_pb_len_tag           2
#define px4_gps_inject_data_pb_flags_tag         3
#define px4_gps_inject_data_pb_data_tag          4

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_gps_inject_data_pb_fields[5];

/* Maximum encoded size of messages (where known) */
#define px4_gps_inject_data_pb_size              208

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define GPS_INJECT_DATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
