/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:13 2016. */

#include "input_rc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_input_rc_pb_fields[13] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_input_rc_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, timestamp_publication, timestamp, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, timestamp_last_signal, timestamp_publication, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, channel_count, timestamp_last_signal, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, rssi, channel_count, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, rc_lost_frame_count, rssi, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, rc_total_frame_count, rc_lost_frame_count, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, rc_ppm_frame_length, rc_total_frame_count, 0),
    PB_FIELD(  9, UINT32  , REPEATED, STATIC  , OTHER, px4_input_rc_pb, values, rc_ppm_frame_length, 0),
    PB_FIELD( 10, BOOL    , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, rc_failsafe, values, 0),
    PB_FIELD( 11, BOOL    , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, rc_lost, rc_failsafe, 0),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, px4_input_rc_pb, input_source, rc_lost, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
