/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:13 2016. */

#include "manual_control_setpoint.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_manual_control_setpoint_pb_fields[22] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_manual_control_setpoint_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, x, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, y, x, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, z, y, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, r, z, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, flaps, r, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, aux1, flaps, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, aux2, aux1, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, aux3, aux2, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, aux4, aux3, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, aux5, aux4, 0),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, mode_switch, aux5, 0),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, return_switch, mode_switch, 0),
    PB_FIELD( 14, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, rattitude_switch, return_switch, 0),
    PB_FIELD( 15, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, posctl_switch, rattitude_switch, 0),
    PB_FIELD( 16, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, loiter_switch, posctl_switch, 0),
    PB_FIELD( 17, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, acro_switch, loiter_switch, 0),
    PB_FIELD( 18, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, offboard_switch, acro_switch, 0),
    PB_FIELD( 19, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, kill_switch, offboard_switch, 0),
    PB_FIELD( 20, UINT32  , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, transition_switch, kill_switch, 0),
    PB_FIELD( 21, INT32   , REQUIRED, STATIC  , OTHER, px4_manual_control_setpoint_pb, mode_slot, transition_switch, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
