/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:13 2016. */

#ifndef PB_MC_ATT_CTRL_STATUS_PB_H_INCLUDED
#define PB_MC_ATT_CTRL_STATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_mc_att_ctrl_status_pb {
    uint64_t timestamp;
    float roll_rate_integ;
    float pitch_rate_integ;
    float yaw_rate_integ;
/* @@protoc_insertion_point(struct:px4_mc_att_ctrl_status_pb) */
} px4_mc_att_ctrl_status_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_mc_att_ctrl_status_pb_init_default   {0, 0, 0, 0}
#define px4_mc_att_ctrl_status_pb_init_zero      {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_mc_att_ctrl_status_pb_timestamp_tag  1
#define px4_mc_att_ctrl_status_pb_roll_rate_integ_tag 2
#define px4_mc_att_ctrl_status_pb_pitch_rate_integ_tag 3
#define px4_mc_att_ctrl_status_pb_yaw_rate_integ_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_mc_att_ctrl_status_pb_fields[5];

/* Maximum encoded size of messages (where known) */
#define px4_mc_att_ctrl_status_pb_size           26

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MC_ATT_CTRL_STATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
