/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:14 2016. */

#include "mission.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_mission_pb_fields[5] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_mission_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, px4_mission_pb, dataman_id, timestamp, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, px4_mission_pb, count, dataman_id, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, px4_mission_pb, current_seq, count, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
