/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:15 2016. */

#ifndef PB_OUTPUT_PWM_PB_H_INCLUDED
#define PB_OUTPUT_PWM_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_output_pwm_pb_OUTPUT_PWM {
    px4_output_pwm_pb_OUTPUT_PWM_PWM_OUTPUT_MAX_CHANNELS = 16
} px4_output_pwm_pb_OUTPUT_PWM;
#define _px4_output_pwm_pb_OUTPUT_PWM_MIN px4_output_pwm_pb_OUTPUT_PWM_PWM_OUTPUT_MAX_CHANNELS
#define _px4_output_pwm_pb_OUTPUT_PWM_MAX px4_output_pwm_pb_OUTPUT_PWM_PWM_OUTPUT_MAX_CHANNELS
#define _px4_output_pwm_pb_OUTPUT_PWM_ARRAYSIZE ((px4_output_pwm_pb_OUTPUT_PWM)(px4_output_pwm_pb_OUTPUT_PWM_PWM_OUTPUT_MAX_CHANNELS+1))

/* Struct definitions */
typedef struct _px4_output_pwm_pb {
    uint64_t timestamp;
    uint32_t channel_count;
    pb_size_t values_count;
    uint32_t values[16];
/* @@protoc_insertion_point(struct:px4_output_pwm_pb) */
} px4_output_pwm_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_output_pwm_pb_init_default           {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define px4_output_pwm_pb_init_zero              {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define px4_output_pwm_pb_timestamp_tag          1
#define px4_output_pwm_pb_channel_count_tag      2
#define px4_output_pwm_pb_values_tag             3

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_output_pwm_pb_fields[4];

/* Maximum encoded size of messages (where known) */
#define px4_output_pwm_pb_size                   113

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define OUTPUT_PWM_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
