/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:15 2016. */

#ifndef PB_QSHELL_REQ_PB_H_INCLUDED
#define PB_QSHELL_REQ_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_qshell_req_pb_QSHELL_REQ {
    px4_qshell_req_pb_QSHELL_REQ_QSHELL_REQ_MAX_STRLEN = 100
} px4_qshell_req_pb_QSHELL_REQ;
#define _px4_qshell_req_pb_QSHELL_REQ_MIN px4_qshell_req_pb_QSHELL_REQ_QSHELL_REQ_MAX_STRLEN
#define _px4_qshell_req_pb_QSHELL_REQ_MAX px4_qshell_req_pb_QSHELL_REQ_QSHELL_REQ_MAX_STRLEN
#define _px4_qshell_req_pb_QSHELL_REQ_ARRAYSIZE ((px4_qshell_req_pb_QSHELL_REQ)(px4_qshell_req_pb_QSHELL_REQ_QSHELL_REQ_MAX_STRLEN+1))

/* Struct definitions */
typedef struct _px4_qshell_req_pb {
    uint64_t timestamp;
    uint64_t strlen;
    pb_size_t string_count;
    int32_t string[100];
/* @@protoc_insertion_point(struct:px4_qshell_req_pb) */
} px4_qshell_req_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_qshell_req_pb_init_default           {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define px4_qshell_req_pb_init_zero              {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define px4_qshell_req_pb_timestamp_tag          1
#define px4_qshell_req_pb_strlen_tag             2
#define px4_qshell_req_pb_string_tag             3

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_qshell_req_pb_fields[4];

/* Maximum encoded size of messages (where known) */
#define px4_qshell_req_pb_size                   1122

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define QSHELL_REQ_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
