/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:16 2016. */

#ifndef PB_SATELLITE_INFO_PB_H_INCLUDED
#define PB_SATELLITE_INFO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_satellite_info_pb_SAT_INFO {
    px4_satellite_info_pb_SAT_INFO_SAT_INFO_MAX_SATELLITES = 20
} px4_satellite_info_pb_SAT_INFO;
#define _px4_satellite_info_pb_SAT_INFO_MIN px4_satellite_info_pb_SAT_INFO_SAT_INFO_MAX_SATELLITES
#define _px4_satellite_info_pb_SAT_INFO_MAX px4_satellite_info_pb_SAT_INFO_SAT_INFO_MAX_SATELLITES
#define _px4_satellite_info_pb_SAT_INFO_ARRAYSIZE ((px4_satellite_info_pb_SAT_INFO)(px4_satellite_info_pb_SAT_INFO_SAT_INFO_MAX_SATELLITES+1))

/* Struct definitions */
typedef struct _px4_satellite_info_pb {
    uint64_t timestamp;
    uint32_t count;
    pb_size_t svid_count;
    uint32_t svid[20];
    pb_size_t used_count;
    uint32_t used[20];
    pb_size_t elevation_count;
    uint32_t elevation[20];
    pb_size_t azimuth_count;
    uint32_t azimuth[20];
    pb_size_t snr_count;
    uint32_t snr[20];
/* @@protoc_insertion_point(struct:px4_satellite_info_pb) */
} px4_satellite_info_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_satellite_info_pb_init_default       {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define px4_satellite_info_pb_init_zero          {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define px4_satellite_info_pb_timestamp_tag      1
#define px4_satellite_info_pb_count_tag          2
#define px4_satellite_info_pb_svid_tag           3
#define px4_satellite_info_pb_used_tag           4
#define px4_satellite_info_pb_elevation_tag      5
#define px4_satellite_info_pb_azimuth_tag        6
#define px4_satellite_info_pb_snr_tag            7

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_satellite_info_pb_fields[8];

/* Maximum encoded size of messages (where known) */
#define px4_satellite_info_pb_size               617

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SATELLITE_INFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
