/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:16 2016. */

#ifndef PB_SUBSYSTEM_INFO_PB_H_INCLUDED
#define PB_SUBSYSTEM_INFO_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_subsystem_info_pb_SUBSYSTEM_TYPE {
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_GYRO = 1,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_ACC = 2,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_MAG = 4,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_ABSPRESSURE = 8,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_DIFFPRESSURE = 16,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_GPS = 32,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_OPTICALFLOW = 64,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_CVPOSITION = 128,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_LASERPOSITION = 256,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_EXTERNALGROUNDTRUTH = 512,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_ANGULARRATECONTROL = 1024,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_ATTITUDESTABILIZATION = 2048,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_YAWPOSITION = 4096,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_ALTITUDECONTROL = 16384,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_POSITIONCONTROL = 32768,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_MOTORCONTROL = 65535,
    px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_RANGEFINDER = 131072
} px4_subsystem_info_pb_SUBSYSTEM_TYPE;
#define _px4_subsystem_info_pb_SUBSYSTEM_TYPE_MIN px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_GYRO
#define _px4_subsystem_info_pb_SUBSYSTEM_TYPE_MAX px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_RANGEFINDER
#define _px4_subsystem_info_pb_SUBSYSTEM_TYPE_ARRAYSIZE ((px4_subsystem_info_pb_SUBSYSTEM_TYPE)(px4_subsystem_info_pb_SUBSYSTEM_TYPE_SUBSYSTEM_TYPE_RANGEFINDER+1))

/* Struct definitions */
typedef struct _px4_subsystem_info_pb {
    uint64_t timestamp;
    uint64_t subsystem_type;
    bool present;
    bool enabled;
    bool ok;
/* @@protoc_insertion_point(struct:px4_subsystem_info_pb) */
} px4_subsystem_info_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_subsystem_info_pb_init_default       {0, 0, 0, 0, 0}
#define px4_subsystem_info_pb_init_zero          {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_subsystem_info_pb_timestamp_tag      1
#define px4_subsystem_info_pb_subsystem_type_tag 2
#define px4_subsystem_info_pb_present_tag        3
#define px4_subsystem_info_pb_enabled_tag        4
#define px4_subsystem_info_pb_ok_tag             5

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_subsystem_info_pb_fields[6];

/* Maximum encoded size of messages (where known) */
#define px4_subsystem_info_pb_size               28

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SUBSYSTEM_INFO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
