/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:16 2016. */

#ifndef PB_TEST_MOTOR_PB_H_INCLUDED
#define PB_TEST_MOTOR_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_test_motor_pb_MOTOR_OUTPUTS {
    px4_test_motor_pb_MOTOR_OUTPUTS_MOTOR_OUTPUTS_COUNT = 8
} px4_test_motor_pb_MOTOR_OUTPUTS;
#define _px4_test_motor_pb_MOTOR_OUTPUTS_MIN px4_test_motor_pb_MOTOR_OUTPUTS_MOTOR_OUTPUTS_COUNT
#define _px4_test_motor_pb_MOTOR_OUTPUTS_MAX px4_test_motor_pb_MOTOR_OUTPUTS_MOTOR_OUTPUTS_COUNT
#define _px4_test_motor_pb_MOTOR_OUTPUTS_ARRAYSIZE ((px4_test_motor_pb_MOTOR_OUTPUTS)(px4_test_motor_pb_MOTOR_OUTPUTS_MOTOR_OUTPUTS_COUNT+1))

/* Struct definitions */
typedef struct _px4_test_motor_pb {
    uint64_t timestamp;
    uint32_t motor_number;
    float value;
/* @@protoc_insertion_point(struct:px4_test_motor_pb) */
} px4_test_motor_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_test_motor_pb_init_default           {0, 0, 0}
#define px4_test_motor_pb_init_zero              {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_test_motor_pb_timestamp_tag          1
#define px4_test_motor_pb_motor_number_tag       2
#define px4_test_motor_pb_value_tag              3

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_test_motor_pb_fields[4];

/* Maximum encoded size of messages (where known) */
#define px4_test_motor_pb_size                   22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TEST_MOTOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
