/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_global_position.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_global_position_pb_fields[16] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_global_position_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, time_utc_usec, timestamp, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, lat, time_utc_usec, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, lon, lat, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, alt, lon, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, vel_n, alt, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, vel_e, vel_n, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, vel_d, vel_e, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, yaw, vel_d, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, eph, yaw, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, epv, eph, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, terrain_alt, epv, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, pressure_alt, terrain_alt, 0),
    PB_FIELD( 14, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, terrain_alt_valid, pressure_alt, 0),
    PB_FIELD( 15, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_global_position_pb, dead_reckoning, terrain_alt_valid, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
