/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_local_position.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_local_position_pb_fields[25] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_local_position_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, ref_timestamp, timestamp, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, ref_lat, ref_timestamp, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, ref_lon, ref_lat, 0),
    PB_FIELD(  5, UINT64  , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, surface_bottom_timestamp, ref_lon, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, x, surface_bottom_timestamp, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, y, x, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, z, y, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, vx, z, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, vy, vx, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, vz, vy, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, yaw, vz, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, ref_alt, yaw, 0),
    PB_FIELD( 14, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, dist_bottom, ref_alt, 0),
    PB_FIELD( 15, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, dist_bottom_rate, dist_bottom, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, eph, dist_bottom_rate, 0),
    PB_FIELD( 17, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, epv, eph, 0),
    PB_FIELD( 18, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, xy_valid, epv, 0),
    PB_FIELD( 19, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, z_valid, xy_valid, 0),
    PB_FIELD( 20, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, v_xy_valid, z_valid, 0),
    PB_FIELD( 21, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, v_z_valid, v_xy_valid, 0),
    PB_FIELD( 22, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, xy_global, v_z_valid, 0),
    PB_FIELD( 23, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, z_global, xy_global, 0),
    PB_FIELD( 24, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_local_position_pb, dist_bottom_valid, z_global, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
