/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:18 2016. */

#ifndef PB_VTOL_VEHICLE_STATUS_PB_H_INCLUDED
#define PB_VTOL_VEHICLE_STATUS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE {
    px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_UNDEFINED = 0,
    px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_TRANSITION_TO_FW = 1,
    px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_TRANSITION_TO_MC = 2,
    px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_MC = 3,
    px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_FW = 4
} px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE;
#define _px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_MIN px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_UNDEFINED
#define _px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_MAX px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_FW
#define _px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_ARRAYSIZE ((px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE)(px4_vtol_vehicle_status_pb_VEHICLE_VTOLSTATE_VEHICLE_VTOL_STATE_FW+1))

/* Struct definitions */
typedef struct _px4_vtol_vehicle_status_pb {
    uint64_t timestamp;
    float airspeed_tot;
    bool vtol_in_rw_mode;
    bool vtol_in_trans_mode;
    bool vtol_transition_failsafe;
    bool fw_permanent_stab;
/* @@protoc_insertion_point(struct:px4_vtol_vehicle_status_pb) */
} px4_vtol_vehicle_status_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_vtol_vehicle_status_pb_init_default  {0, 0, 0, 0, 0, 0}
#define px4_vtol_vehicle_status_pb_init_zero     {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_vtol_vehicle_status_pb_timestamp_tag 1
#define px4_vtol_vehicle_status_pb_airspeed_tot_tag 2
#define px4_vtol_vehicle_status_pb_vtol_in_rw_mode_tag 3
#define px4_vtol_vehicle_status_pb_vtol_in_trans_mode_tag 4
#define px4_vtol_vehicle_status_pb_vtol_transition_failsafe_tag 5
#define px4_vtol_vehicle_status_pb_fw_permanent_stab_tag 6

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_vtol_vehicle_status_pb_fields[7];

/* Maximum encoded size of messages (where known) */
#define px4_vtol_vehicle_status_pb_size          24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define VTOL_VEHICLE_STATUS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
