---
config_base: ${PROJECT_SOURCE_DIR}

modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/core/osal/fsw/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/bebop2/wh_design.yaml
      
  amc:
    definition: ${PROJECT_SOURCE_DIR}/apps/amc/wh_design.yaml
    telemetry:
      AMC_OUT_DATA_MID: 
        msgID: 0x0919
        struct: AMC_BebopObservationMsg_t
    command:
