---
config_base: ${PROJECT_SOURCE_DIR}
modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/core/osal/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/core/psp/pc-linux-wh/wh_design.yaml