---
config_base: ${PROJECT_SOURCE_DIR}
cpu_id: simlink
modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/core/osal/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/core/psp/pc-linux-wh/wh_design.yaml
      cfe:
        modules:
          cfe_es:
            telemetry:
              CFE_ES_HK_TLM_MID:
                msgID: 0x0c0f          # TLM_MSG(   15 )
              CFE_ES_APP_TLM_MID:
                msgID: 0x0c17          # TLM_MSG(   23 )
              CFE_ES_MEMSTATS_TLM_MID:
                msgID: 0x0c1c          # TLM_MSG(   28 )
              CFE_ES_SHELL_TLM_MID:
                msgID: 0x0c1b          # TLM_MSG(   27 )
            commands:
              CFE_ES_CMD_MID:
                msgID: 0x1c04          # CMD_MSG(    4 )
              CFE_ES_SEND_HK_MID:
                msgID: 0x1c05          # CMD_MSG(    5 )
          cfe_evs:
            telemetry:
              CFE_EVS_HK_TLM_MID:
                msgID: 0x0c10          # TLM_MSG(   16 )
              CFE_EVS_EVENT_MSG_MID:
                msgID: 0x0c15          # TLM_MSG(   21 )
            commands:
              CFE_EVS_CMD_MID:
                msgID: 0x1c00          # CMD_MSG(    0 )
              CFE_EVS_SEND_HK_MID:
                msgID: 0x1c06          # CMD_MSG(    6 )
          cfe_sb:
            telemetry:
              CFE_SB_HK_TLM_MID:
                msgID: 0x0c11          # TLM_MSG(   17 )
              CFE_SB_STATS_TLM_MID:
                msgID: 0x0c16          # TLM_MSG(   22 )
              CFE_SB_ALLSUBS_TLM_MID:
                msgID: 0x0c19          # TLM_MSG(   25 )
              CFE_SB_ONESUB_TLM_MID:
                msgID: 0x0c1a          # TLM_MSG(   26 )
            commands:
              CFE_SB_CMD_MID:
                msgID: 0x1c01          # CMD_MSG(    1 )
              CFE_SB_SEND_HK_MID:
                msgID: 0x1c07          # CMD_MSG(    6 )
          cfe_tbl:
            telemetry:
              CFE_TBL_HK_TLM_MID:
                msgID: 0x0c12          # TLM_MSG(   18 )
              CFE_TBL_REG_TLM_MID:
                msgID: 0x0c18          # TLM_MSG(   24 )
            commands:
              CFE_TBL_CMD_MID:
                msgID: 0x1c02          # CMD_MSG(    2 )
              CFE_TBL_SEND_HK_MID:
                msgID: 0x1c08          # CMD_MSG(    8 )
          cfe_time:
            telemetry:
              CFE_TIME_DIAG_TLM_MID:
                msgID: 0x0c14          # TLM_MSG(   20 )
              CFE_TIME_HK_TLM_MID:
                msgID: 0x0c13          # TLM_MSG(   19 )
            commands:
              CFE_TIME_CMD_MID:
                msgID: 0x1c03          # CMD_MSG(    3 )
              CFE_TIME_SEND_HK_MID:
                msgID: 0x1c09          # CMD_MSG(    9 )
              CFE_TIME_DATA_CMD_MID:
                msgID: 0x1c0c          # CMD_MSG(   12 )
              CFE_TIME_TONE_CMD_MID:
                msgID: 0x1c0a          # CMD_MSG(   10 )
              CFE_TIME_FAKE_CMD_MID:
                msgID: 0x1c0d          # CMD_MSG(   13 )
              CFE_TIME_1HZ_CMD_MID:
                msgID: 0x1c0b          # CMD_MSG(   11 )
              CFE_TIME_SEND_CMD_MID:
                msgID: 0x1c0e          # CMD_MSG(   14 )
        
  apps:
    modules:  
      ci:
        definition: ${PROJECT_SOURCE_DIR}/apps/ci/wh_design.yaml
        telemetry:
          CI_HK_TLM_MID:
            msgID: 0x0c27              # TLM_MSG(   39 )
        commands:
          CI_CMD_MID:
            msgID: 0x1c28              # CMD_MSG(   40 )
          CI_INGEST_COMMANDS_MID:
            msgID: 0x1c29              # CMD_MSG(   41 )
          CI_PROCESS_TIMEOUTS_MID:
            msgID: 0x1c2a              # CMD_MSG(   42 )
          CI_SEND_HK_MID:
            msgID: 0x1c2b              # CMD_MSG(   43 )
          CI_WAKEUP_MID:
            msgID: 0x1c2c              # CMD_MSG(   44 )
        perfids:
          CF_APPMAIN_PERF_ID:
            id: 33
          CI_MAIN_TASK_PERF_ID:
            id: 34
          CI_SOCKET_RCV_PERF_ID:
            id: 35

      md:
        definition: ${PROJECT_SOURCE_DIR}/apps/md/wh_design.yaml
        telemetry: 
          MD_DWELL_PKT_MID_BASE: 
            msgID: 0x0c50              # TLM_MSG(   80 )
          MD_HK_TLM_MID: 
            msgID: 0x0c51              # TLM_MSG(   81 )
        commands: 
          MD_CMD_MID: 
            msgID: 0x1c52              # CMD_MSG(   82 )
          MD_SEND_HK_MID: 
            msgID: 0x1c53              # CMD_MSG(   83 )
          MD_WAKEUP_MID: 
            msgID: 0x1c54              # CMD_MSG(   84 )
        perfids: 
          MD_APPMAIN_PERF_ID: 
            id: 53

      mm:
        definition: ${PROJECT_SOURCE_DIR}/apps/mm/wh_design.yaml
        telemetry: 
          MM_HK_TLM_MID: 
            msgID: 0x0c55              # TLM_MSG(   85 )
        commands: 
          MM_CMD_MID: 
            msgID: 0x1c56              # CMD_MSG(   86 )
          MM_SEND_HK_MID: 
            msgID: 0x1c57              # CMD_MSG(   87 )
        perfids: 
          MM_APPMAIN_PERF_ID: 
            id: 54
          MM_EEPROM_FILELOAD_PERF_ID: 
            id: 55
          MM_EEPROM_FILL_PERF_ID: 
            id: 56
          MM_EEPROM_POKE_PERF_ID: 
            id: 57
          MM_SEGBREAK_PERF_ID: 
            id: 58

      sch:
        definition: ${PROJECT_SOURCE_DIR}/apps/sch/wh_design.yaml
        telemetry:
          SCH_ACTIVITY_DONE_MID:
            msgID: 0x0c63              # TLM_MSG(   99 )
          SCH_DIAG_TLM_MID:
            msgID: 0x0c64              # TLM_MSG(  100 )
          SCH_HK_TLM_MID:
            msgID: 0x0c65              # TLM_MSG(  101 )
        commands:
          SCH_CMD_MID:
            msgID: 0x1c66              # CMD_MSG(  102 )
          SCH_SEND_HK_MID:
            msgID: 0x1c67              # CMD_MSG(  103 )
        perfids:
          SCH_APPMAIN_PERF_ID:
            id: 60

      to:
        definition: ${PROJECT_SOURCE_DIR}/apps/to/wh_design.yaml
        commander:
          displays: cdr
          templates:
            _ADD_MESSAGE_FLOW:
              template: "../../config/multirotor/cdr/TO_AddMessageFlow.j2"
              output: "TO_AddMessageFlow.bob"
              scope: GLOBAL
            _QUERY_MESSAGE_FLOW:
              template: "cdr/resources/templates/TO_QueryMessageFlow.j2"
              output: "TO_QueryMessageFlow.bob"
              scope: GLOBAL
            _REMOVE_MESSAGE_FLOW:
              template: "../../config/multirotor/cdr/TO_RemoveMessageFlow.j2"
              output: "TO_RemoveMessageFlow.bob"
              scope: GLOBAL
            _TLM_MANAGEMENT_FLOW:
              template: "cdr/resources/templates/TO_TlmManagement.j2"
              output: "TO_TlmManagement.bob"
              scope: GLOBAL
        telemetry:
          TO_DIAG_MSG_FLOW_MID: 
            msgID: 0x0c69              # TLM_MSG(  105 )
          TO_DIAG_TLM_MID:
            msgID: 0x0c6a              # TLM_MSG(  106 )
          TO_HK_TLM_MID:
            msgID: 0x0c6b              # TLM_MSG(  107 )
        commands:
          TO_CMD_MID:
            msgID: 0x1c6c              # CMD_MSG(  108 )
            commands: 
              EnableChannel:
                cc: 10
                struct: TO_EnableChannelCmd_t
              DisableChannel:
                cc: 11
                struct: TO_DisableChannelCmd_t   
          TO_SEND_HK_MID:
            msgID: 0x1c6d              # CMD_MSG(  109 ) 
          TO_SEND_TLM_MID:
            msgID: 0x1c6e              # CMD_MSG(  110 ) 
        tables:
          _TO_CONFIG:
            channel:
              - name: "ground"
                instance:
                -  name: "default"
                   output: "to_config.c"
                   id: 1
                   is_backup: false
                   priority_queue:
                     - name:  "SINGLE_PASS"
                       type:  "SINGLE"
                       depth: 20
                     - name:  "HIGH_OPS_RSRVD"
                       type:  "FIFO"
                       depth: 20
                     - name:  "SHELL"
                       type:  "FIFO"
                       depth: 64
                     - name:  "EVENTS"
                       type:  "FIFO"
                       depth: 32
                     - name:  "HIGH"
                       type:  "FIFO"
                       depth: 32
                     - name:  "HK"
                       type:  "FIFO"
                       depth: 50
                   message_flow:
                     - msg: "AMC_HK_TLM_MID"
                       depth: 1
                       pqueue: "CPD_HK"
                     - msg: "BAT_HK_TLM_MID"
                       depth: 1
                       pqueue: "CPD_HK"
                     - msg: "CF_CONFIG_TLM_MID"
                       depth: 1
                       pqueue: "CPD_HK"
                     - msg: "CF_HK_TLM_MID"
                       depth: 1
                       pqueue: "CPD_HK"
                     - msg: "CF_SPACE_TO_GND_PDU_MID"
                       depth: 32
                       pqueue: "CPD_CFDP"
                     - msg: "CF_TRANS_TLM_MID"
                       depth: 1
                       pqueue: "CPD_HK"
                     - msg: "CFE_ES_APP_TLM_MID"
                       depth: 1
                       pqueue: "CPD_HK"

      simlink:
        definition: ${PROJECT_SOURCE_DIR}/apps/simlink/gazebo9/wh_design.yaml
        telemetry:
          SIMLINK_HK_TLM_MID:
            msgID: 0x0c3f 
        commands:
          SIMLINK_CMD_MID:
            msgID: 0x1c41
          SIMLINK_SEND_HK_MID:
            msgID: 0x1c42
          SIMLINK_WAKEUP_MID:
            msgID: 0x1c43
        perfids:
          SIMLINK_MAIN_TASK_PERF_ID:
            id: 115

      cvt:
        definition: ${PROJECT_SOURCE_DIR}/apps/cvt/wh_design.yaml
        telemetry:
          CVT_HK_TLM_MID:
            msgID: 0x0c44
        commands:
          CVT_CMD_MID:
            msgID: 0x1c45
          CVT_SEND_HK_MID:
            msgID: 0x1c46
          CVT_WAKEUP_MID:
            msgID: 0x1c47
        perfids:
          CVT_MAIN_TASK_PERF_ID:
            id: 64

      ublox_m8n:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/gps/simlink/ublox_m8n/wh_design.yaml
        telemetry:
          UBLOX_M8N_HK_TLM_MID:
            msgID: 0x0c44
        commands:
          UBLOX_M8N_CMD_MID:
            msgID: 0x1c45
          UBLOX_M8N_SEND_HK_MID:
            msgID: 0x1c46
          UBLOX_M8N_WAKEUP_MID:
            msgID: 0x1c47
        perfids:
          UBLOX_M8N_MAIN_TASK_PERF_ID:
            id: 117

      hmc5883:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/hmc5883/simlink/wh_design.yaml
        telemetry:
          HMC5883_DIAG_TLM_MID:
            msgID: 0x0c14
          HMC5883_HK_TLM_MID:
            msgID: 0x1c15
        commands:
          HMC5883_CMD_MID:
            msgID: 0x1c16
          HMC5883_SEND_HK_MID:
            msgID: 0x1c17
          HMC5883_WAKEUP_MID:
            msgID: 0x1c18
        perfids:
          HMC5883_MAIN_TASK_PERF_ID:
            id: 72

      icm20689:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/icm20689/simlink/wh_design.yaml
        telemetry:
          ICM20689_DIAG_TLM_MID:
            msgID: 0x0c19
          ICM20689_HK_TLM_MID:
            msgID: 0x0c1a
        commands:
          ICM20689_CMD_MID:
            msgID: 0x1c1b
          ICM20689_MEASURE_MID:
            msgID: 0x1c1c
          ICM20689_SEND_HK_MID:
            msgID: 0x1c1d
        perfids:
          ICM20689_MAIN_TASK_PERF_ID:
            id: 118

      ms5611:
        definition: ${PROJECT_SOURCE_DIR}/apps/ms5611/simlink/wh_design.yaml
        telemetry:
          MS5611_HK_TLM_MID:
            msgID: 0x0c1f
        commands:
          MS5611_CMD_MID:
            msgID: 0x1c20
          MS5611_SEND_HK_MID:
            msgID: 0x1c21
          MS5611_WAKEUP_MID:
            msgID: 0x1c22
        perfids:
          MS5611_MAIN_TASK_PERF_ID:
            id: 87

      rfd900x:
        definition: ${PROJECT_SOURCE_DIR}/apps/rfd900x/simlink/wh_design.yaml
        telemetry:
          RFD900X_HK_TLM_MID:
            msgID: 0x0c4a
        commands:
          RFD900X_CMD_MID:
            msgID: 0x1c4b
          RFD900X_SEND_HK_MID:
            msgID: 0x1c4c
          RFD900X_WAKEUP_MID:
            msgID: 0x1c4d
        perfids:
          RFD900X_MAIN_TASK_PERF_ID:
            id: 119

      sedpwm:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/sedpwm/simlink/wh_design.yaml
        telemetry:
          SEDPWM_HK_TLM_MID:
            msgID: 0x0c4f
        commands:
          SEDPWM_CMD_MID:
            msgID: 0x1c50
          SEDPWM_SEND_HK_MID:
            msgID: 0x1c51
          SEDPWM_WAKEUP_MID:
            msgID: 0x1c52
        perfids:
          SEDPWM_MAIN_TASK_PERF_ID:
            id: 120

