/* This file was autogenerated from template version 0.0.0.1 and autogenerator version 0.0.0.1 */

#include "pb.h"
#include "pb_encode.h"
#include "pb_decode.h"
#include "pb_lib.h"
#include "PX4_DistanceSensorMsg_t.pb.h"
#include "PX4_VehicleGlobalPositionMsg_t.pb.h"
#include "PX4_SensorCombinedMsg_t.pb.h"
#include "PX4_EstimatorStatusMsg_t.pb.h"
#include "PX4_McAttCtrlStatusMsg_t.pb.h"
#include "PX4_InputRcMsg_t.pb.h"
#include "PX4_VehicleAttitudeMsg_t.pb.h"
#include "PX4_VehicleAttitudeSetpointMsg_t.pb.h"
#include "PX4_VehicleCommandMsg_t.pb.h"
#include "PX4_LedControlMsg_t.pb.h"
#include "PX4_AirspeedMsg_t.pb.h"
#include "PX4_SafetyMsg_t.pb.h"
#include "PX4_ActuatorControlsMsg_t.pb.h"
#include "PX4_BatteryStatusMsg_t.pb.h"
#include "PX4_VehicleStatusMsg_t.pb.h"
#include "PX4_PositionSetpointTripletMsg_t.pb.h"
#include "PX4_VehicleGpsPositionMsg_t.pb.h"
#include "PX4_VehicleLocalPositionSetpointMsg_t.pb.h"
#include "PX4_HomePositionMsg_t.pb.h"
#include "PX4_VehicleLocalPositionMsg_t.pb.h"
#include "PX4_TelemetryStatusMsg_t.pb.h"
#include "PX4_SaturationStatus_t.pb.h"
#include "PX4_VehicleRatesSetpointMsg_t.pb.h"
#include "PX4_VehicleControlModeMsg_t.pb.h"
#include "PX4_VehicleLandDetectedMsg_t.pb.h"
#include "PX4_MissionMsg_t.pb.h"
#include "PX4_MissionResultMsg_t.pb.h"
#include "PX4_RcChannelsMsg_t.pb.h"
#include "PX4_GpsInjectDataMsg_t.pb.h"
#include "PX4_ControlStateMsg_t.pb.h"
#include "PX4_SubsystemInfoMsg_t.pb.h"
#include "PX4_ManualControlSetpointMsg_t.pb.h"
#include "PX4_SensorBaroMsg_t.pb.h"
#include "PX4_SensorAccelMsg_t.pb.h"
#include "PX4_SensorMagMsg_t.pb.h"
#include "PX4_DifferentialPressureMsg_t.pb.h"
#include "PX4_SensorGyroMsg_t.pb.h"
#include "PX4_ActuatorArmedMsg_t.pb.h"
#include "PX4_ActuatorOutputsMsg_t.pb.h"
#include "PX4_SensorCorrectionMsg_t.pb.h"
#include "PX4_CommanderStateMsg_t.pb.h"
#include "PX4_SatelliteInfoMsg_t.pb.h"
#include "px4lib.h"
#include "px4_msgs.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 PX4_DistanceSensorMsg_t_Enc(const PX4_DistanceSensorMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_DistanceSensorMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_DistanceSensorMsg_t *inOutObject);

uint32 PX4_VehicleGlobalPositionMsg_t_Enc(const PX4_VehicleGlobalPositionMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleGlobalPositionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleGlobalPositionMsg_t *inOutObject);

uint32 PX4_SensorCombinedMsg_t_Enc(const PX4_SensorCombinedMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SensorCombinedMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SensorCombinedMsg_t *inOutObject);

uint32 PX4_EstimatorStatusMsg_t_Enc(const PX4_EstimatorStatusMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_EstimatorStatusMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_EstimatorStatusMsg_t *inOutObject);

uint32 PX4_PositionSetpoint_t_Enc(const PX4_PositionSetpoint_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_PositionSetpoint_t_Dec(const char *inBuffer, uint32 inSize, PX4_PositionSetpoint_t *inOutObject);

uint32 PX4_McAttCtrlStatusMsg_t_Enc(const PX4_McAttCtrlStatusMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_McAttCtrlStatusMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_McAttCtrlStatusMsg_t *inOutObject);

uint32 PX4_InputRcMsg_t_Enc(const PX4_InputRcMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_InputRcMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_InputRcMsg_t *inOutObject);

uint32 PX4_VehicleAttitudeMsg_t_Enc(const PX4_VehicleAttitudeMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleAttitudeMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleAttitudeMsg_t *inOutObject);

uint32 PX4_VehicleAttitudeSetpointMsg_t_Enc(const PX4_VehicleAttitudeSetpointMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleAttitudeSetpointMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleAttitudeSetpointMsg_t *inOutObject);

uint32 PX4_VehicleCommandMsg_t_Enc(const PX4_VehicleCommandMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleCommandMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleCommandMsg_t *inOutObject);

uint32 PX4_LedControlMsg_t_Enc(const PX4_LedControlMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_LedControlMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_LedControlMsg_t *inOutObject);

uint32 PX4_AirspeedMsg_t_Enc(const PX4_AirspeedMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_AirspeedMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_AirspeedMsg_t *inOutObject);

uint32 PX4_SafetyMsg_t_Enc(const PX4_SafetyMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SafetyMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SafetyMsg_t *inOutObject);

uint32 PX4_ActuatorControlsMsg_t_Enc(const PX4_ActuatorControlsMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_ActuatorControlsMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_ActuatorControlsMsg_t *inOutObject);

uint32 PX4_BatteryStatusMsg_t_Enc(const PX4_BatteryStatusMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_BatteryStatusMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_BatteryStatusMsg_t *inOutObject);

uint32 PX4_VehicleStatusMsg_t_Enc(const PX4_VehicleStatusMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleStatusMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleStatusMsg_t *inOutObject);

uint32 PX4_PositionSetpointTripletMsg_t_Enc(const PX4_PositionSetpointTripletMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_PositionSetpointTripletMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_PositionSetpointTripletMsg_t *inOutObject);

uint32 PX4_VehicleGpsPositionMsg_t_Enc(const PX4_VehicleGpsPositionMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleGpsPositionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleGpsPositionMsg_t *inOutObject);

uint32 PX4_VehicleLocalPositionSetpointMsg_t_Enc(const PX4_VehicleLocalPositionSetpointMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleLocalPositionSetpointMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleLocalPositionSetpointMsg_t *inOutObject);

uint32 PX4_HomePositionMsg_t_Enc(const PX4_HomePositionMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_HomePositionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_HomePositionMsg_t *inOutObject);

uint32 PX4_VehicleLocalPositionMsg_t_Enc(const PX4_VehicleLocalPositionMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleLocalPositionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleLocalPositionMsg_t *inOutObject);

uint32 PX4_TelemetryStatusMsg_t_Enc(const PX4_TelemetryStatusMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_TelemetryStatusMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_TelemetryStatusMsg_t *inOutObject);

uint32 PX4_SaturationStatus_t_Enc(const PX4_SaturationStatus_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SaturationStatus_t_Dec(const char *inBuffer, uint32 inSize, PX4_SaturationStatus_t *inOutObject);

uint32 PX4_VehicleRatesSetpointMsg_t_Enc(const PX4_VehicleRatesSetpointMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleRatesSetpointMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleRatesSetpointMsg_t *inOutObject);

uint32 PX4_VehicleControlModeMsg_t_Enc(const PX4_VehicleControlModeMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleControlModeMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleControlModeMsg_t *inOutObject);

uint32 PX4_VehicleLandDetectedMsg_t_Enc(const PX4_VehicleLandDetectedMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_VehicleLandDetectedMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleLandDetectedMsg_t *inOutObject);

uint32 PX4_MissionMsg_t_Enc(const PX4_MissionMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_MissionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_MissionMsg_t *inOutObject);

uint32 PX4_MissionResultMsg_t_Enc(const PX4_MissionResultMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_MissionResultMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_MissionResultMsg_t *inOutObject);

uint32 PX4_RcChannelsMsg_t_Enc(const PX4_RcChannelsMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_RcChannelsMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_RcChannelsMsg_t *inOutObject);

uint32 PX4_GpsInjectDataMsg_t_Enc(const PX4_GpsInjectDataMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_GpsInjectDataMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_GpsInjectDataMsg_t *inOutObject);

uint32 PX4_ControlStateMsg_t_Enc(const PX4_ControlStateMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_ControlStateMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_ControlStateMsg_t *inOutObject);

uint32 PX4_SubsystemInfoMsg_t_Enc(const PX4_SubsystemInfoMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SubsystemInfoMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SubsystemInfoMsg_t *inOutObject);

uint32 PX4_ManualControlSetpointMsg_t_Enc(const PX4_ManualControlSetpointMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_ManualControlSetpointMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_ManualControlSetpointMsg_t *inOutObject);

uint32 PX4_SensorBaroMsg_t_Enc(const PX4_SensorBaroMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SensorBaroMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SensorBaroMsg_t *inOutObject);

uint32 PX4_SensorAccelMsg_t_Enc(const PX4_SensorAccelMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SensorAccelMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SensorAccelMsg_t *inOutObject);

uint32 PX4_SensorMagMsg_t_Enc(const PX4_SensorMagMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SensorMagMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SensorMagMsg_t *inOutObject);

uint32 PX4_DifferentialPressureMsg_t_Enc(const PX4_DifferentialPressureMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_DifferentialPressureMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_DifferentialPressureMsg_t *inOutObject);

uint32 PX4_SensorGyroMsg_t_Enc(const PX4_SensorGyroMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SensorGyroMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SensorGyroMsg_t *inOutObject);

uint32 PX4_MultirotorMotorLimitsMsg_t_Enc(const PX4_MultirotorMotorLimitsMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_MultirotorMotorLimitsMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_MultirotorMotorLimitsMsg_t *inOutObject);

uint32 PX4_ActuatorArmedMsg_t_Enc(const PX4_ActuatorArmedMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_ActuatorArmedMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_ActuatorArmedMsg_t *inOutObject);

uint32 PX4_ActuatorOutputsMsg_t_Enc(const PX4_ActuatorOutputsMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_ActuatorOutputsMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_ActuatorOutputsMsg_t *inOutObject);

uint32 PX4_SensorCorrectionMsg_t_Enc(const PX4_SensorCorrectionMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SensorCorrectionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SensorCorrectionMsg_t *inOutObject);

uint32 PX4_CommanderStateMsg_t_Enc(const PX4_CommanderStateMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_CommanderStateMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_CommanderStateMsg_t *inOutObject);

uint32 PX4_SatelliteInfoMsg_t_Enc(const PX4_SatelliteInfoMsg_t *inObject, char *inOutBuffer, uint32 inSize);
uint32 PX4_SatelliteInfoMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_SatelliteInfoMsg_t *inOutObject);

#ifdef __cplusplus
} /* extern "C" */
#endif
