#include "fm_msg.h"

FM_NoopCmd_t          FM_NoopCmd_s;
FM_ResetCmd_t         FM_ResetCmd_s;
FM_CopyFileCmd_t      FM_CopyFileCmd_s;
FM_MoveFileCmd_t      FM_MoveFileCmd_s;
FM_RenameFileCmd_t    FM_RenameFileCmd_s;
FM_DeleteFileCmd_t    FM_DeleteFileCmd_s;
FM_DeleteAllCmd_t     FM_DeleteAllCmd_s;
FM_DecompressCmd_t    FM_DecompressCmd_s;
FM_ConcatCmd_t        FM_ConcatCmd_s;
FM_GetFileInfoCmd_t   FM_GetFileInfoCmd_s;
FM_GetOpenFilesCmd_t  FM_GetOpenFilesCmd_s;
FM_CreateDirCmd_t     FM_CreateDirCmd_s;
FM_DeleteDirCmd_t     FM_DeleteDirCmd_s;
FM_GetDirFileCmd_t    FM_GetDirFileCmd_s;
FM_GetDirPktCmd_t     FM_GetDirPktCmd_s;
FM_GetFreeSpaceCmd_t  FM_GetFreeSpaceCmd_s;
FM_SetTableStateCmd_t FM_SetTableStateCmd_s;
FM_SetPermCmd_t       FM_SetPermCmd_s;
FM_DirListPkt_t       FM_DirListPkt_s;
FM_FileInfoPkt_t      FM_FileInfoPkt_s;
FM_OpenFilesPkt_t     FM_OpenFilesPkt_s;
FM_FreeSpacePkt_t     FM_FreeSpacePkt_s;
FM_HousekeepingPkt_t  FM_HousekeepingPkt_s;
FM_HousekeepingCmd_t  FM_HousekeepingCmd_s;
