#include "ds_msg.h"

DS_NoopCmd_t        DS_NoopCmd_s;
DS_ResetCmd_t       DS_ResetCmd_s;
DS_AppStateCmd_t    DS_AppStateCmd_s;
DS_FilterFileCmd_t  DS_FilterFileCmd_s;
DS_FilterTypeCmd_t  DS_FilterTypeCmd_s;
DS_FilterParmsCmd_t DS_FilterParmsCmd_s;
DS_DestTypeCmd_t    DS_DestTypeCmd_s;
DS_DestStateCmd_t   DS_DestStateCmd_s;
DS_DestPathCmd_t    DS_DestPathCmd_s;
DS_DestBaseCmd_t    DS_DestBaseCmd_s;
DS_DestExtCmd_t     DS_DestExtCmd_s;
DS_DestSizeCmd_t    DS_DestSizeCmd_s;
DS_DestAgeCmd_t     DS_DestAgeCmd_s;
DS_DestCountCmd_t   DS_DestCountCmd_s;
DS_CloseFileCmd_t   DS_CloseFileCmd_s;
DS_CloseAllCmd_t    DS_CloseAllCmd_s;
DS_GetFileInfoCmd_t DS_GetFileInfoCmd_s;
DS_AddMidCmd_t      DS_AddMidCmd_s;
