---
config_base: ${PROJECT_SOURCE_DIR}
cpu_id: simlink
modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/public/core/osal/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/public/core/psp/pc-linux-wh/wh_design.yaml
      cfe:
        definition: ${PROJECT_SOURCE_DIR}/core/base/cfe/wh_design.yaml
        modules:
          cfe_es:
            telemetry:
              CFE_ES_HK_TLM_MID:
                msgID: 0x080f
              CFE_ES_APP_TLM_MID:
                msgID: 0x0817
              CFE_ES_MEMSTATS_TLM_MID:
                msgID: 0x081c
              CFE_ES_SHELL_TLM_MID:
                msgID: 0x081b
            commands:
              CFE_ES_CMD_MID:
                msgID: 0x1804
              CFE_ES_SEND_HK_MID:
                msgID: 0x1805
          cfe_evs:
            telemetry:
              CFE_EVS_HK_TLM_MID:
                msgID: 0x0810
              CFE_EVS_EVENT_MSG_MID:
                msgID: 0x0815
            commands:
              CFE_EVS_CMD_MID:
                msgID: 0x1800
              CFE_EVS_SEND_HK_MID:
                msgID: 0x1806
          cfe_sb:
            telemetry:
              CFE_SB_HK_TLM_MID:
                msgID: 0x0811
              CFE_SB_STATS_TLM_MID:
                msgID: 0x0816
              CFE_SB_ALLSUBS_TLM_MID:
                msgID: 0x0819
              CFE_SB_ONESUB_TLM_MID:
                msgID: 0x081a
            commands:
              CFE_SB_CMD_MID:
                msgID: 0x1801
              CFE_SB_SEND_HK_MID:
                msgID: 0x1807
          cfe_tbl:
            telemetry:
              CFE_TBL_HK_TLM_MID:
                msgID: 0x0812
              CFE_TBL_REG_TLM_MID:
                msgID: 0x0818
            commands:
              CFE_TBL_CMD_MID:
                msgID: 0x0802
              CFE_TBL_SEND_HK_MID:
                msgID: 0x1808
          cfe_time:
            telemetry:
              CFE_TIME_DIAG_TLM_MID:
                msgID: 0x0814
              CFE_TIME_HK_TLM_MID:
                msgID: 0x0813
            commands:
              CFE_TIME_CMD_MID:
                msgID: 0x1803
              CFE_TIME_SEND_HK_MID:
                msgID: 0x1809
              CFE_TIME_DATA_CMD_MID:
                msgID: 0x180c
              CFE_TIME_TONE_CMD_MID:
                msgID: 0x180a
              CFE_TIME_FAKE_CMD_MID:
                msgID: 0x180d
              CFE_TIME_1HZ_CMD_MID:
                msgID: 0x180b
              CFE_TIME_SEND_CMD_MID:
                msgID: 0x180e
        
  apps:
    modules:  
      ci:
        definition: ${PROJECT_SOURCE_DIR}/apps/ci/wh_design.yaml
        telemetry:
          CI_HK_TLM_MID:
            msgID: 0x081d
        commands:
          CI_CMD_MID:
            msgID: 0x181e
          CI_PROCESS_TIMEOUTS_MID:
            msgID: 0x181f
          CI_SEND_HK_MID:
            msgID: 0x1820
          CI_WAKEUP_MID:
            msgID: 0x1821
          CI_INGEST_COMMANDS_MID:
            msgID: 0x1822
        perfids:
          CF_APPMAIN_PERF_ID:
            id: 33
          CI_MAIN_TASK_PERF_ID:
            id: 34
          CI_SOCKET_RCV_PERF_ID:
            id: 35

      ds:
        definition: ${PROJECT_SOURCE_DIR}/apps/ds/wh_design.yaml
        telemetry: 
          DS_DIAG_TLM_MID: 
            msgID: 0x0823
          DS_HK_TLM_MID: 
            msgID: 0x0824
        commands: 
          DS_CMD_MID: 
            msgID: 0x1825
          DS_SEND_HK_MID: 
            msgID: 0x1826
        perfids: 
          DS_APPMAIN_PERF_ID: 
            id: 36

      hs:
        definition: ${PROJECT_SOURCE_DIR}/apps/hs/wh_design.yaml
        telemetry: 
          HS_HK_TLM_MID: 
            msgID: 0x0839
        commands: 
          HS_CMD_MID: 
            msgID: 0x1840
          HS_SEND_HK_MID: 
            msgID: 0x1841
          HS_WAKEUP_MID: 
            msgID: 0x1842
        perfids: 
          HS_APPMAIN_PERF_ID: 
            id: 37
          HS_IDLETASK_PERF_ID: 
            id: 38

      md:
        definition: ${PROJECT_SOURCE_DIR}/apps/md/wh_design.yaml
        telemetry: 
          MD_DWELL_PKT_MID_BASE: 
            msgID: 0x082c
          MD_DWELL_PKT1_MID: 
            msgID: 0x082c
          MD_DWELL_PKT2_MID: 
            msgID: 0x082d
          MD_DWELL_PKT3_MID: 
            msgID: 0x082e
          MD_DWELL_PKT4_MID: 
            msgID: 0x082f
          MD_HK_TLM_MID: 
            msgID: 0x0830
        commands: 
          MD_CMD_MID: 
            msgID: 0x1831
          MD_SEND_HK_MID: 
            msgID: 0x1832
          MD_WAKEUP_MID: 
            msgID: 0x1833
        perfids: 
          MD_APPMAIN_PERF_ID: 
            id: 39

      mm:
        definition: ${PROJECT_SOURCE_DIR}/apps/mm/wh_design.yaml
        telemetry: 
          MM_HK_TLM_MID: 
            msgID: 0x0834
        commands: 
          MM_CMD_MID: 
            msgID: 0x1835
          MM_SEND_HK_MID: 
            msgID: 0x1836
        perfids: 
          MM_APPMAIN_PERF_ID: 
            id: 40
          MM_EEPROM_FILELOAD_PERF_ID: 
            id: 41
          MM_EEPROM_FILL_PERF_ID: 
            id: 42
          MM_EEPROM_POKE_PERF_ID: 
            id: 43
          MM_SEGBREAK_PERF_ID: 
            id: 44

      sch:
        definition: ${PROJECT_SOURCE_DIR}/apps/sch/wh_design.yaml
        telemetry:
          SCH_ACTIVITY_DONE_MID:
            msgID: 0x0837
          SCH_DIAG_TLM_MID:
            msgID: 0x0838
          SCH_HK_TLM_MID:
            msgID: 0x0839
        commands:
          SCH_CMD_MID:
            msgID: 0x183a
          SCH_SEND_HK_MID:
            msgID: 0x183b
        perfids:
          SCH_APPMAIN_PERF_ID:
            id: 45

      to:
        definition: ${PROJECT_SOURCE_DIR}/apps/to/wh_design.yaml
        telemetry:
          TO_DATA_TYPE_MID: 
            msgID: 0x083c
          TO_DIAG_MSG_FLOW_MID: 
            msgID: 0x083d
          TO_DIAG_TLM_MID:
            msgID: 0x083e
          TO_HK_TLM_MID:
            msgID: 0x083f
        commands:
          TO_CMD_MID:
            msgID: 0x1840
            commands: 
              EnableChannel:
                cc: 10
                struct: TO_EnableChannelCmd_t
              DisableChannel:
                cc: 11
                struct: TO_DisableChannelCmd_t  
          TO_SEND_HK_MID:
            msgID: 0x1841
          TO_SEND_TLM_MID:
            msgID: 0x1842  
        perfids: 
          TO_MAIN_TASK_PERF_ID: 
            id: 46
          TO_SOCKET_SEND_PERF_ID: 
            id: 47

      simlink:
        definition: ${PROJECT_SOURCE_DIR}/apps/simlink/gazebo9/wh_design.yaml
        telemetry:
          SIMLINK_HK_TLM_MID:
            msgID: 0x0848
        commands:
          RFD900X_CMD_MID:
            msgID: 0x1844
          RFD900X_SEND_HK_MID:
            msgID: 0x1845
          RFD900X_WAKEUP_MID:
            msgID: 0x1846
        perfids:
          RFD900X_MAIN_TASK_PERF_ID:
            id: 63

      cvt:
        definition: ${PROJECT_SOURCE_DIR}/apps/cvt/wh_design.yaml
        telemetry:
          CVT_HK_TLM_MID:
            msgID: 0x084d
        commands:
          CVT_CMD_MID:
            msgID: 0x1849
          CVT_SEND_HK_MID:
            msgID: 0x184a
          CVT_WAKEUP_MID:
            msgID: 0x184b
        perfids:
          CVT_MAIN_TASK_PERF_ID:
            id: 64

      ublox_m8n:
        definition: ${PROJECT_SOURCE_DIR}/apps/gps/simlink/ublox_m8n/wh_design.yaml
        telemetry:
          UBLOX_M8N_HK_TLM_MID:
            msgID: 0x0852
        commands:
          UBLOX_M8N_CMD_MID:
            msgID: 0x184e
          UBLOX_M8N_SEND_HK_MID:
            msgID: 0x184f
          UBLOX_M8N_WAKEUP_MID:
            msgID: 0x1850
        perfids:
          UBLOX_M8N_MAIN_TASK_PERF_ID:
            id: 65

      hmc5883:
        definition: ${PROJECT_SOURCE_DIR}/apps/hmc5883/simlink/wh_design.yaml
        telemetry:
          HMC5883_HK_TLM_MID:
            msgID: 0x0857
        commands:
          HMC5883_CMD_MID:
            msgID: 0x1853
          HMC5883_SEND_HK_MID:
            msgID: 0x1854
          HMC5883_WAKEUP_MID:
            msgID: 0x1855
        perfids:
          HMC5883_MAIN_TASK_PERF_ID:
            id: 66

      icm20689:
        definition: ${PROJECT_SOURCE_DIR}/apps/icm20689/simlink/wh_design.yaml
        telemetry:
          ICM20689_HK_TLM_MID:
            msgID: 0x085c
        commands:
          ICM20689_CMD_MID:
            msgID: 0x1858
          ICM20689_SEND_HK_MID:
            msgID: 0x1859
          ICM20689_WAKEUP_MID:
            msgID: 0x185a
        perfids:
          ICM20689_MAIN_TASK_PERF_ID:
            id: 67

      ms5611:
        definition: ${PROJECT_SOURCE_DIR}/apps/ms5611/simlink/wh_design.yaml
        telemetry:
          MS5611_HK_TLM_MID:
            msgID: 0x0861
        commands:
          MS5611_CMD_MID:
            msgID: 0x185d
          MS5611_SEND_HK_MID:
            msgID: 0x185e
          MS5611_WAKEUP_MID:
            msgID: 0x185f
        perfids:
          MS5611_MAIN_TASK_PERF_ID:
            id: 68

      rfd900x:
        definition: ${PROJECT_SOURCE_DIR}/apps/rfd900x/simlink/wh_design.yaml
        telemetry:
          RFD900X_HK_TLM_MID:
            msgID: 0x0866
        commands:
          RFD900X_CMD_MID:
            msgID: 0x1862
          RFD900X_SEND_HK_MID:
            msgID: 0x1863
          RFD900X_WAKEUP_MID:
            msgID: 0x1864
        perfids:
          RFD900X_MAIN_TASK_PERF_ID:
            id: 69

