---
core:
  url:      git@github.com:WindhoverLabs/cfs-core.git
  branch:   develop
  path:     core/base
  strategy: subtree
  osal:
    posix-fast:
      url:    git@github.com:WindhoverLabs/osal-posix-fast.git
      branch: develop
      path:   core/osal/posix-fast
      strategy: subtree
    posix-nasa:
      url:    git@github.com:WindhoverLabs/osal-posix-nasa.git
      branch: develop
      path:   core/osal/posix-nasa
      strategy: subtree
  psp:
    pc-linux-nasa:
      url:    git@github.com:WindhoverLabs/psp-pc-linux-nasa.git
      branch: develop
      path:   core/psp/pc-linux-nasa
      strategy: subtree
    pc-linux-wh:
      url:    git@github.com:WindhoverLabs/psp-pc-linux-wh.git
      branch: develop
      path:   core/psp/pc-linux-wh
      strategy: subtree

tools:
  auto-yamcs:
    url:    git@github.com:WindhoverLabs/auto-yamcs.git
    branch: develop
    path:   core/tools/auto-yamcs
    strategy: submodule

apps:
  cf:
    url:      git@github.com:WindhoverLabs/cf.git
    branch:   develop
    path:     apps/cf
    strategy: subtree
  cfs_lib:
    url:      git@github.com:WindhoverLabs/cfs_lib.git
    branch:   develop
    path:     apps/cfs_lib
    strategy: subtree
  ci:
    url:      git@github.com:WindhoverLabs/ci.git
    branch:   develop
    path:     apps/ci
    strategy: subtree
  cs:
    url:      git@github.com:WindhoverLabs/cs.git
    branch:   develop
    path:     apps/cs
    strategy: subtree
  ds:
    url:      git@github.com:WindhoverLabs/ds.git
    branch:   develop
    path:     apps/ds
    strategy: subtree
  fm:
    url:      git@github.com:WindhoverLabs/fm.git
    branch:   develop
    path:     apps/fm
    strategy: subtree
  hk:
    url:      git@github.com:WindhoverLabs/hk.git
    branch:   develop
    path:     apps/hk
    strategy: subtree
  hs:
    url:      git@github.com:WindhoverLabs/hs.git
    branch:   develop
    path:     apps/hs
    strategy: subtree
  lc:
    url:      git@github.com:WindhoverLabs/lc.git
    branch:   develop
    path:     apps/lc
    strategy: subtree
  md:
    url:      git@github.com:WindhoverLabs/md.git
    branch:   develop
    path:     apps/md
    strategy: subtree
  mm:
    url:      git@github.com:WindhoverLabs/mm.git
    branch:   develop
    path:     apps/mm
    strategy: subtree
  sbn:
    url:      git@github.com:WindhoverLabs/sbn.git
    branch:   develop
    path:     apps/sbn
    strategy: subtree
  sc:
    url:      git@github.com:WindhoverLabs/sc.git
    branch:   develop
    path:     apps/sc
    strategy: subtree
  sch:
    url:      git@github.com:WindhoverLabs/sch.git
    branch:   develop
    path:     apps/sch
    strategy: subtree
  to:
    url:      git@github.com:WindhoverLabs/to.git
    branch:   develop
    path:     apps/to
    strategy: subtree

  ak8963:
    url:      git@github.com:WindhoverLabs/ak8963.git
    branch:   develop
    path:     apps/ak8963
    strategy: subtree
  amc:
    url:      git@github.com:WindhoverLabs/amc.git
    branch:   develop
    path:     apps/amc
    strategy: subtree
  bat:
    url:      git@github.com:WindhoverLabs/bat.git
    branch:   develop
    path:     apps/bat
    strategy: subtree
  cvt:
    url:      git@github.com:WindhoverLabs/cvt.git
    branch:   develop
    path:     apps/cvt
    strategy: subtree
  ea:
    url:      git@github.com:WindhoverLabs/ea.git
    branch:   develop
    path:     apps/ea
    strategy: subtree
  flow:
    url:      git@github.com:WindhoverLabs/flow.git
    branch:   develop
    path:     apps/flow
    strategy: subtree
  gps:
    url:      git@github.com:WindhoverLabs/gps.git
    branch:   develop
    path:     apps/gps
    strategy: subtree
  hmc5883:
    url:      git@github.com:WindhoverLabs/hmc5883.git
    branch:   develop
    path:     apps/hmc5883
    strategy: subtree
  ld:
    url:      git@github.com:WindhoverLabs/ld.git
    branch:   develop
    path:     apps/ld
    strategy: subtree
  lgc:
    url:      git@github.com:WindhoverLabs/lgc.git
    branch:   develop
    path:     apps/lgc
    strategy: subtree
  mac:
    url:      git@github.com:WindhoverLabs/mac.git
    branch:   develop
    path:     apps/mac
    strategy: subtree
  mavlink:
    url:      git@github.com:WindhoverLabs/mavlink.git
    branch:   develop
    path:     apps/mavlink
    strategy: subtree
  mpc:
    url:      git@github.com:WindhoverLabs/mpc.git
    branch:   develop
    path:     apps/mpc
    strategy: subtree
  mpu6050:
    url:      git@github.com:WindhoverLabs/mpu6050.git
    branch:   develop
    path:     apps/mpu6050
    strategy: subtree
  mpu9250:
    url:      git@github.com:WindhoverLabs/mpu9250.git
    branch:   develop
    path:     apps/mpu9250
    strategy: subtree
  ms5607:
    url:      git@github.com:WindhoverLabs/ms5607.git
    branch:   develop
    path:     apps/ms5607
    strategy: subtree
  ms5611:
    url:      git@github.com:WindhoverLabs/ms5611.git
    branch:   develop
    path:     apps/ms5611
    strategy: subtree
  nav:
    url:      git@github.com:WindhoverLabs/nav.git
    branch:   develop
    path:     apps/nav
    strategy: subtree
  pblib:
    url:      git@github.com:WindhoverLabs/pblib.git
    branch:   develop
    path:     apps/pblib
    strategy: subtree
  pe:
    url:      git@github.com:WindhoverLabs/pe.git
    branch:   develop
    path:     apps/pe
    strategy: subtree
  prmlib:
    url:      git@github.com:WindhoverLabs/prmlib.git
    branch:   develop
    path:     apps/prmlib
    strategy: subtree
  px4br:
    url:      git@github.com:WindhoverLabs/px4br.git
    branch:   develop
    path:     apps/px4br
    strategy: subtree
  px4lib:
    url:      git@github.com:WindhoverLabs/px4lib.git
    branch:   develop
    path:     apps/px4lib
    strategy: subtree
  qae:
    url:      git@github.com:WindhoverLabs/qae.git
    branch:   develop
    path:     apps/qae
    strategy: subtree
  rcin:
    url:      git@github.com:WindhoverLabs/rcin.git
    branch:   develop
    path:     apps/rcin
    strategy: subtree
  rgbled:
    url:      git@github.com:WindhoverLabs/rgbled.git
    branch:   develop
    path:     apps/rgbled
    strategy: subtree
  sens:
    url:      git@github.com:WindhoverLabs/sens.git
    branch:   develop
    path:     apps/sens
    strategy: subtree
  sg33bl:
    url:      git@github.com:WindhoverLabs/sg33bl.git
    branch:   develop
    path:     apps/sg33bl
    strategy: subtree
  sim:
    url:      git@github.com:WindhoverLabs/sim.git
    branch:   develop
    path:     apps/sim
    strategy: subtree
  sonar:
    url:      git@github.com:WindhoverLabs/sonar.git
    branch:   develop
    path:     apps/sonar
    strategy: subtree
  ulr:
    url:      git@github.com:WindhoverLabs/ulr.git
    branch:   develop
    path:     apps/ulr
    strategy: subtree
  vc:
    url:      git@github.com:WindhoverLabs/vc.git
    branch:   develop
    path:     apps/vc
    strategy: subtree
  vm:
    url:      git@github.com:WindhoverLabs/vm.git
    branch:   develop
    path:     apps/vm
    strategy: submodule

