#Configuration tested on YAMCS 5.4.0
services:
  - class: org.yamcs.archive.XtceTmRecorder
  - class: org.yamcs.archive.ParameterRecorder
  - class: org.yamcs.archive.AlarmRecorder
  - class: org.yamcs.archive.EventRecorder
  - class: org.yamcs.archive.ReplayServer
  - class: org.yamcs.parameter.SystemParametersCollector
    args:
      provideJvmVariables: true
      provideFsVariables: true
  - class: org.yamcs.ProcessorCreatorService
    args:
      name: realtime
      type: realtime
  - class: org.yamcs.archive.CommandHistoryRecorder
  - class: org.yamcs.parameterarchive.ParameterArchive
    args:
      realtimeFiller:
        enabled: false
      backFiller:
        enabled: true
        warmupTime: 60
  - class: org.yamcs.tctm.cfs.CfsEventDecoder
    args:
      msgIds: [0x0815, 0x0a15] #Always confirm this ID with CFE_EVS configuration
      byteOrder: LITTLE_ENDIAN
      appNameMax: 40
      eventMsgMax: 122

  - class: org.yamcs.cfdp.CfdpService
    name: cfdp1
    args:
      inStream: cfdp_ch1_in
      outStream: cfdp_ch1_out
      localEntities:
        - name: "0.1"
          id: 1
          bucket: cfdpDownCH1
      remoteEntities:
        - name: "0.2"
          id: 2
          bucket: cfdpUpCH1
      receiverFaultHandlers:
        AckLimitReached: suspend
  - class: org.yamcs.cfdp.CfdpService
    name: cfdp2
    args:
      inStream: cfdp_ch2_in
      outStream: cfdp_ch2_out
      localEntities:
        - name: "0.1"
          id: 1
          bucket: cfdpDownCH2
      remoteEntities:
        - name: "0.3"
          id: 3
          bucket: cfdpUpCH2
      receiverFaultHandlers:
        AckLimitReached: suspend

dataLinks:
  - name: ds-logs
    class: com.windhoverlabs.yamcs.cfs.ds.CfsDsPlugin
    stream: tm_realtime
    buckets: ["cfdpDownCH1", "cfdpDownCH2"]
    DS_FILE_HDR_SUBTYPE: 12346
    DS_TOTAL_FNAME_BUFSIZE: 64
    packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
    packetPreprocessorArgs:
      byteOrder: LITTLE_ENDIAN
      timestampFormat: CFE_SB_TIME_32_16_SUBS
      timeEncoding:
        useLocalGenerationTime: false
        epoch: CUSTOM
        epochUTC: "1970-01-01T00:00:00Z"
        timeIncludesLeapSeconds: false
        
  - name: tmtc_cpd
    class: com.windhoverlabs.yamcs.tctm.SerialATTmTcDatalink
    device: /dev/ttyUSB0
    baudRate: 115200
    flowControl: RTS_CTS
    tm_config:
      stream: tm_realtime
      packetInputStreamClassName: com.windhoverlabs.yamcs.tctm.RFC1055PacketInputStream
      packetInputStreamArgs:
        asm: "1ACFFC1D"
        minLength: 1024
        maxLength: 1024
        dropMalformed: false
      spacecraftId: 1
      maxPacketLength: 32768
      packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
      packetPreprocessorArgs:
        byteOrder: LITTLE_ENDIAN
        #            useLocalGenerationTime: true
        #errorDetection:
        #tcoService:
        timestampFormat: CFE_SB_TIME_32_16_SUBS
        timeEncoding:
          useLocalGenerationTime: false
          epoch: CUSTOM
          epochUTC: "1970-01-01T00:00:00Z"
          timeIncludesLeapSeconds: false
    tc_config:
      spacecraftId: 1
      commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
      commandPostprocessorArgs:
        swapChecksumFc: false
      stream: tc_realtime
      
  - name: tc_ppd
    class: org.yamcs.tctm.UdpTcDataLink
    stream: tc_realtime
    host: 192.168.2.153
    port: 5010
    enabledAtStartup: false
    commandPostprocessorClassName: org.yamcs.tctm.cfs.CfsCommandPostprocessor
    commandPostprocessorArgs:
      swapChecksumFc: true

  - name: tm_ppd
    class: org.yamcs.tctm.UdpTmDataLink
    stream: tm_realtime
    port: 5011
    maxLength: 32768 #32KB is the default for CCSDS
    packetPreprocessorClassName: org.yamcs.tctm.cfs.CfsPacketPreprocessor
    packetPreprocessorArgs:
      checkSequence: false
      byteOrder: LITTLE_ENDIAN
      useLocalGenerationTime: false
      #errorDetection:
      #tcoService:
      timestampFormat: CFE_SB_TIME_32_16_SUBS
      timeEncoding:
        epoch: CUSTOM
        epochUTC: "1970-01-01T00:00:00Z"
        timeIncludesLeapSeconds: false

mdb:
    # Configuration of the active loaders
    # Valid loaders are: sheet, xtce or fully qualified name of the class
    - type: "xtce"
      spec: "mdb/cfs-ccsds.xml"
      subLoaders:
      - type: "xtce"
        spec: "mdb/ppd.xml"
      - type: "xtce"
        spec: "mdb/cpd.xml"

# Configuration for streams created at server startup
streamConfig:
  tm:
    - name: "tm_realtime"
    - name: "tm_dump"
  cmdHist: ["cmdhist_realtime", "cmdhist_dump"]
  event: ["events_realtime", "events_dump"]
  param: ["pp_realtime", "sys_param", "proc_param"]
  parameterAlarm: ["alarms_realtime"]
  tc: ["tc_realtime"]
  sqlFile: "etc/extra_streams.sql"
