---
config_base: ${PROJECT_SOURCE_DIR}

modules:
  core:
    modules:
      cfe:
        definition: ${PROJECT_SOURCE_DIR}/core/base/cfe/wh_design.yaml
        modules:
          cfe_es:
            telemetry:
              CFE_ES_HK_TLM_MID:
                msgID: 0x080f
              CFE_ES_APP_TLM_MID:
                msgID: 0x0817
              CFE_ES_MEMSTATS_TLM_MID:
                msgID: 0x081c
              CFE_ES_SHELL_TLM_MID:
                msgID: 0x081b
            commands:
              CFE_ES_CMD_MID:
                msgID: 0x1804
              CFE_ES_SEND_HK_MID:
                msgID: 0x1805
          cfe_evs:
            telemetry:
              CFE_EVS_HK_TLM_MID:
                msgID: 0x0810
              CFE_EVS_EVENT_MSG_MID:
                msgID: 0x0815
            commands:
              CFE_EVS_CMD_MID:
                msgID: 0x1800
              CFE_EVS_SEND_HK_MID:
                msgID: 0x1806
          cfe_sb:
            telemetry:
              CFE_SB_HK_TLM_MID:
                msgID: 0x0811
              CFE_SB_STATS_TLM_MID:
                msgID: 0x0816
              CFE_SB_ALLSUBS_TLM_MID:
                msgID: 0x0819
              CFE_SB_ONESUB_TLM_MID:
                msgID: 0x081a
            commands:
              CFE_SB_CMD_MID:
                msgID: 0x1801
              CFE_SB_SEND_HK_MID:
                msgID: 0x1807
          cfe_tbl:
            telemetry:
              CFE_TBL_HK_TLM_MID:
                msgID: 0x0812
              CFE_TBL_REG_TLM_MID:
                msgID: 0x0818
            commands:
              CFE_TBL_CMD_MID:
                msgID: 0x0802
              CFE_TBL_SEND_HK_MID:
                msgID: 0x1808
          cfe_time:
            telemetry:
              CFE_TIME_DIAG_TLM_MID:
                msgID: 0x0814
              CFE_TIME_HK_TLM_MID:
                msgID: 0x0813
            commands:
              CFE_TIME_CMD_MID:
                msgID: 0x1803
              CFE_TIME_SEND_HK_MID:
                msgID: 0x1809
              CFE_TIME_DATA_CMD_MID:
                msgID: 0x180c
              CFE_TIME_TONE_CMD_MID:
                msgID: 0x180a
              CFE_TIME_FAKE_CMD_MID:
                msgID: 0x180d
              CFE_TIME_1HZ_CMD_MID:
                msgID: 0x180b
              CFE_TIME_SEND_CMD_MID:
                msgID: 0x180e
      osal:
        definition: ${PROJECT_SOURCE_DIR}/core/osal/posix-fast/wh_design.yaml
    
  ci:
    definition: ${PROJECT_SOURCE_DIR}/apps/ci/wh_design.yaml
    telemetry:
      CI_HK_TLM_MID:
        msgID: 0x0832
    commands:
      CI_CMD_MID:
        msgID: 0x1834
      CI_PROCESS_TIMEOUTS_MID:
        msgID: 0x1835
      CI_SEND_HK_MID:
        msgID: 0x1836
      CI_WAKEUP_MID:
        msgID: 0x1837
      CI_INGEST_COMMANDS_MID:
        msgID: 0x19e5
    perfids:
      CF_APPMAIN_PERF_ID:
        id: 33
      CI_MAIN_TASK_PERF_ID:
        id: 34
      CI_SOCKET_RCV_PERF_ID:
        id: 35
        
  cf:
    definition: ${PROJECT_SOURCE_DIR}/apps/cf/wh_design.yaml
    telemetry: 
      CF_CONFIG_TLM_MID: 
        msgID: 0x0838
      CF_HK_TLM_MID: 
        msgID: 0x0839
      CF_INCOMING_PDU_MID: 
        msgID: 0x183a
      CF_TRANS_TLM_MID:
        msgID: 0x083b
    commands:
      CF_CMD_MID: 
        msgID: 0x183c
      CF_SEND_HK_MID: 
        msgID: 0x183d
      CF_SPACE_TO_GND_PDU_MID:
        msgID: 0x083e
      CF_WAKE_UP_REQ_CMD_MID:
        msgID: 0x183f
    perfids: 
      CF_CYCLE_ENG_PERF_ID: 
        id: 36
      CF_FCLOSE_PERF_ID: 
        id: 37
      CF_FILESIZE_PERF_ID: 
        id: 38
      CF_FOPEN_PERF_ID: 
        id: 39
      CF_FREAD_PERF_ID: 
        id: 40
      CF_FWRITE_PERF_ID: 
        id: 41
      CF_QDIRFILES_PERF_ID: 
        id: 42
      CF_REDLIGHT_PERF_ID: 
        id: 43

  cs:
    definition: ${PROJECT_SOURCE_DIR}/apps/cs/wh_design.yaml
    telemetry: 
      CS_HK_TLM_MID: 
        msgID: 0x0850
    commands: 
      CS_CMD_MID: 
        msgID: 0x1851
      CS_BACKGROUND_CYCLE_MID: 
        msgID: 0x1852
      CS_SEND_HK_MID: 
        msgID: 0x1853
    perfids: 
      CS_APPMAIN_PERF_ID: 
        id: 44

  ds:
    definition: ${PROJECT_SOURCE_DIR}/apps/ds/wh_design.yaml
    telemetry: 
      DS_DIAG_TLM_MID: 
        msgID: 0x0854
      DS_HK_TLM_MID: 
        msgID: 0x0855
    commands: 
      DS_CMD_MID: 
        msgID: 0x1856
      DS_SEND_HK_MID: 
        msgID: 0x1857
    perfids: 
      DS_APPMAIN_PERF_ID: 
        id: 45

  fm:
    definition: ${PROJECT_SOURCE_DIR}/apps/fm/wh_design.yaml
    telemetry: 
      FM_DIR_LIST_TLM_MID: 
        msgID: 0x0858
      FM_FILE_INFO_TLM_MID: 
        msgID: 0x0859
      FM_FREE_SPACE_TLM_MID: 
        msgID: 0x085a
      FM_HK_TLM_MID: 
        msgID: 0x085b
      FM_OPEN_FILES_TLM_MID: 
        msgID: 0x085c
    commands: 
      FM_CMD_MID: 
        msgID: 0x185d
      FM_SEND_HK_MID: 
        msgID: 0x185e
    perfids: 
      FM_APPMAIN_PERF_ID: 
        id: 46
      FM_CHILD_TASK_PERF_ID: 
        id: 47

  hk:
    definition: ${PROJECT_SOURCE_DIR}/apps/hk/wh_design.yaml
    telemetry: 
      HK_COMBINED_PKT1_MID: 
        msgID: 0x0864
      HK_COMBINED_PKT2_MID: 
        msgID: 0x0865
      HK_COMBINED_PKT3_MID: 
        msgID: 0x0866
      HK_COMBINED_PKT4_MID: 
        msgID: 0x0867
      HK_COMBINED_PKT5_MID: 
        msgID: 0x0868
      HK_COMBINED_PKT6_MID: 
        msgID: 0x0869
      HK_COMBINED_PKT7_MID: 
        msgID: 0x086a
      HK_COMBINED_PKT8_MID: 
        msgID: 0x086b
      HK_COMBINED_PKT9_MID: 
        msgID: 0x086c
      HK_COMBINED_PKT10_MID: 
        msgID: 0x086d
      HK_HK_TLM_MID: 
        msgID: 0x086e
    commands: 
      HK_CMD_MID: 
        msgID: 0x186f
      HK_SEND_COMBINED_PKT_MID: 
        msgID: 0x1870
      HK_SEND_HK_MID: 
        msgID: 0x1871
    perfids: 
      HK_APPMAIN_PERF_ID: 
        id: 48

  hs:
    definition: ${PROJECT_SOURCE_DIR}/apps/hs/wh_design.yaml
    telemetry: 
      HS_HK_TLM_MID: 
        msgID: 0x0878
    commands: 
      HS_CMD_MID: 
        msgID: 0x1879
      HS_SEND_HK_MID: 
        msgID: 0x187a
      HS_WAKEUP_MID: 
        msgID: 0x187b
    perfids: 
      HS_APPMAIN_PERF_ID: 
        id: 49
      HS_IDLETASK_PERF_ID: 
        id: 50
    
  lc:
    definition: ${PROJECT_SOURCE_DIR}/apps/lc/wh_design.yaml
    telemetry: 
      LC_HK_TLM_MID: 
        msgID: 0x0882
    commands: 
      LC_CMD_MID: 
        msgID: 0x1883
      LC_SAMPLE_AP_MID: 
        msgID: 0x1884
      LC_SEND_HK_MID: 
        msgID: 0x1885
    perfids: 
      LC_APPMAIN_PERF_ID: 
        id: 51
      LC_WDT_SEARCH_PERF_ID: 
        id: 52

  md:
    definition: ${PROJECT_SOURCE_DIR}/apps/md/wh_design.yaml
    telemetry: 
      MD_DWELL_PKT_MID_BASE: 
        msgID: 0x0886
      MD_DWELL_PKT1_MID: 
        msgID: 0x0886
      MD_DWELL_PKT2_MID: 
        msgID: 0x0887
      MD_DWELL_PKT3_MID: 
        msgID: 0x0888
      MD_DWELL_PKT4_MID: 
        msgID: 0x0889
      MD_HK_TLM_MID: 
        msgID: 0x088b
    commands: 
      MD_CMD_MID: 
        msgID: 0x188c
      MD_SEND_HK_MID: 
        msgID: 0x188d
      MD_WAKEUP_MID: 
        msgID: 0x188e
    perfids: 
      MD_APPMAIN_PERF_ID: 
        id: 53

  mm:
    definition: ${PROJECT_SOURCE_DIR}/apps/mm/wh_design.yaml
    telemetry: 
      MM_HK_TLM_MID: 
        msgID: 0x088f
    commands: 
      MM_CMD_MID: 
        msgID: 0x1890
      MM_SEND_HK_MID: 
        msgID: 0x1891
    perfids: 
      MM_APPMAIN_PERF_ID: 
        id: 54
      MM_EEPROM_FILELOAD_PERF_ID: 
        id: 55
      MM_EEPROM_FILL_PERF_ID: 
        id: 56
      MM_EEPROM_POKE_PERF_ID: 
        id: 57
      MM_SEGBREAK_PERF_ID: 
        id: 58

  sc:
    definition: ${PROJECT_SOURCE_DIR}/apps/sc/wh_design.yaml
    telemetry:
      SC_HK_TLM_MID:
        msgID: 0x0892
    commands:
      SC_1HZ_WAKEUP_MID:
        msgID: 0x1893
      SC_CMD_MID:
        msgID: 0x1894
      SC_SEND_HK_MID:
        msgID: 0x1895
    perfids:
      SC_APPMAIN_PERF_ID:
        id: 59

  sch:
    definition: ${PROJECT_SOURCE_DIR}/apps/sch/wh_design.yaml
    telemetry:
      SCH_ACTIVITY_DONE_MID:
        msgID: 0x0896
      SCH_DIAG_TLM_MID:
        msgID: 0x0897
      SCH_HK_TLM_MID:
        msgID: 0x0898
    commands:
      SCH_CMD_MID:
        msgID: 0x1899
      SCH_SEND_HK_MID:
        msgID: 0x189a
    perfids:
      SCH_APPMAIN_PERF_ID:
        id: 60

  to:
    definition: ${PROJECT_SOURCE_DIR}/apps/to/wh_design.yaml
    telemetry:
      TO_DATA_TYPE_MID: 
        msgID: 0x089b
      TO_DIAG_MSG_FLOW_MID: 
        msgID: 0x089c
      TO_DIAG_TLM_MID:
        msgID: 0x089d
      TO_HK_TLM_MID:
        msgID: 0x089e
    commands:
      TO_CMD_MID:
        msgID: 0x189f
        #commands: 
        #  EnableChannel:
        #    cc: 10
        #    struct: TO_EnableChannelCmd_t
        #  DisableChannel:
        #    cc: 11
        #    struct: TO_DisableChannelCmd_t      

  px4lib:
    definition: ${PROJECT_SOURCE_DIR}/apps/px4lib/wh_design.yaml
    telemetry:
      PX4_ACTUATOR_ARMED_MID:
        msgID: 0x08a2
      PX4_ACTUATOR_CONTROLS_0_MID:
        msgID: 0x08a3
      PX4_ACTUATOR_CONTROLS_1_MID:
        msgID: 0x08a4
      PX4_ACTUATOR_CONTROLS_2_MID:
        msgID: 0x08a5
      PX4_ACTUATOR_CONTROLS_3_MID:
        msgID: 0x08a6
      PX4_ACTUATOR_DIRECT_MID:
        msgID: 0x08a7
      PX4_ACTUATOR_OUTPUTS_MID:
        msgID: 0x08a8
      PX4_ADC_REPORT_MID:
        msgID: 0x08a9
      PX4_AIRSPEED_MID:
        msgID: 0x08aa
      PX4_ATT_POS_MOCAP_MID:
        msgID: 0x08ab
      PX4_BATTERY_STATUS_MID:
        msgID: 0x08ac
      PX4_CAMERA_TRIGGER_MID:
        msgID: 0x08ad
      PX4_COMMANDER_STATE_MID:
        msgID: 0x08ae
      PX4_CONTROL_STATE_MID:
        msgID: 0x08af
      PX4_CPULOAD_MID:
        msgID: 0x08b0
      PX4_DEBUG_KEY_VALUE_MID:
        msgID: 0x08b1
      PX4_DIFFERENTIAL_PRESSURE_MID:
        msgID: 0x08b2
      PX4_DISTANCE_SENSOR_MID:
        msgID: 0x08b3
      PX4_FW_POS_CTRL_STATUS_MID:
        msgID: 0x08b4
      PX4_FW_VIRTUAL_ATTITUDE_SETPOINT_MID:
        msgID: 0x08b5
      PX4_FW_VIRTUAL_RATES_SETPOINT_MID:
        msgID: 0x08b6
      PX4_EKF2_INNOVATIONS_MID:
        msgID: 0x08b7
      PX4_EKF2_REPLAY_MID:
        msgID: 0x08b8
      PX4_ESC_REPORT_MID:
        msgID: 0x08b9
      PX4_ESC_STATUS_MID:
        msgID: 0x08ba
      PX4_ESTIMATOR_STATUS_MID:
        msgID: 0x08bb
      PX4_FENCE_MID:
        msgID: 0x08bc
      PX4_FENCE_VERTEX_MID:
        msgID: 0x08bd
      PX4_FILTERED_BOTTOM_FLOW_MID:
        msgID: 0x08be
      PX4_FOLLOW_TARGET_MID:
        msgID: 0x08bf
      PX4_GEOFENCE_RESULT_MID:
        msgID: 0x08c0
      PX4_GPS_DUMP_MID:
        msgID: 0x08c1
      PX4_GPS_INJECT_DATA_MID:
        msgID: 0x08c2
      PX4_HIL_SENSOR_MID:
        msgID: 0x08c3
      PX4_HOME_POSITION_MID:
        msgID: 0x08c4
      PX4_INPUT_RC_MID:
        msgID: 0x08c5
      PX4_LED_CONTROL_MID:
        msgID: 0x08c6
      PX4_LOG_MESSAGE_MID:
        msgID: 0x08c7
      PX4_MANUAL_CONTROL_SETPOINT_MID:
        msgID: 0x08c8
      PX4_MAVLINK_LOG_MID:
        msgID: 0x08c9
      PX4_MC_ATT_CTRL_STATUS_MID:
        msgID: 0x08ca
      PX4_MC_VIRTUAL_ATTITUDE_SETPOINT_MID:
        msgID: 0x08cb
      PX4_MC_VIRTUAL_RATES_SETPOINT_MID:
        msgID: 0x08cc
      PX4_MISSION_MID:
        msgID: 0x08cd
      PX4_MISSION_RESULT_MID:
        msgID: 0x08ce
      PX4_MULTIROTOR_MOTOR_LIMITS_MID:
        msgID: 0x08cf
      PX4_OFFBOARD_CONTROL_MODE_MID:
        msgID: 0x08d0
      PX4_OPTICAL_FLOW_MID:
        msgID: 0x08d1
      PX4_OUTPUT_PWM_MID:
        msgID: 0x08d2
      PX4_PARAMETER_UPDATE_MID:
        msgID: 0x08d3
      PX4_POSITION_SETPOINT_MID:
        msgID: 0x08d4
      PX4_POSITION_SETPOINT_TRIPLET_MID:
        msgID: 0x08d5
      PX4_PWM_INPUT_MID:
        msgID: 0x08d6
      PX4_QSHELL_REQ_MID:
        msgID: 0x08d7
      PX4_RC_CHANNELS_MID:
        msgID: 0x08d8
      PX4_RC_PARAMETER_MAP_MID:
        msgID: 0x08d9
      PX4_SAFETY_MID:
        msgID: 0x08da
      PX4_SATELLITE_INFO_MID:
        msgID: 0x08db
      PX4_SENSOR_ACCEL_MID:
        msgID: 0x08dc
      PX4_SENSOR_BARO_MID:
        msgID: 0x08dd
      PX4_SENSOR_COMBINED_MID:
        msgID: 0x08de
      PX4_SENSOR_GYRO_MID:
        msgID: 0x08df
      PX4_SENSOR_MAG_MID:
        msgID: 0x08e0
      PX4_SERVORAIL_STATUS_MID:
        msgID: 0x08e1
      PX4_SUBSYSTEM_INFO_MID:
        msgID: 0x08e2
      PX4_SYSTEM_POWER_MID:
        msgID: 0x08e3
      PX4_TECS_STATUS_MID:
        msgID: 0x08e4
      PX4_TELEMETRY_STATUS_MID:
        msgID: 0x08e5
      PX4_TEST_MOTOR_MID:
        msgID: 0x08e6
      PX4_TIME_OFFSET_MID:
        msgID: 0x08e7
      PX4_TRANSPONDER_REPORT_MID:
        msgID: 0x08e8
      PX4_UAVCAN_PARAMETER_REQUEST_MID:
        msgID: 0x08e9
      PX4_UAVCAN_PARAMETER_VALUE_MID:
        msgID: 0x08ea
      PX4_VEHICLE_ATTITUDE_MID:
        msgID: 0x08eb
      PX4_VEHICLE_ATTITUDE_SETPOINT_MID:
        msgID: 0x08ec
      PX4_VEHICLE_COMMAND_ACK_MID:
        msgID: 0x08ed
      PX4_VEHICLE_COMMAND_MID:
        msgID: 0x08ee
      PX4_VEHICLE_CONTROL_MODE_MID:
        msgID: 0x08ef
      PX4_VEHICLE_FORCE_SETPOINT_MID:
        msgID: 0x08f0
      PX4_VEHICLE_GLOBAL_POSITION_MID:
        msgID: 0x08f1
      PX4_VEHICLE_GLOBAL_VELOCITY_SETPOINT_MID:
        msgID: 0x08f2
      PX4_VEHICLE_GPS_POSITION_MID:
        msgID: 0x08f3
      PX4_VEHICLE_LAND_DETECTED_MID:
        msgID: 0x08f4
      PX4_VEHICLE_LOCAL_POSITION_MID:
        msgID: 0x08f5
      PX4_VEHICLE_LOCAL_POSITION_SETPOINT_MID:
        msgID: 0x08f6
      PX4_VEHICLE_RATES_SETPOINT_MID:
        msgID: 0x08f7
      PX4_VEHICLE_STATUS_MID:
        msgID: 0x08f8
      PX4_VISION_POSITION_ESTIMATE_MID:
        msgID: 0x08f9
      PX4_VTOL_VEHICLE_STATUS_MID:
        msgID: 0x08fa
      PX4_WIND_ESTIMATE_MID:
        msgID: 0x08fb
      PX4_SENSOR_CORRECTION_MID:
        msgID: 0x08fc
    
  ea:
    definition: ${PROJECT_SOURCE_DIR}/apps/ea/wh_design.yaml
    telemetry:
      EA_HK_TLM_MID:
        msgID: 0x0925
    commands:
      EA_CMD_MID:
        msgID: 0x1926
      EA_SEND_HK_MID:
        msgID: 0x1927
      EA_WAKEUP_MID:
        msgID: 0x1928
    perfids:
      EA_MAIN_TASK_PERF_ID:
        id: 70
    
  gps:
    definition: ${PROJECT_SOURCE_DIR}/apps/gps/wh_design.yaml
    telemetry:
      GPS_ACK_ACK_MID:
        msgID: 0x092c
      GPS_ACK_NAK_MID:
        msgID: 0x092d
      GPS_CFG_MSG_MID:
        msgID: 0x092e
      GPS_CFG_NAV5_MID:
        msgID: 0x092f
      GPS_CFG_PRT_MID:
        msgID: 0x0930
      GPS_CFG_RATE_MID:
        msgID: 0x0931
      GPS_CFG_SBAS_MID:
        msgID: 0x0932
      GPS_HK_TLM_MID:
        msgID: 0x0933
      GPS_MON_HW_MID:
        msgID: 0x0934
      GPS_NAV_DOP_MID:
        msgID: 0x0935
      GPS_NAV_NAVPVT_MID:
        msgID: 0x0936
      GPS_NAV_SVINFO_MID:
        msgID: 0x0937
      GPS_SEND_HK_MID:
        msgID: 0x0938
      GPS_HK_TLM_MID:
        msgID: 0x0939
    commands:
      GPS_CMD_MID:
        msgID: 0x183a
      GPS_SEND_HK_MID:
        msgID: 0x183b
      GPS_READ_SENSOR_MID:
        msgID: 0x183c
    perfids: 
      GPS_MAIN_TASK_PERF_ID:
        id: 71
        
  vc:
    definition: ${PROJECT_SOURCE_DIR}/apps/vc/wh_design.yaml
    telemetry:
      VC_HK_TLM_MID:
        msgID: 0x09d0
      FLOW_FRAME_MID:
        msgID: 0x09d1
    commands:
      VC_CMD_MID:
        msgID: 0x19d2
      VC_PROCESS_CMDS_MID:
        msgID: 0x19d3
      VC_SEND_HK_MID:
        msgID: 0x19d4
    perfids:
      VC_DEVICE_GET_PERF_ID:
        id: 107
      VC_MAIN_TASK_PERF_ID:
        id: 108
      VC_SOCKET_SEND_PERF_ID:
        id: 109
        
  sbn:
    definition: ${PROJECT_SOURCE_DIR}/apps/sbn/wh_design.yaml
    telemetry:
      SBN_TLM_MID:
        msgID: 0x09ae
      SBN_MODULE_HK_TLM_MID:
        msgID: 0x09b4
    commands:
      SBN_CMD_MID:
        msgID: 0x19af
      SBN_WAKEUP_MID:
        msgID: 0x19b0

  sbnd:
    definition: ${PROJECT_SOURCE_DIR}/../private/apps/sbnd/wh_design.yaml
    telemetry:
      SBND_HK_TLM_MID:
        msgID: 0x09b5
    commands:
      SBND_CMD_MID:
        msgID: 0x19b6
      SBND_WAKEUP_MID:
        msgID: 0x19b0
      SBND_SEND_HK_MID:
        msgID: 0x19b7
    perfids:
      SBND_MAIN_TASK_PERF_ID:
        id: 115

  adsbr:
    definition: ${PROJECT_SOURCE_DIR}/apps/adsbr/wh_design.yaml
    telemetry:
      ADSBR_HK_TLM_MID:
        msgID: 0x09ef
    commands:
      ADSBR_CMD_MID:
        msgID: 0x11eb
      ADSBR_WAKEUP_MID:
        msgID: 0x19ed
      ADSBR_SEND_HK_MID:
        msgID: 0x19ec
    perfids:
      ADSBR_MAIN_TASK_PERF_ID:
        id: 114
