---
config_base: ${PROJECT_SOURCE_DIR}

modules:       
  apps:
    modules:          
      cf:
        definition: ${PROJECT_SOURCE_DIR}/apps/cf/wh_design.yaml
            
      ci:
        definition: ${PROJECT_SOURCE_DIR}/apps/ci/wh_design.yaml

      cs:
        definition: ${PROJECT_SOURCE_DIR}/apps/cs/wh_design.yaml

      cvt:
        definition: ${PROJECT_SOURCE_DIR}/apps/ds/wh_design.yaml

      ds:
        definition: ${PROJECT_SOURCE_DIR}/apps/ds/wh_design.yaml
    
      ea:
        definition: ${PROJECT_SOURCE_DIR}/apps/ea/wh_design.yaml

      fm:
        definition: ${PROJECT_SOURCE_DIR}/apps/fm/wh_design.yaml

      hk:
        definition: ${PROJECT_SOURCE_DIR}/apps/hk/wh_design.yaml

      hs:
        definition: ${PROJECT_SOURCE_DIR}/apps/hs/wh_design.yaml
    
      lc:
        definition: ${PROJECT_SOURCE_DIR}/apps/lc/wh_design.yaml

      md:
        definition: ${PROJECT_SOURCE_DIR}/apps/md/wh_design.yaml

      mm:
        definition: ${PROJECT_SOURCE_DIR}/apps/mm/wh_design.yaml

      sc:
        definition: ${PROJECT_SOURCE_DIR}/apps/sc/wh_design.yaml

      sch:
        definition: ${PROJECT_SOURCE_DIR}/apps/sch/wh_design.yaml

      to:
        definition: ${PROJECT_SOURCE_DIR}/apps/to/wh_design.yaml
        
      gps:
        definition: ${PROJECT_SOURCE_DIR}/apps/gps/wh_design.yaml
            
      sbn:
        definition: ${PROJECT_SOURCE_DIR}/apps/sbn/wh_design.yaml

      sbnd:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/sbnd/wh_design.yaml
            
      vc:
        definition: ${PROJECT_SOURCE_DIR}/apps/vc/wh_design.yaml
             
      ublox_m8n:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/gps/simlink/ublox_m8n/wh_design.yaml

      hmc5883:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/hmc5883/simlink/wh_design.yaml

      icm20689:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/icm20689/simlink/wh_design.yaml

      ms5611:
        definition: ${PROJECT_SOURCE_DIR}/apps/ms5611/simlink/wh_design.yaml

      rfd900x:
        definition: ${PROJECT_SOURCE_DIR}/apps/rfd900x/simlink/wh_design.yaml

      sedpwm:
        definition: ${PROJECT_SOURCE_DIR}/../private/apps/sedpwm/simlink/wh_design.yaml

      vm:
        definition: ${PROJECT_SOURCE_DIR}/apps/vm/wh_design.yaml

      amc:
        definition: ${PROJECT_SOURCE_DIR}/apps/amc/wh_design.yaml

