---
config_base: ${PROJECT_SOURCE_DIR} 
cpu_id: PPD
modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/core/osal/fsw/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/obc-ppd/wh_design.yaml
