obc: 
  - name: A
    fsw:
      tlm:
        port: 5021
      cmd:
        ip:   127.0.0.1
        port: 5020
    gnd:
      tlm:
        ip:   127.0.0.1
        port: 5111
      cmd: 
        port: 5110
    sim:
      ip:    127.0.0.1
      port:  4561
  - name: B
    fsw:
      tlm:
        port: 5031
      cmd:
        ip:   127.0.0.1
        port: 5030
    gnd:
      tlm:
        ip:   127.0.0.1
        port: 5211
      cmd: 
        port: 5210
    sim:
      ip:    127.0.0.1
      port:  4562
sim:
  ip: 127.0.0.1
  port: 4560
gnd:
  tlm:
    ip: 127.0.0.1
    port: 5011
  cmd:
    port: 5010