/* This file was autogenerated from template version 0.0.0.2 and autogenerator version 0.0.0.1 */

#include "gps_serialization.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 GPS_HkTlm_t_Enc(const GPS_HkTlm_t *inObject, char *inOutBuffer, uint32 inSize)
{
	bool status = false;
	pb_ostream_t stream;

	gps_hk_pb pbMsg;

    pbMsg.usCmdCnt = inObject->usCmdCnt;
    pbMsg.usCmdErrCnt = inObject->usCmdErrCnt;
    pbMsg.VehicleGpsMsg.FixType = inObject->VehicleGpsMsg.FixType;
    pbMsg.VehicleGpsMsg.SatellitesUsed = inObject->VehicleGpsMsg.SatellitesUsed;
    pbMsg.VehicleGpsMsg.Lon = inObject->VehicleGpsMsg.Lon;
    pbMsg.VehicleGpsMsg.Vel_d_m_s = inObject->VehicleGpsMsg.Vel_d_m_s;
    pbMsg.VehicleGpsMsg.COG = inObject->VehicleGpsMsg.COG;
    pbMsg.VehicleGpsMsg.SVariance = inObject->VehicleGpsMsg.SVariance;
    pbMsg.VehicleGpsMsg.JammingIndicator = inObject->VehicleGpsMsg.JammingIndicator;
    pbMsg.VehicleGpsMsg.Timestamp = inObject->VehicleGpsMsg.Timestamp;
    pbMsg.VehicleGpsMsg.VelNedValid = inObject->VehicleGpsMsg.VelNedValid;
    pbMsg.VehicleGpsMsg.Lat = inObject->VehicleGpsMsg.Lat;
    pbMsg.VehicleGpsMsg.VDOP = inObject->VehicleGpsMsg.VDOP;
    pbMsg.VehicleGpsMsg.HDOP = inObject->VehicleGpsMsg.HDOP;
    pbMsg.VehicleGpsMsg.TimestampTimeRelative = inObject->VehicleGpsMsg.TimestampTimeRelative;
    pbMsg.VehicleGpsMsg.CVariance = inObject->VehicleGpsMsg.CVariance;
    pbMsg.VehicleGpsMsg.TimeUtcUsec = inObject->VehicleGpsMsg.TimeUtcUsec;
    pbMsg.VehicleGpsMsg.AltEllipsoid = inObject->VehicleGpsMsg.AltEllipsoid;
    pbMsg.VehicleGpsMsg.NoisePerMs = inObject->VehicleGpsMsg.NoisePerMs;
    pbMsg.VehicleGpsMsg.EpV = inObject->VehicleGpsMsg.EpV;
    pbMsg.VehicleGpsMsg.Vel_n_m_s = inObject->VehicleGpsMsg.Vel_n_m_s;
    pbMsg.VehicleGpsMsg.Vel_m_s = inObject->VehicleGpsMsg.Vel_m_s;
    pbMsg.VehicleGpsMsg.EpH = inObject->VehicleGpsMsg.EpH;
    pbMsg.VehicleGpsMsg.Alt = inObject->VehicleGpsMsg.Alt;
    pbMsg.VehicleGpsMsg.Vel_e_m_s = inObject->VehicleGpsMsg.Vel_e_m_s;

	/* Create a stream that will write to our buffer. */
	stream = pb_ostream_from_buffer((pb_byte_t *)inOutBuffer, inSize);
	
	/* Now we are ready to encode the message. */
	status = pb_encode(&stream, gps_hk_pb_fields, &pbMsg);

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error encoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

	return stream.bytes_written;
}

uint32 GPS_HkTlm_t_Dec(const char *inBuffer, uint32 inSize, GPS_HkTlm_t *inOutObject)
{
	bool status = false;
	pb_istream_t stream;

	gps_hk_pb pbMsg;

    /* Create a stream that reads from the buffer. */
	stream = pb_istream_from_buffer((const pb_byte_t *)inBuffer, inSize);

	/* Now we are ready to decode the message. */
	status = pb_decode(&stream, gps_hk_pb_fields, &pbMsg); 

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error decoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

    inOutObject->usCmdCnt = pbMsg.usCmdCnt;
    inOutObject->usCmdErrCnt = pbMsg.usCmdErrCnt;
    inOutObject->VehicleGpsMsg.FixType = pbMsg.VehicleGpsMsg.FixType;
    inOutObject->VehicleGpsMsg.SatellitesUsed = pbMsg.VehicleGpsMsg.SatellitesUsed;
    inOutObject->VehicleGpsMsg.Lon = pbMsg.VehicleGpsMsg.Lon;
    inOutObject->VehicleGpsMsg.Vel_d_m_s = pbMsg.VehicleGpsMsg.Vel_d_m_s;
    inOutObject->VehicleGpsMsg.COG = pbMsg.VehicleGpsMsg.COG;
    inOutObject->VehicleGpsMsg.SVariance = pbMsg.VehicleGpsMsg.SVariance;
    inOutObject->VehicleGpsMsg.JammingIndicator = pbMsg.VehicleGpsMsg.JammingIndicator;
    inOutObject->VehicleGpsMsg.Timestamp = pbMsg.VehicleGpsMsg.Timestamp;
    inOutObject->VehicleGpsMsg.VelNedValid = pbMsg.VehicleGpsMsg.VelNedValid;
    inOutObject->VehicleGpsMsg.Lat = pbMsg.VehicleGpsMsg.Lat;
    inOutObject->VehicleGpsMsg.VDOP = pbMsg.VehicleGpsMsg.VDOP;
    inOutObject->VehicleGpsMsg.HDOP = pbMsg.VehicleGpsMsg.HDOP;
    inOutObject->VehicleGpsMsg.TimestampTimeRelative = pbMsg.VehicleGpsMsg.TimestampTimeRelative;
    inOutObject->VehicleGpsMsg.CVariance = pbMsg.VehicleGpsMsg.CVariance;
    inOutObject->VehicleGpsMsg.TimeUtcUsec = pbMsg.VehicleGpsMsg.TimeUtcUsec;
    inOutObject->VehicleGpsMsg.AltEllipsoid = pbMsg.VehicleGpsMsg.AltEllipsoid;
    inOutObject->VehicleGpsMsg.NoisePerMs = pbMsg.VehicleGpsMsg.NoisePerMs;
    inOutObject->VehicleGpsMsg.EpV = pbMsg.VehicleGpsMsg.EpV;
    inOutObject->VehicleGpsMsg.Vel_n_m_s = pbMsg.VehicleGpsMsg.Vel_n_m_s;
    inOutObject->VehicleGpsMsg.Vel_m_s = pbMsg.VehicleGpsMsg.Vel_m_s;
    inOutObject->VehicleGpsMsg.EpH = pbMsg.VehicleGpsMsg.EpH;
    inOutObject->VehicleGpsMsg.Alt = pbMsg.VehicleGpsMsg.Alt;
    inOutObject->VehicleGpsMsg.Vel_e_m_s = pbMsg.VehicleGpsMsg.Vel_e_m_s;

	return sizeof(GPS_HkTlm_t);
}


#ifdef __cplusplus
} /* extern "C" */
#endif
