/* This file was autogenerated from template version 0.0.0.2 and autogenerator version 0.0.0.1 */

#include "sens_serialization.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 SENS_HkTlm_t_Enc(const SENS_HkTlm_t *inObject, char *inOutBuffer, uint32 inSize)
{
	bool status = false;
	pb_ostream_t stream;

	sens_hk_pb pbMsg;

    pbMsg.usCmdCnt = inObject->usCmdCnt;
    pbMsg.usCmdErrCnt = inObject->usCmdErrCnt;
    /* Unroll indexes */
    pbMsg.SensorCombinedMsg.Acc_count = 3;
    pbMsg.SensorCombinedMsg.Acc[0] = inObject->SensorCombinedMsg.Acc[0];
    pbMsg.SensorCombinedMsg.Acc[1] = inObject->SensorCombinedMsg.Acc[1];
    pbMsg.SensorCombinedMsg.Acc[2] = inObject->SensorCombinedMsg.Acc[2];
    pbMsg.SensorCombinedMsg.MagTimestampRelative = inObject->SensorCombinedMsg.MagTimestampRelative;
    pbMsg.SensorCombinedMsg.GyroIntegralDt = inObject->SensorCombinedMsg.GyroIntegralDt;
    pbMsg.SensorCombinedMsg.AccTimestampRelative = inObject->SensorCombinedMsg.AccTimestampRelative;
    pbMsg.SensorCombinedMsg.BaroRelTimeInvalid = inObject->SensorCombinedMsg.BaroRelTimeInvalid;
    pbMsg.SensorCombinedMsg.AccIntegralDt = inObject->SensorCombinedMsg.AccIntegralDt;
    pbMsg.SensorCombinedMsg.BaroAlt = inObject->SensorCombinedMsg.BaroAlt;
    /* Unroll indexes */
    pbMsg.SensorCombinedMsg.Mag_count = 3;
    pbMsg.SensorCombinedMsg.Mag[0] = inObject->SensorCombinedMsg.Mag[0];
    pbMsg.SensorCombinedMsg.Mag[1] = inObject->SensorCombinedMsg.Mag[1];
    pbMsg.SensorCombinedMsg.Mag[2] = inObject->SensorCombinedMsg.Mag[2];
    pbMsg.SensorCombinedMsg.Timestamp = inObject->SensorCombinedMsg.Timestamp;
    /* Unroll indexes */
    pbMsg.SensorCombinedMsg.GyroRad_count = 3;
    pbMsg.SensorCombinedMsg.GyroRad[0] = inObject->SensorCombinedMsg.GyroRad[0];
    pbMsg.SensorCombinedMsg.GyroRad[1] = inObject->SensorCombinedMsg.GyroRad[1];
    pbMsg.SensorCombinedMsg.GyroRad[2] = inObject->SensorCombinedMsg.GyroRad[2];
    pbMsg.SensorCombinedMsg.MagRelTimeInvalid = inObject->SensorCombinedMsg.MagRelTimeInvalid;
    pbMsg.SensorCombinedMsg.BaroTemp = inObject->SensorCombinedMsg.BaroTemp;
    pbMsg.SensorCombinedMsg.BaroTimestampRelative = inObject->SensorCombinedMsg.BaroTimestampRelative;

	/* Create a stream that will write to our buffer. */
	stream = pb_ostream_from_buffer((pb_byte_t *)inOutBuffer, inSize);
	
	/* Now we are ready to encode the message. */
	status = pb_encode(&stream, sens_hk_pb_fields, &pbMsg);

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error encoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

	return stream.bytes_written;
}

uint32 SENS_HkTlm_t_Dec(const char *inBuffer, uint32 inSize, SENS_HkTlm_t *inOutObject)
{
	bool status = false;
	pb_istream_t stream;

	sens_hk_pb pbMsg;

    /* Create a stream that reads from the buffer. */
	stream = pb_istream_from_buffer((const pb_byte_t *)inBuffer, inSize);

	/* Now we are ready to decode the message. */
	status = pb_decode(&stream, sens_hk_pb_fields, &pbMsg); 

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error decoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

    inOutObject->usCmdCnt = pbMsg.usCmdCnt;
    inOutObject->usCmdErrCnt = pbMsg.usCmdErrCnt;
    /* Unroll indexes */
    inOutObject->SensorCombinedMsg.Acc[0] = pbMsg.SensorCombinedMsg.Acc[0];
    inOutObject->SensorCombinedMsg.Acc[1] = pbMsg.SensorCombinedMsg.Acc[1];
    inOutObject->SensorCombinedMsg.Acc[2] = pbMsg.SensorCombinedMsg.Acc[2];
    inOutObject->SensorCombinedMsg.MagTimestampRelative = pbMsg.SensorCombinedMsg.MagTimestampRelative;
    inOutObject->SensorCombinedMsg.GyroIntegralDt = pbMsg.SensorCombinedMsg.GyroIntegralDt;
    inOutObject->SensorCombinedMsg.AccTimestampRelative = pbMsg.SensorCombinedMsg.AccTimestampRelative;
    inOutObject->SensorCombinedMsg.BaroRelTimeInvalid = pbMsg.SensorCombinedMsg.BaroRelTimeInvalid;
    inOutObject->SensorCombinedMsg.AccIntegralDt = pbMsg.SensorCombinedMsg.AccIntegralDt;
    inOutObject->SensorCombinedMsg.BaroAlt = pbMsg.SensorCombinedMsg.BaroAlt;
    /* Unroll indexes */
    inOutObject->SensorCombinedMsg.Mag[0] = pbMsg.SensorCombinedMsg.Mag[0];
    inOutObject->SensorCombinedMsg.Mag[1] = pbMsg.SensorCombinedMsg.Mag[1];
    inOutObject->SensorCombinedMsg.Mag[2] = pbMsg.SensorCombinedMsg.Mag[2];
    inOutObject->SensorCombinedMsg.Timestamp = pbMsg.SensorCombinedMsg.Timestamp;
    /* Unroll indexes */
    inOutObject->SensorCombinedMsg.GyroRad[0] = pbMsg.SensorCombinedMsg.GyroRad[0];
    inOutObject->SensorCombinedMsg.GyroRad[1] = pbMsg.SensorCombinedMsg.GyroRad[1];
    inOutObject->SensorCombinedMsg.GyroRad[2] = pbMsg.SensorCombinedMsg.GyroRad[2];
    inOutObject->SensorCombinedMsg.MagRelTimeInvalid = pbMsg.SensorCombinedMsg.MagRelTimeInvalid;
    inOutObject->SensorCombinedMsg.BaroTemp = pbMsg.SensorCombinedMsg.BaroTemp;
    inOutObject->SensorCombinedMsg.BaroTimestampRelative = pbMsg.SensorCombinedMsg.BaroTimestampRelative;

	return sizeof(SENS_HkTlm_t);
}


#ifdef __cplusplus
} /* extern "C" */
#endif
