/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:08 2016. */

#ifndef PB_COMMANDER_STATE_PB_H_INCLUDED
#define PB_COMMANDER_STATE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_commander_state_pb_MAIN_STATE {
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_MANUAL = 0,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_ALTCTL = 1,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_POSCTL = 2,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_AUTO_MISSION = 3,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_AUTO_LOITER = 4,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_AUTO_RTL = 5,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_ACRO = 6,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_OFFBOARD = 7,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_STAB = 8,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_RATTITUDE = 9,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_AUTO_TAKEOFF = 10,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_AUTO_LAND = 11,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_AUTO_FOLLOW_TARGET = 12,
    px4_commander_state_pb_MAIN_STATE_MAIN_STATE_MAX = 13
} px4_commander_state_pb_MAIN_STATE;
#define _px4_commander_state_pb_MAIN_STATE_MIN px4_commander_state_pb_MAIN_STATE_MAIN_STATE_MANUAL
#define _px4_commander_state_pb_MAIN_STATE_MAX px4_commander_state_pb_MAIN_STATE_MAIN_STATE_MAX
#define _px4_commander_state_pb_MAIN_STATE_ARRAYSIZE ((px4_commander_state_pb_MAIN_STATE)(px4_commander_state_pb_MAIN_STATE_MAIN_STATE_MAX+1))

/* Struct definitions */
typedef struct _px4_commander_state_pb {
    uint64_t timestamp;
    uint32_t main_state;
/* @@protoc_insertion_point(struct:px4_commander_state_pb) */
} px4_commander_state_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_commander_state_pb_init_default      {0, 0}
#define px4_commander_state_pb_init_zero         {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_commander_state_pb_timestamp_tag     1
#define px4_commander_state_pb_main_state_tag    2

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_commander_state_pb_fields[3];

/* Maximum encoded size of messages (where known) */
#define px4_commander_state_pb_size              17

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define COMMANDER_STATE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
