/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:08 2016. */

#include "control_state.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_control_state_pb_fields[20] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_control_state_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, x_acc, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, y_acc, x_acc, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, z_acc, y_acc, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, x_vel, z_acc, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, y_vel, x_vel, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, z_vel, y_vel, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, x_pos, z_vel, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, y_pos, x_pos, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, z_pos, y_pos, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, airspeed, z_pos, 0),
    PB_FIELD( 12, FLOAT   , REPEATED, STATIC  , OTHER, px4_control_state_pb, vel_variance, airspeed, 0),
    PB_FIELD( 13, FLOAT   , REPEATED, STATIC  , OTHER, px4_control_state_pb, pos_variance, vel_variance, 0),
    PB_FIELD( 14, FLOAT   , REPEATED, STATIC  , OTHER, px4_control_state_pb, q, pos_variance, 0),
    PB_FIELD( 15, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, roll_rate, q, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, pitch_rate, roll_rate, 0),
    PB_FIELD( 17, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, yaw_rate, pitch_rate, 0),
    PB_FIELD( 18, FLOAT   , REQUIRED, STATIC  , OTHER, px4_control_state_pb, horz_acc_mag, yaw_rate, 0),
    PB_FIELD( 19, BOOL    , REQUIRED, STATIC  , OTHER, px4_control_state_pb, airspeed_valid, horz_acc_mag, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
