/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Oct 29 18:11:51 2016. */

#include "debug_key_value.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_debug_key_value_pb_fields[5] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_debug_key_value_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, px4_debug_key_value_pb, timestamp_ms, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_debug_key_value_pb, value, timestamp_ms, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, px4_debug_key_value_pb, key, value, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
