/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:09 2016. */

#ifndef PB_DISTANCE_SENSOR_PB_H_INCLUDED
#define PB_DISTANCE_SENSOR_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_distance_sensor_pb_MAV_DISTANCE_SENSOR {
    px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAV_DISTANCE_SENSOR_LASER = 0,
    px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAV_DISTANCE_SENSOR_ULTRASOUND = 1,
    px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAV_DISTANCE_SENSOR_INFRARED = 2
} px4_distance_sensor_pb_MAV_DISTANCE_SENSOR;
#define _px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MIN px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAV_DISTANCE_SENSOR_LASER
#define _px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAX px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAV_DISTANCE_SENSOR_INFRARED
#define _px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_ARRAYSIZE ((px4_distance_sensor_pb_MAV_DISTANCE_SENSOR)(px4_distance_sensor_pb_MAV_DISTANCE_SENSOR_MAV_DISTANCE_SENSOR_INFRARED+1))

/* Struct definitions */
typedef struct _px4_distance_sensor_pb {
    uint64_t timestamp;
    float min_distance;
    float max_distance;
    float current_distance;
    float covariance;
    uint32_t type;
    uint32_t id;
    uint32_t orientation;
/* @@protoc_insertion_point(struct:px4_distance_sensor_pb) */
} px4_distance_sensor_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_distance_sensor_pb_init_default      {0, 0, 0, 0, 0, 0, 0, 0}
#define px4_distance_sensor_pb_init_zero         {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_distance_sensor_pb_timestamp_tag     1
#define px4_distance_sensor_pb_min_distance_tag  2
#define px4_distance_sensor_pb_max_distance_tag  3
#define px4_distance_sensor_pb_current_distance_tag 4
#define px4_distance_sensor_pb_covariance_tag    5
#define px4_distance_sensor_pb_type_tag          6
#define px4_distance_sensor_pb_id_tag            7
#define px4_distance_sensor_pb_orientation_tag   8

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_distance_sensor_pb_fields[9];

/* Maximum encoded size of messages (where known) */
#define px4_distance_sensor_pb_size              49

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DISTANCE_SENSOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
