/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:09 2016. */

#include "distance_sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_distance_sensor_pb_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_distance_sensor_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, min_distance, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, max_distance, min_distance, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, current_distance, max_distance, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, covariance, current_distance, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, type, covariance, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, id, type, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, px4_distance_sensor_pb, orientation, id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
