/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:09 2016. */

#include "ekf2_innovations.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_ekf2_innovations_pb_fields[14] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_ekf2_innovations_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_innovations_pb, vel_pos_innov, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_innovations_pb, mag_innov, vel_pos_innov, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_innovations_pb, heading_innov, mag_innov, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_innovations_pb, airspeed_innov, heading_innov, 0),
    PB_FIELD(  6, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_innovations_pb, flow_innov, airspeed_innov, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_innovations_pb, hagl_innov, flow_innov, 0),
    PB_FIELD(  8, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_innovations_pb, vel_pos_innov_var, hagl_innov, 0),
    PB_FIELD(  9, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_innovations_pb, mag_innov_var, vel_pos_innov_var, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_innovations_pb, heading_innov_var, mag_innov_var, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_innovations_pb, airspeed_innov_var, heading_innov_var, 0),
    PB_FIELD( 12, FLOAT   , REPEATED, STATIC  , OTHER, px4_ekf2_innovations_pb, flow_innov_var, airspeed_innov_var, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, px4_ekf2_innovations_pb, hagl_innov_var, flow_innov_var, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
