/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:11 2016. */

#ifndef PB_FENCE_PB_H_INCLUDED
#define PB_FENCE_PB_H_INCLUDED
#include <pb.h>

#include "fence_vertex.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_fence_pb_FENCE {
    px4_fence_pb_FENCE_GEOFENCE_MAX_VERTICES = 16
} px4_fence_pb_FENCE;
#define _px4_fence_pb_FENCE_MIN px4_fence_pb_FENCE_GEOFENCE_MAX_VERTICES
#define _px4_fence_pb_FENCE_MAX px4_fence_pb_FENCE_GEOFENCE_MAX_VERTICES
#define _px4_fence_pb_FENCE_ARRAYSIZE ((px4_fence_pb_FENCE)(px4_fence_pb_FENCE_GEOFENCE_MAX_VERTICES+1))

/* Struct definitions */
typedef struct _px4_fence_pb {
    uint64_t timestamp;
    uint32_t count;
    pb_size_t vertices_count;
    px4_fence_vertex_pb vertices[16];
/* @@protoc_insertion_point(struct:px4_fence_pb) */
} px4_fence_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_fence_pb_init_default                {0, 0, 0, {px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default, px4_fence_vertex_pb_init_default}}
#define px4_fence_pb_init_zero                   {0, 0, 0, {px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero, px4_fence_vertex_pb_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define px4_fence_pb_timestamp_tag               1
#define px4_fence_pb_count_tag                   2
#define px4_fence_pb_vertices_tag                3

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_fence_pb_fields[4];

/* Maximum encoded size of messages (where known) */
#define px4_fence_pb_size                        (113 + 16*px4_fence_vertex_pb_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FENCE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
