/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:12 2016. */

#ifndef PB_HOME_POSITION_PB_H_INCLUDED
#define PB_HOME_POSITION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_home_position_pb {
    uint64_t timestamp;
    double lat;
    double lon;
    float alt;
    float x;
    float y;
    float z;
    float yaw;
    float direction_x;
    float direction_y;
    float direction_z;
/* @@protoc_insertion_point(struct:px4_home_position_pb) */
} px4_home_position_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_home_position_pb_init_default        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define px4_home_position_pb_init_zero           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_home_position_pb_timestamp_tag       1
#define px4_home_position_pb_lat_tag             2
#define px4_home_position_pb_lon_tag             3
#define px4_home_position_pb_alt_tag             4
#define px4_home_position_pb_x_tag               5
#define px4_home_position_pb_y_tag               6
#define px4_home_position_pb_z_tag               7
#define px4_home_position_pb_yaw_tag             8
#define px4_home_position_pb_direction_x_tag     9
#define px4_home_position_pb_direction_y_tag     10
#define px4_home_position_pb_direction_z_tag     11

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_home_position_pb_fields[12];

/* Maximum encoded size of messages (where known) */
#define px4_home_position_pb_size                69

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define HOME_POSITION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
