/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:14 2016. */

#ifndef PB_MISSION_PB_H_INCLUDED
#define PB_MISSION_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_mission_pb {
    uint64_t timestamp;
    int32_t dataman_id;
    uint32_t count;
    int32_t current_seq;
/* @@protoc_insertion_point(struct:px4_mission_pb) */
} px4_mission_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_mission_pb_init_default              {0, 0, 0, 0}
#define px4_mission_pb_init_zero                 {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_mission_pb_timestamp_tag             1
#define px4_mission_pb_dataman_id_tag            2
#define px4_mission_pb_count_tag                 3
#define px4_mission_pb_current_seq_tag           4

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_mission_pb_fields[5];

/* Maximum encoded size of messages (where known) */
#define px4_mission_pb_size                      39

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MISSION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
