/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:15 2016. */

#ifndef PB_OPTICAL_FLOW_PB_H_INCLUDED
#define PB_OPTICAL_FLOW_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_optical_flow_pb {
    uint64_t timestamp;
    float pixel_flow_x_integral;
    float pixel_flow_y_integral;
    float gyro_x_rate_integral;
    float gyro_y_rate_integral;
    float gyro_z_rate_integral;
    float ground_distance_m;
    uint32_t integration_timespan;
    uint32_t time_since_last_sonar_update;
    uint32_t frame_count_since_last_readout;
    int32_t gyro_temperature;
    uint32_t sensor_id;
    uint32_t quality;
/* @@protoc_insertion_point(struct:px4_optical_flow_pb) */
} px4_optical_flow_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_optical_flow_pb_init_default         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define px4_optical_flow_pb_init_zero            {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_optical_flow_pb_timestamp_tag        1
#define px4_optical_flow_pb_pixel_flow_x_integral_tag 2
#define px4_optical_flow_pb_pixel_flow_y_integral_tag 3
#define px4_optical_flow_pb_gyro_x_rate_integral_tag 4
#define px4_optical_flow_pb_gyro_y_rate_integral_tag 5
#define px4_optical_flow_pb_gyro_z_rate_integral_tag 6
#define px4_optical_flow_pb_ground_distance_m_tag 7
#define px4_optical_flow_pb_integration_timespan_tag 8
#define px4_optical_flow_pb_time_since_last_sonar_update_tag 9
#define px4_optical_flow_pb_frame_count_since_last_readout_tag 10
#define px4_optical_flow_pb_gyro_temperature_tag 11
#define px4_optical_flow_pb_sensor_id_tag        12
#define px4_optical_flow_pb_quality_tag          13

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_optical_flow_pb_fields[14];

/* Maximum encoded size of messages (where known) */
#define px4_optical_flow_pb_size                 82

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define OPTICAL_FLOW_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
