/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:15 2016. */

#include "rc_channels.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_rc_channels_pb_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_rc_channels_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_rc_channels_pb, timestamp_last_valid, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, px4_rc_channels_pb, channels, timestamp_last_valid, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, px4_rc_channels_pb, frame_drop_count, channels, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, px4_rc_channels_pb, channel_count, frame_drop_count, 0),
    PB_FIELD(  6, INT32   , REPEATED, STATIC  , OTHER, px4_rc_channels_pb, function, channel_count, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, px4_rc_channels_pb, rssi, function, 0),
    PB_FIELD(  8, BOOL    , REQUIRED, STATIC  , OTHER, px4_rc_channels_pb, signal_lost, rssi, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
