/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Oct 29 18:16:28 2016. */

#include "rc_parameter_map.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_rc_parameter_map_pb_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_rc_parameter_map_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, INT32   , REPEATED, STATIC  , OTHER, px4_rc_parameter_map_pb, param_index, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REPEATED, STATIC  , OTHER, px4_rc_parameter_map_pb, scale, param_index, 0),
    PB_FIELD(  4, FLOAT   , REPEATED, STATIC  , OTHER, px4_rc_parameter_map_pb, value0, scale, 0),
    PB_FIELD(  5, FLOAT   , REPEATED, STATIC  , OTHER, px4_rc_parameter_map_pb, value_min, value0, 0),
    PB_FIELD(  6, FLOAT   , REPEATED, STATIC  , OTHER, px4_rc_parameter_map_pb, value_max, value_min, 0),
    PB_FIELD(  7, BOOL    , REPEATED, STATIC  , OTHER, px4_rc_parameter_map_pb, valid, value_max, 0),
    PB_FIELD(  8, STRING  , REQUIRED, STATIC  , OTHER, px4_rc_parameter_map_pb, param_id, valid, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
