/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:16 2016. */

#include "satellite_info.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_satellite_info_pb_fields[8] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_satellite_info_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, px4_satellite_info_pb, count, timestamp, 0),
    PB_FIELD(  3, UINT32  , REPEATED, STATIC  , OTHER, px4_satellite_info_pb, svid, count, 0),
    PB_FIELD(  4, UINT32  , REPEATED, STATIC  , OTHER, px4_satellite_info_pb, used, svid, 0),
    PB_FIELD(  5, UINT32  , REPEATED, STATIC  , OTHER, px4_satellite_info_pb, elevation, used, 0),
    PB_FIELD(  6, UINT32  , REPEATED, STATIC  , OTHER, px4_satellite_info_pb, azimuth, elevation, 0),
    PB_FIELD(  7, UINT32  , REPEATED, STATIC  , OTHER, px4_satellite_info_pb, snr, azimuth, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
