/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:16 2016. */

#include "telemetry_status.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_telemetry_status_pb_fields[14] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_telemetry_status_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, heartbeat_time, timestamp, 0),
    PB_FIELD(  3, UINT64  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, telem_time, heartbeat_time, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, rxerrors, telem_time, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, fixed, rxerrors, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, type, fixed, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, rssi, type, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, remote_rssi, rssi, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, noise, remote_rssi, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, remote_noise, noise, 0),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, txbuf, remote_noise, 0),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, system_id, txbuf, 0),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, px4_telemetry_status_pb, component_id, system_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
