/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Sat Oct 29 18:21:26 2016. */

#ifndef PB_UAVCAN_PARAMETER_VALUE_PB_H_INCLUDED
#define PB_UAVCAN_PARAMETER_VALUE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_uavcan_parameter_value_pb {
    uint64_t timestamp;
    int64_t int_value;
    float real_value;
    int32_t param_index;
    uint32_t param_count;
    uint32_t node_id;
    char param_id[17];
    uint32_t param_type;
/* @@protoc_insertion_point(struct:px4_uavcan_parameter_value_pb) */
} px4_uavcan_parameter_value_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_uavcan_parameter_value_pb_init_default {0, 0, 0, 0, 0, 0, "", 0}
#define px4_uavcan_parameter_value_pb_init_zero  {0, 0, 0, 0, 0, 0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_uavcan_parameter_value_pb_timestamp_tag 1
#define px4_uavcan_parameter_value_pb_int_value_tag 2
#define px4_uavcan_parameter_value_pb_real_value_tag 3
#define px4_uavcan_parameter_value_pb_param_index_tag 4
#define px4_uavcan_parameter_value_pb_param_count_tag 5
#define px4_uavcan_parameter_value_pb_node_id_tag 6
#define px4_uavcan_parameter_value_pb_param_id_tag 7
#define px4_uavcan_parameter_value_pb_param_type_tag 8

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_uavcan_parameter_value_pb_fields[9];

/* Maximum encoded size of messages (where known) */
#define px4_uavcan_parameter_value_pb_size       75

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define UAVCAN_PARAMETER_VALUE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
