/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Sat Oct 29 18:19:03 2016. */

#include "uavcan_parameter_request.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_uavcan_parameter_request_pb_fields[9] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_uavcan_parameter_request_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, INT64   , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, int_value, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, real_value, int_value, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, param_index, real_value, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, message_type, param_index, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, node_id, message_type, 0),
    PB_FIELD(  7, STRING  , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, param_id, node_id, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, px4_uavcan_parameter_request_pb, param_type, param_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
