/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_attitude.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_attitude_pb_fields[20] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_attitude_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, roll, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, pitch, roll, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, yaw, pitch, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, rollspeed, yaw, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, pitchspeed, rollspeed, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, yawspeed, pitchspeed, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, rollacc, yawspeed, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, pitchacc, rollacc, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, yawacc, pitchacc, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, rate_vibration, yawacc, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, accel_vibration, rate_vibration, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, mag_vibration, accel_vibration, 0),
    PB_FIELD( 14, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_pb, rate_offsets, mag_vibration, 0),
    PB_FIELD( 15, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_pb, R, rate_offsets, 0),
    PB_FIELD( 16, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_pb, q, R, 0),
    PB_FIELD( 17, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_pb, g_comp, q, 0),
    PB_FIELD( 18, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, R_valid, g_comp, 0),
    PB_FIELD( 19, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_pb, q_valid, R_valid, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
