/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#ifndef PB_VEHICLE_LOCAL_POSITION_SETPOINT_PB_H_INCLUDED
#define PB_VEHICLE_LOCAL_POSITION_SETPOINT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_vehicle_local_position_setpoint_pb {
    uint64_t timestamp;
    float x;
    float y;
    float z;
    float yaw;
    float vx;
    float vy;
    float vz;
    float acc_x;
    float acc_y;
    float acc_z;
/* @@protoc_insertion_point(struct:px4_vehicle_local_position_setpoint_pb) */
} px4_vehicle_local_position_setpoint_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_vehicle_local_position_setpoint_pb_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define px4_vehicle_local_position_setpoint_pb_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_vehicle_local_position_setpoint_pb_timestamp_tag 1
#define px4_vehicle_local_position_setpoint_pb_x_tag 2
#define px4_vehicle_local_position_setpoint_pb_y_tag 3
#define px4_vehicle_local_position_setpoint_pb_z_tag 4
#define px4_vehicle_local_position_setpoint_pb_yaw_tag 5
#define px4_vehicle_local_position_setpoint_pb_vx_tag 6
#define px4_vehicle_local_position_setpoint_pb_vy_tag 7
#define px4_vehicle_local_position_setpoint_pb_vz_tag 8
#define px4_vehicle_local_position_setpoint_pb_acc_x_tag 9
#define px4_vehicle_local_position_setpoint_pb_acc_y_tag 10
#define px4_vehicle_local_position_setpoint_pb_acc_z_tag 11

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_vehicle_local_position_setpoint_pb_fields[12];

/* Maximum encoded size of messages (where known) */
#define px4_vehicle_local_position_setpoint_pb_size 61

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define VEHICLE_LOCAL_POSITION_SETPOINT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
