/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_control_mode.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_control_mode_pb_fields[18] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_control_mode_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_armed, timestamp, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_external_manual_override_ok, flag_armed, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_system_hil_enabled, flag_external_manual_override_ok, 0),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_manual_enabled, flag_system_hil_enabled, 0),
    PB_FIELD(  6, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_auto_enabled, flag_control_manual_enabled, 0),
    PB_FIELD(  7, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_offboard_enabled, flag_control_auto_enabled, 0),
    PB_FIELD(  8, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_rates_enabled, flag_control_offboard_enabled, 0),
    PB_FIELD(  9, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_attitude_enabled, flag_control_rates_enabled, 0),
    PB_FIELD( 10, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_rattitude_enabled, flag_control_attitude_enabled, 0),
    PB_FIELD( 11, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_force_enabled, flag_control_rattitude_enabled, 0),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_acceleration_enabled, flag_control_force_enabled, 0),
    PB_FIELD( 13, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_velocity_enabled, flag_control_acceleration_enabled, 0),
    PB_FIELD( 14, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_position_enabled, flag_control_velocity_enabled, 0),
    PB_FIELD( 15, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_altitude_enabled, flag_control_position_enabled, 0),
    PB_FIELD( 16, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_climb_rate_enabled, flag_control_altitude_enabled, 0),
    PB_FIELD( 17, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_control_mode_pb, flag_control_termination_enabled, flag_control_climb_rate_enabled, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
