/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#ifndef PB_VEHICLE_COMMAND_ACK_PB_H_INCLUDED
#define PB_VEHICLE_COMMAND_ACK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _px4_vehicle_command_ack_pb_VEHICLE_RESULT {
    px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_ACCEPTED = 0,
    px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_TEMPORARILY_REJECTED = 1,
    px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_DENIED = 2,
    px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_UNSUPPORTED = 3,
    px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_FAILED = 4
} px4_vehicle_command_ack_pb_VEHICLE_RESULT;
#define _px4_vehicle_command_ack_pb_VEHICLE_RESULT_MIN px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_ACCEPTED
#define _px4_vehicle_command_ack_pb_VEHICLE_RESULT_MAX px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_FAILED
#define _px4_vehicle_command_ack_pb_VEHICLE_RESULT_ARRAYSIZE ((px4_vehicle_command_ack_pb_VEHICLE_RESULT)(px4_vehicle_command_ack_pb_VEHICLE_RESULT_VEHICLE_RESULT_FAILED+1))

/* Struct definitions */
typedef struct _px4_vehicle_command_ack_pb {
    uint64_t timestamp;
    uint32_t command;
    uint32_t result;
/* @@protoc_insertion_point(struct:px4_vehicle_command_ack_pb) */
} px4_vehicle_command_ack_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_vehicle_command_ack_pb_init_default  {0, 0, 0}
#define px4_vehicle_command_ack_pb_init_zero     {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_vehicle_command_ack_pb_timestamp_tag 1
#define px4_vehicle_command_ack_pb_command_tag   2
#define px4_vehicle_command_ack_pb_result_tag    3

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_vehicle_command_ack_pb_fields[4];

/* Maximum encoded size of messages (where known) */
#define px4_vehicle_command_ack_pb_size          23

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define VEHICLE_COMMAND_ACK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
