/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_gps_position.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_gps_position_pb_fields[24] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_gps_position_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT64  , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, time_utc_usec, timestamp, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, lat, time_utc_usec, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, lon, lat, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, alt, lon, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, alt_ellipsoid, alt, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, s_variance_m_s, alt_ellipsoid, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, c_variance_rad, s_variance_m_s, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, eph, c_variance_rad, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, epv, eph, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, hdop, epv, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, vdop, hdop, 0),
    PB_FIELD( 13, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, noise_per_ms, vdop, 0),
    PB_FIELD( 14, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, jamming_indicator, noise_per_ms, 0),
    PB_FIELD( 15, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, vel_m_s, jamming_indicator, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, vel_n_m_s, vel_m_s, 0),
    PB_FIELD( 17, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, vel_e_m_s, vel_n_m_s, 0),
    PB_FIELD( 18, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, vel_d_m_s, vel_e_m_s, 0),
    PB_FIELD( 19, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, cog_rad, vel_d_m_s, 0),
    PB_FIELD( 20, INT32   , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, timestamp_time_relative, cog_rad, 0),
    PB_FIELD( 21, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, fix_type, timestamp_time_relative, 0),
    PB_FIELD( 22, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, vel_ned_valid, fix_type, 0),
    PB_FIELD( 23, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_gps_position_pb, satellites_used, vel_ned_valid, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
