/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_command.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_command_pb_fields[15] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_command_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, DOUBLE  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param5, timestamp, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param6, param5, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param1, param6, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param2, param1, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param3, param2, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param4, param3, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, param7, param4, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, command, param7, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, target_system, command, 0),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, target_component, target_system, 0),
    PB_FIELD( 12, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, source_system, target_component, 0),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, source_component, source_system, 0),
    PB_FIELD( 14, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_command_pb, confirmation, source_component, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
