/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:17 2016. */

#include "vehicle_attitude_setpoint.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_attitude_setpoint_pb_fields[19] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_attitude_setpoint_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, roll_body, timestamp, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, pitch_body, roll_body, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, yaw_body, pitch_body, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, yaw_sp_move_rate, yaw_body, 0),
    PB_FIELD(  6, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, R_body, yaw_sp_move_rate, 0),
    PB_FIELD(  7, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, q_d, R_body, 0),
    PB_FIELD(  8, FLOAT   , REPEATED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, q_e, q_d, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, thrust, q_e, 0),
    PB_FIELD( 10, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, R_valid, thrust, 0),
    PB_FIELD( 11, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, q_d_valid, R_valid, 0),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, q_e_valid, q_d_valid, 0),
    PB_FIELD( 13, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, roll_reset_integral, q_e_valid, 0),
    PB_FIELD( 14, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, pitch_reset_integral, roll_reset_integral, 0),
    PB_FIELD( 15, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, yaw_reset_integral, pitch_reset_integral, 0),
    PB_FIELD( 16, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, fw_control_yaw, yaw_reset_integral, 0),
    PB_FIELD( 17, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, disable_mc_yaw_control, fw_control_yaw, 0),
    PB_FIELD( 18, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_attitude_setpoint_pb, apply_flaps, disable_mc_yaw_control, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
