/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:18 2016. */

#include "vehicle_status.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t px4_vehicle_status_pb_fields[23] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, px4_vehicle_status_pb, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, system_id, timestamp, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, component_id, system_id, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, onboard_control_sensors_present, component_id, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, onboard_control_sensors_enabled, onboard_control_sensors_present, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, onboard_control_sensors_health, onboard_control_sensors_enabled, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, nav_state, onboard_control_sensors_health, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, arming_state, nav_state, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, hil_state, arming_state, 0),
    PB_FIELD( 10, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, failsafe, hil_state, 0),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, system_type, failsafe, 0),
    PB_FIELD( 12, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, is_rotary_wing, system_type, 0),
    PB_FIELD( 13, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, is_vtol, is_rotary_wing, 0),
    PB_FIELD( 14, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, vtol_fw_permanent_stab, is_vtol, 0),
    PB_FIELD( 15, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, in_transition_mode, vtol_fw_permanent_stab, 0),
    PB_FIELD( 16, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, rc_signal_lost, in_transition_mode, 0),
    PB_FIELD( 17, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, rc_input_mode, rc_signal_lost, 0),
    PB_FIELD( 18, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, data_link_lost, rc_input_mode, 0),
    PB_FIELD( 19, UINT32  , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, data_link_lost_counter, data_link_lost, 0),
    PB_FIELD( 20, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, engine_failure, data_link_lost_counter, 0),
    PB_FIELD( 21, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, engine_failure_cmd, engine_failure, 0),
    PB_FIELD( 22, BOOL    , REQUIRED, STATIC  , OTHER, px4_vehicle_status_pb, mission_failure, engine_failure_cmd, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
