/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Wed Oct 26 00:46:18 2016. */

#ifndef PB_WIND_ESTIMATE_PB_H_INCLUDED
#define PB_WIND_ESTIMATE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _px4_wind_estimate_pb {
    uint64_t timestamp;
    float windspeed_north;
    float windspeed_east;
    float covariance_north;
    float covariance_east;
/* @@protoc_insertion_point(struct:px4_wind_estimate_pb) */
} px4_wind_estimate_pb;

/* Default values for struct fields */

/* Initializer values for message structs */
#define px4_wind_estimate_pb_init_default        {0, 0, 0, 0, 0}
#define px4_wind_estimate_pb_init_zero           {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define px4_wind_estimate_pb_timestamp_tag       1
#define px4_wind_estimate_pb_windspeed_north_tag 2
#define px4_wind_estimate_pb_windspeed_east_tag  3
#define px4_wind_estimate_pb_covariance_north_tag 4
#define px4_wind_estimate_pb_covariance_east_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t px4_wind_estimate_pb_fields[6];

/* Maximum encoded size of messages (where known) */
#define px4_wind_estimate_pb_size                31

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WIND_ESTIMATE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
