#ifndef VM_VEHICLETYPE_T_H
#define VM_VEHICLETYPE_T_H

enum VM_VehicleType_t {
	VM_VEHICLE_TYPE_UNKNOWN_WING = 0, 
	VM_VEHICLE_TYPE_ROTARY_WING = 1, 
	VM_VEHICLE_TYPE_FIXED_WING = 2, 
	VM_VEHICLE_TYPE_VTOL = 3
};

#endif
