#ifndef PERF_IDS_H
#define PERF_IDS_H

#define CI_MAIN_TASK_PERF_ID        (33)
#define CI_SOCKET_RCV_PERF_ID       (34)
#define CF_APPMAIN_PERF_ID          (35)
#define CF_FILESIZE_PERF_ID         (36)
#define CF_FOPEN_PERF_ID            (37)
#define CF_FCLOSE_PERF_ID           (38)
#define CF_FREAD_PERF_ID            (39)
#define CF_FWRITE_PERF_ID           (40)
#define CF_REDLIGHT_PERF_ID         (41)
#define CF_CYCLE_ENG_PERF_ID        (42)
#define CF_QDIRFILES_PERF_ID        (43)
#define CS_APPMAIN_PERF_ID          (44)
#define DS_APPMAIN_PERF_ID          (45)
#define FM_APPMAIN_PERF_ID          (46)
#define FM_CHILD_TASK_PERF_ID       (47)
#define HK_APPMAIN_PERF_ID          (48)
#define HS_IDLETASK_PERF_ID         (49)
#define HS_APPMAIN_PERF_ID          (50)
#define LC_APPMAIN_PERF_ID          (51)
#define LC_WDT_SEARCH_PERF_ID       (52)
#define MD_APPMAIN_PERF_ID          (53)
#define MM_APPMAIN_PERF_ID          (54)
#define MM_SEGBREAK_PERF_ID         (55)
#define MM_EEPROM_POKE_PERF_ID      (56)
#define MM_EEPROM_FILELOAD_PERF_ID  (57)
#define MM_EEPROM_FILL_PERF_ID      (58)
#define SC_APPMAIN_PERF_ID          (59)
#define TO_MAIN_TASK_PERF_ID        (60)
#define SCH_APPMAIN_PERF_ID	    (61)
#define TO_SOCKET_SEND_PERF_ID      (62)

#endif

