---
config_base: ${PROJECT_SOURCE_DIR}
cpu_id: PPD
modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/public/core/osal/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/public/core/psp/pc-linux-wh/wh_design.yaml
