---
config_base: ${PROJECT_SOURCE_DIR}
  
modules:
  core:
    modules:
      osal:
        definition: ${PROJECT_SOURCE_DIR}/core/osal/fsw/posix-fast/wh_design.yaml
      psp:
        definition: ${PROJECT_SOURCE_DIR}/core/psp/fsw/pc-linux/wh_design.yaml


